"""Neo4j graph retriever for Elder pipeline."""

import logging
from typing import Any, Protocol

from neo4j import AsyncSession as AsyncNeo4jSession

from app.graphrag.retrieval_service import RetrievalService
from app.jobs.elder.schemas import RetrievedChunk

logger = logging.getLogger(__name__)


class GraphRetriever(Protocol):
    """Interface for graph retrieval."""
    
    async def search(
        self,
        query: str,
        ontology_ids: list[int],
        top_k: int = 10,
    ) -> list[RetrievedChunk]:
        """
        Search for relevant context in the graph.
        
        Args:
            query: Search query text
            ontology_ids: List of ontology IDs to scope the search
            top_k: Number of results to return
            
        Returns:
            List of retrieved chunks
        """
        ...


class Neo4jGraphRetriever:
    """Neo4j-based graph retriever using existing GraphRAG service."""
    
    def __init__(self, graph_session: AsyncNeo4jSession):
        """
        Initialize retriever.
        
        Args:
            graph_session: Neo4j async session
        """
        self.retrieval_service = RetrievalService(graph_session)
    
    async def search(
        self,
        query: str,
        ontology_ids: list[int],
        top_k: int = 10,
    ) -> list[RetrievedChunk]:
        """
        Search for relevant context in Neo4j graph.
        
        Uses the existing semantic search from GraphRAG module.
        Scopes results by ontology IDs and converts to RetrievedChunk format.
        
        Args:
            query: Search query text
            ontology_ids: List of ontology IDs to filter results
            top_k: Number of results to return
            
        Returns:
            List of retrieved chunks with scores
        """
        chunks = []
        
        # If no ontologies specified, search across all
        search_ontologies = ontology_ids if ontology_ids else [None]
        
        for ontology_id in search_ontologies:
            try:
                # Use existing semantic search
                results = await self.retrieval_service.semantic_search(
                    query=query,
                    ontology_id=ontology_id,
                    k=top_k,
                    score_threshold=0.0,
                    include_neighbors=False,
                )
                
                # Convert to RetrievedChunk format
                for node in results.get("results", []):
                    # Build context text from node data
                    context_text = node.get("context_text") or ""
                    if not context_text:
                        # Fallback to combining available text fields
                        text_parts = []
                        if node.get("text"):
                            text_parts.append(node["text"])
                        if node.get("autogenerated_text"):
                            text_parts.append(node["autogenerated_text"])
                        context_text = "\n".join(text_parts) if text_parts else node.get("name", "")
                    
                    chunk = RetrievedChunk(
                        node_id=node.get("node_id", ""),
                        node_label=node.get("labels", [None])[0] if node.get("labels") else None,
                        text=context_text,
                        score=node.get("score", 0.0),
                        source=f"ontology_{ontology_id}" if ontology_id else None,
                    )
                    chunks.append(chunk)
                    
            except Exception as e:
                logger.error(f"Error searching ontology {ontology_id}: {e}")
                # Continue with other ontologies
                continue
        
        # Sort by score and take top_k
        chunks.sort(key=lambda c: c.score, reverse=True)
        return chunks[:top_k]
