"""Retrieval service for semantic search over Neo4j."""

from __future__ import annotations

import asyncio
from typing import Any

from neo4j import AsyncSession as AsyncNeo4jSession

from app.graphrag.embedding_service import EmbeddingService


class RetrievalService:
    """Service for semantic retrieval from Neo4j."""

    def __init__(self, graph_session: AsyncNeo4jSession) -> None:
        self.graph_session = graph_session
        self.embedding_service = EmbeddingService(graph_session)

    async def semantic_search(
        self,
        query: str,
        ontology_id: int | None = None,
        k: int = 10,
        score_threshold: float = 0.0,
        include_neighbors: bool = True,
        neighbor_limit: int = 10,
    ) -> dict[str, Any]:
        """
        Perform semantic search over Neo4j nodes.

        Args:
            query: Search query text
            ontology_id: Filter by ontology ID
            k: Number of results to return
            score_threshold: Minimum similarity score (0-1)
            include_neighbors: Whether to expand neighborhood
            neighbor_limit: Max neighbors per node

        Returns:
            Dict with results and metadata
        """
        # Embed the query
        loop = asyncio.get_event_loop()
        query_embedding = await loop.run_in_executor(
            None, self.embedding_service.embed_text, query
        )

        # Perform vector similarity search
        search_query = """
        CALL db.index.vector.queryNodes('entity_text_vec_idx', $k, $query_embedding)
        YIELD node, score
        WHERE score >= $score_threshold
            AND ($ontology_id IS NULL OR node.ontology_id = $ontology_id)
        RETURN node, score
        ORDER BY score DESC
        LIMIT $k
        """

        result = await self.graph_session.run(
            search_query,
            k=k * 2,  # Fetch more to filter
            query_embedding=query_embedding,
            score_threshold=score_threshold,
            ontology_id=ontology_id,
        )

        records = await result.data()

        if not records:
            return {
                "query": query,
                "results": [],
                "total": 0,
                "ontology_id": ontology_id,
            }

        # Extract nodes and scores
        nodes_data = []
        for record in records[:k]:
            node = record["node"]
            score = record["score"]

            node_info = {
                "node_id": node.get("entity_instance_id"),
                "name": node.get("name"),
                "labels": list(node.labels),
                "score": score,
                "context_text": node.get("context_text"),
                "text": node.get("text"),
                "autogenerated_text": node.get("autogenerated_text"),
                "ontology_id": node.get("ontology_id"),
                "properties": dict(node),
            }

            # Optionally fetch neighbors
            if include_neighbors:
                neighbors = await self._fetch_neighbors(
                    node.get("entity_instance_id"), neighbor_limit
                )
                node_info["neighbors"] = neighbors

            nodes_data.append(node_info)

        return {
            "query": query,
            "results": nodes_data,
            "total": len(nodes_data),
            "ontology_id": ontology_id,
        }

    async def _fetch_neighbors(
        self, node_id: str, limit: int = 10
    ) -> list[dict[str, Any]]:
        """
        Fetch neighboring nodes.

        Args:
            node_id: Node ID
            limit: Max neighbors to return

        Returns:
            List of neighbor info dicts
        """
        query = """
        MATCH (n:EntityInstance {entity_instance_id: $node_id})-[r]->(m:EntityInstance)
        RETURN type(r) AS rel_type, 
               m.entity_instance_id AS node_id,
               m.name AS name,
               head(labels(m)) AS label
        LIMIT $limit
        """

        result = await self.graph_session.run(query, node_id=node_id, limit=limit)
        records = await result.data()

        neighbors = []
        for record in records:
            neighbors.append(
                {
                    "rel_type": record["rel_type"],
                    "node_id": record["node_id"],
                    "name": record["name"],
                    "label": record["label"],
                }
            )

        return neighbors

    async def get_context_for_llm(
        self,
        query: str,
        ontology_id: int | None = None,
        k: int = 5,
        score_threshold: float = 0.5,
    ) -> str:
        """
        Get formatted context text for LLM from semantic search.

        Args:
            query: Search query
            ontology_id: Filter by ontology
            k: Number of results
            score_threshold: Minimum score

        Returns:
            Formatted context string
        """
        results = await self.semantic_search(
            query=query,
            ontology_id=ontology_id,
            k=k,
            score_threshold=score_threshold,
            include_neighbors=True,
        )

        if not results["results"]:
            return "No relevant information found."

        context_parts = [f"Query: {query}\n", "Relevant Information:\n"]

        for i, node in enumerate(results["results"], 1):
            context_parts.append(f"\n{i}. {node['name']} (Score: {node['score']:.2f})")

            if node.get("context_text"):
                context_parts.append(f"\n{node['context_text']}")

            if node.get("neighbors"):
                neighbor_names = [n["name"] for n in node["neighbors"][:5]]
                if neighbor_names:
                    context_parts.append(f"\nRelated: {', '.join(neighbor_names)}")

            context_parts.append("\n" + "-" * 40)

        return "\n".join(context_parts)
