"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import DashboardLayout from "@/app/components/DashboardLayout";
import AuthGuard from "@/app/components/auth/AuthGuard";
import { useAuth } from "@/app/components/auth/AuthProvider";
import { getWriterJob } from "@/app/lib/agentAPI";
import { useAgentById } from "@/app/lib/useAgentById";
import { useConcepts } from "@/app/lib/useConcept";
import { useWorld } from "@/app/lib/useWorld";
import { usePages } from "@/app/lib/usePage";
import { getPage, updatePage } from "@/app/lib/pagesAPI";
import EditableContent from "@/app/components/editor/EditableContent";
import EventTimeline from "@/app/components/see_page/EventTimeline";
import RelationshipMapTab from "@/app/components/see_page/RelationshipMapTab";
import Image from "next/image";
import { Loader2 } from "lucide-react";
import { useTranslation } from "@/app/hooks/useTranslation";
import CreatePageForm from "@/app/components/create_page/CreatePageForm";

export default function ReviewPage() {
  const { t } = useTranslation();
  const { agentID, jobID } = useParams();
  const router = useRouter();
  const { token } = useAuth();
  const { agent } = useAgentById(Number(agentID));
  const { concepts } = useConcepts(agent?.world_id);
  const { world } = useWorld(agent?.world_id);
  const { pages: worldPages } = usePages(
    world?.id ? { gameworld_id: world.id } : {},
  );

  const [job, setJob] = useState<any>(null);
  const [newPages, setNewPages] = useState<any[]>([]);
  const [updatedPages, setUpdatedPages] = useState<any[]>([]);
  const [activeIdx, setActiveIdx] = useState(0);
  const [activeType, setActiveType] = useState<"new" | "updated">("new");

  async function refreshPage(id: number, idx: number, type: "new" | "updated") {
    if (!token) return;
    try {
      const p = await getPage(id, token);
      if (type === "new") {
        setNewPages((pgs) => {
          const copy = [...pgs];
          copy[idx] = p;
          return copy;
        });
      } else {
        setUpdatedPages((pgs) => {
          const copy = [...pgs];
          copy[idx] = p;
          return copy;
        });
      }
    } catch (err) {
      console.error("Failed to refresh page", err);
    }
  }

  useEffect(() => {
    if (!jobID || !token) return;
    getWriterJob(jobID as string, token)
      .then(async (data) => {
        setJob(data);
        if (data.status === "done") {
          const newList = data.generated?.pages || data.pages || [];
          const updList =
            data.generated?.auto_updated || data.auto_updated || [];

          const newFull = await Promise.all(
            newList.map(async (p: any) => {
              try {
                return await getPage(p.id, token);
              } catch {
                return null;
              }
            }),
          );

          const updFull = await Promise.all(
            updList.map(async (p: any) => {
              try {
                return await getPage(p.id, token);
              } catch {
                return null;
              }
            }),
          );

          setNewPages(newFull.filter(Boolean));
          setUpdatedPages(updFull.filter(Boolean));
          setActiveType(newFull.length > 0 ? "new" : "updated");
          setActiveIdx(0);
        }
      })
      .catch((err) => {
        console.error("ERROR!", err);
      });
  }, [jobID, token]);

  if (!job)
    return (
      <AuthGuard>
        <DashboardLayout>
          <div className="p-6 text-[var(--foreground)]">{t("loading")}</div>
        </DashboardLayout>
      </AuthGuard>
    );

  if (job.status !== "done")
    return (
      <AuthGuard>
        <DashboardLayout>
          <div className="p-6 text-[var(--foreground)] flex items-center gap-2">
            <Loader2 className="animate-spin" /> {t("summoning_scribes")}
          </div>
        </DashboardLayout>
      </AuthGuard>
    );

  if (newPages.length === 0 && updatedPages.length === 0)
    return (
      <AuthGuard>
        <DashboardLayout>
          <div className="min-h-[60vh] flex flex-col items-center justify-center px-4">
            <div className="text-xl font-semibold">
              {t("all_pages_updated")}
            </div>
            <button
              onClick={() => router.push(`/agent_writer?agent=${agentID}`)}
              className="mt-4 px-4 py-2 rounded-xl bg-[var(--primary)] text-white font-bold shadow"
            >
              {t("return_agent_writer")}
            </button>
          </div>
        </DashboardLayout>
      </AuthGuard>
    );

  const page =
    activeType === "new" ? newPages[activeIdx] : updatedPages[activeIdx];
  const pageConcept = concepts?.find((c) => c.id === page?.concept_id);

  async function handleSaveNotes(idx: number, newContent: string) {
    if (!token) return;
    try {
      await updatePage(page.id, { autogenerated_content: newContent }, token);
      refreshPage(page.id, idx, activeType);
    } catch (err) {
      console.error("Failed to save notes", err);
    }
  }

  async function handleEditPage(payload: unknown) {
    if (!token || !page) return;
    try {
      await updatePage(page.id, payload, token);
      refreshPage(page.id, activeIdx, activeType);
    } catch (err) {
      console.error("Failed to update page", err);
    }
  }

  return (
    <AuthGuard>
      <DashboardLayout>
        <div className="min-h-screen w-full bg-[var(--background)] text-[var(--foreground)] px-2 sm:px-6 py-10 flex justify-center">
          <div className="w-full max-w-screen-2xl mx-auto flex flex-col md:flex-row gap-6">
            <div className="md:w-64 space-y-4">
              {newPages.length > 0 && (
                <div className="bg-[var(--card)] border border-green-600 rounded-xl p-4 shadow">
                  <h2 className="text-lg font-bold text-green-700 mb-3">
                    New Pages
                  </h2>
                  <div className="flex flex-col gap-2">
                    {newPages.map((p, idx) => (
                      <button
                        key={p.id}
                        onClick={() => {
                          setActiveType("new");
                          setActiveIdx(idx);
                        }}
                        className={`text-left px-3 py-2 rounded-lg border transition-all ${
                          activeType === "new" && activeIdx === idx
                            ? "bg-green-600/20 border-green-600"
                            : "border-transparent hover:border-green-600/50"
                        }`}
                      >
                        <div className="font-semibold text-green-700">
                          {p.name}
                        </div>
                        <div className="text-xs text-[var(--muted-foreground)]">
                          {concepts?.find((c) => c.id === p.concept_id)?.name ||
                            ""}
                        </div>
                      </button>
                    ))}
                  </div>
                </div>
              )}

              {updatedPages.length > 0 && (
                <div className="bg-[var(--card)] border border-blue-600 rounded-xl p-4 shadow">
                  <h2 className="text-lg font-bold text-blue-700 mb-3">
                    Updated Pages
                  </h2>
                  <div className="flex flex-col gap-2">
                    {updatedPages.map((p, idx) => (
                      <button
                        key={p.id}
                        onClick={() => {
                          setActiveType("updated");
                          setActiveIdx(idx);
                        }}
                        className={`text-left px-3 py-2 rounded-lg border transition-all ${
                          activeType === "updated" && activeIdx === idx
                            ? "bg-blue-600/20 border-blue-600"
                            : "border-transparent hover:border-blue-600/50"
                        }`}
                      >
                        <div className="font-semibold text-blue-700">
                          {p.name}
                        </div>
                        <div className="text-xs text-[var(--muted-foreground)]">
                          {concepts?.find((c) => c.id === p.concept_id)?.name ||
                            ""}
                        </div>
                      </button>
                    ))}
                  </div>
                </div>
              )}
            </div>

            <div className="flex-1 space-y-8">
              {page && (
                <>
                  <div className="flex items-center gap-3">
                    {concepts?.find((c) => c.id === page.concept_id)?.logo && (
                      <Image
                        src={
                          concepts.find((c) => c.id === page.concept_id)!.logo
                        }
                        alt="concept logo"
                        width={40}
                        height={40}
                        className="rounded-full border border-[var(--border)]"
                      />
                    )}
                    <h1 className="text-2xl font-bold">{page.name}</h1>
                  </div>

                  <EditableContent
                    content={page.autogenerated_content}
                    canEdit={true}
                    onSaveContent={(content) =>
                      handleSaveNotes(activeIdx, content)
                    }
                    pageType="worlds"
                    pageName={page.name}
                    className="mt-4"
                  />

                  <div>
                    <h2 className="text-xl font-semibold mb-2">
                      {t("tab_key_events")}
                    </h2>
                    <EventTimeline
                      pageId={page.id}
                      events={page.key_events || []}
                      pages={worldPages}
                      onUpdated={() =>
                        refreshPage(page.id, activeIdx, activeType)
                      }
                    />
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-2">
                      {t("tab_relationships")}
                    </h2>
                    <RelationshipMapTab page={page} pages={worldPages} />
                  </div>

                  <CreatePageForm
                    selectedWorld={world}
                    selectedConcept={pageConcept}
                    token={token as string}
                    initialValues={page}
                    mode="edit"
                    onSubmit={handleEditPage}
                  />
                </>
              )}
            </div>
          </div>
        </div>
      </DashboardLayout>
    </AuthGuard>
  );
}
