services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

    volumes:
      - ./frontend/public:/public   

  backend:
    build: ./backend
    ports:
      - "8000:8000"    
    env_file:
     - ./backend/.env      

    volumes:
      - ./backend/data:/app/data         # maps host ./data to /backend/data in the container      
 
