services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"    
    env_file:
     - ./backend/.env       
      # Put your backend env variables here, e.g.:
      # - DATABASE_URL=sqlite:///data.db
      # - SECRET_KEY=your_secret
      # or reference an .env file
      # env_file:
      #   - ./backend/.env