services:
  frontend:
    user: "33:33"
    build:
      context: ./frontend
      network: host
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/uploads:/app/uploads

  backend:
    build:
      context: ./backend
      network: host
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./backend/data:/app/data
      - ./frontend/uploads:/app/uploads
    depends_on:
      - redis

  celery:
    build:
      context: ./backend
      network: host
    command: celery -A app.task_queue.celery_app worker --loglevel=info
    env_file:
      - ./backend/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./backend/data:/app/data
      - ./frontend/uploads:/app/uploads
    depends_on:
      - backend
      - redis

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"