from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field, field_validator, model_validator
from pydantic import ConfigDict

from app.models.ontology import AuthorType


class OntologyInstancePropertyValue(BaseModel):
    model_config = ConfigDict(extra="ignore")
    definition_id: int
    value: Any


class OntologyInstanceRelationshipCreate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    definition_id: int
    target_alias: str | None = None
    target_entity_instance_id: str | None = None
    data: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_target(
        cls, values: "OntologyInstanceRelationshipCreate"
    ) -> "OntologyInstanceRelationshipCreate":
        alias = values.target_alias.strip() if values.target_alias else None
        target_id = (
            values.target_entity_instance_id.strip()
            if values.target_entity_instance_id
            else None
        )
        if bool(alias) == bool(target_id):
            raise ValueError(
                "Provide exactly one of target_alias or target_entity_instance_id"
            )
        if alias:
            values.target_alias = alias
        else:
            values.target_alias = None
        if target_id:
            values.target_entity_instance_id = target_id
        else:
            values.target_entity_instance_id = None
        return values


class OntologyInstanceRelationshipRead(BaseModel):
    model_config = ConfigDict(extra="ignore")
    relationship_instance_id: str
    definition_id: int
    target_entity_id: str
    destiny_entity_definition_id: int | None = None
    data: dict[str, Any] = Field(default_factory=dict)


class OntologyInstanceEntityCreate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    definition_id: int
    alias: str
    text: str | None = None
    node_avatar_url: str | None = None
    autogenerated_text: str | None = None
    created_date: datetime | None = None
    last_updated_date: datetime | None = None
    author_type: AuthorType
    author_id: str
    properties: list[OntologyInstancePropertyValue] = Field(default_factory=list)
    relationships: list[OntologyInstanceRelationshipCreate] = Field(
        default_factory=list
    )

    @field_validator("alias", "author_id", mode="before")
    def validate_non_empty(cls, value: str, info):
        if value is None:
            raise ValueError(f"{info.field_name} cannot be empty")
        value = value.strip()
        if not value:
            raise ValueError(f"{info.field_name} cannot be empty")
        return value

    # text is optional and may be empty


class OntologyInstanceEntityRead(BaseModel):
    model_config = ConfigDict(extra="ignore")
    entity_instance_id: str
    definition_id: int
    alias: str | None = None
    text: str
    text_linked: str | None = None
    node_avatar_url: str | None = None
    autogenerated_text: str | None = None
    autogenerated_text_linked: str | None = None
    created_date: datetime
    last_updated_date: datetime
    author_type: AuthorType
    author_id: str
    properties: list[OntologyInstancePropertyValue] = Field(default_factory=list)
    relationships: list[OntologyInstanceRelationshipRead] = Field(default_factory=list)


class TimelineEventBase(BaseModel):
    model_config = ConfigDict(extra="ignore")
    title: str
    description: str
    source_instance_id: str | None = None
    related_instance_ids: list[str] = Field(default_factory=list)
    before_event_id: str | None = None
    after_event_id: str | None = None

    @field_validator("title", "description", mode="before")
    def validate_text(cls, value: str, info):
        if value is None:
            raise ValueError(f"{info.field_name} cannot be empty")
        value = value.strip()
        if not value:
            raise ValueError(f"{info.field_name} cannot be empty")
        return value


class TimelineEventCreate(TimelineEventBase):
    timeline_event_id: str | None = None


class TimelineEventUpdate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    title: str | None = None
    description: str | None = None
    source_instance_id: str | None = None
    related_instance_ids: list[str] | None = None
    before_event_id: str | None = None
    after_event_id: str | None = None


class TimelineEventRead(TimelineEventBase):
    timeline_event_id: str
    instance_id: str
    ontology_id: int
    created_at: datetime
    updated_at: datetime


class OntologyInstanceBase(BaseModel):
    model_config = ConfigDict(extra="ignore")
    name: str


class OntologyInstanceCreate(OntologyInstanceBase):
    model_config = ConfigDict(extra="ignore")
    ontology_id: int
    entities: list[OntologyInstanceEntityCreate]
    timeline_events: list[TimelineEventCreate] = Field(default_factory=list)


class OntologyInstanceUpdate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    name: str | None = None
    entities: list[OntologyInstanceEntityCreate] | None = None
    timeline_events: list[TimelineEventCreate] | None = None


class OntologyInstanceRead(OntologyInstanceBase):
    model_config = ConfigDict(extra="ignore")
    instance_id: str
    ontology_id: int
    created_at: datetime
    updated_at: datetime
    entities: list[OntologyInstanceEntityRead]
    timeline_events: list[TimelineEventRead] = Field(default_factory=list)
