"""
Tests for the new Architect V2 pipeline.
"""

from __future__ import annotations

from datetime import datetime

import pytest

from app.jobs.architect.architect_v2 import ArchitectOrchestratorV2
from app.jobs.architect.schemas import (
    ChunkExtractionResponse,
    ChunkEntityProposal,
    ReconciliationResponse,
    ReconciledExistingEntity,
    ReconciledNewEntity,
)
from app.jobs.elder.schemas import RetrievedChunk
from app.schemas.ontology_instance import (
    OntologyInstanceEntityRead,
    OntologyInstanceRead,
)


class StubLLMV2:
    """Stub LLM client for V2 pipeline tests."""

    def __init__(self, responses: dict[str, str]) -> None:
        self._responses = responses
        self._call_count = 0

    async def chat(self, *args, **kwargs) -> str:
        """Return canned responses based on call count."""
        messages = kwargs.get("messages", [])
        if messages and "reconciling" in messages[0]["content"].lower():
            return self._responses.get("reconciliation", "{}")
        else:
            # Chunk extraction
            response_key = f"chunk_{self._call_count}"
            self._call_count += 1
            return self._responses.get(response_key, '{"entities": []}')


class StubRetrieverV2:
    """Stub retriever for V2 pipeline tests."""

    async def search_aliases(self, **kwargs):
        """Return mock existing entities."""
        return [
            RetrievedChunk(
                node_id="char_001",
                node_label="Jessie Williams",
                node_alias="Jessie Williams",
                instance_id="instance-1",
                text="",
                score=0.95,
                confidence_pct=95.0,
                source="Character",
            ),
            RetrievedChunk(
                node_id="org_101",
                node_label="Camarilla",
                node_alias="Camarilla",
                instance_id="instance-2",
                text="",
                score=0.92,
                confidence_pct=92.0,
                source="Organization",
            ),
        ]


class StubPolicy:
    """Stub model policy."""

    def get_model(self, task):
        return "fake-model"


@pytest.mark.asyncio
async def test_architect_v2_chunk_extraction():
    """Test that chunk-level extraction works correctly."""
    chunk_response = """
    {
      "entities": [
        {
          "name": "Jessie Williams",
          "ontology": "Character",
          "confidence": 0.92,
          "why": "Main character in the scene."
        },
        {
          "name": "Camarilla",
          "ontology": "Organization",
          "confidence": 0.88,
          "why": "Organization mentioned."
        }
      ]
    }
    """

    llm = StubLLMV2({"chunk_0": chunk_response})
    orchestrator = ArchitectOrchestratorV2(
        llm_client=llm,
        model_policy=StubPolicy(),
        graph_retriever=StubRetrieverV2(),
        chunk_size=50,
        chunk_overlap=10,
    )

    now = datetime.utcnow()
    entity = OntologyInstanceEntityRead(
        entity_instance_id="entity-1",
        definition_id=1,
        alias="Story",
        text="Jessie Williams met with the Camarilla leadership.",
        text_linked=None,
        node_avatar_url=None,
        autogenerated_text="",
        autogenerated_text_linked=None,
        created_date=now,
        updated_date=now,
        last_updated_date=now,
        author_type="human",
        author_id="user-1",
    )

    instance = OntologyInstanceRead(
        instance_id="test-instance",
        ontology_id=1,
        name="Test Instance",
        entities=[entity],
        created_date=now,
        updated_date=now,
        created_at=now,
        updated_at=now,
    )

    entity_definitions = [
        {"id": 1, "name": "Character", "description": "People and characters"},
        {"id": 2, "name": "Organization", "description": "Groups and organizations"},
    ]

    result = await orchestrator.analyse(
        agent_ontology_ids=[1],
        ontology_instance=instance,
        entity_definitions=entity_definitions,
    )

    assert result["pipeline_version"] == "v2"
    assert result["chunk_count"] > 0
    assert "proposals" in result


@pytest.mark.asyncio
async def test_architect_v2_deduplication():
    """Test that deduplication works correctly."""
    orchestrator = ArchitectOrchestratorV2(
        llm_client=StubLLMV2({}),
        model_policy=StubPolicy(),
        graph_retriever=StubRetrieverV2(),
    )

    # Create mock chunk results with exact duplicates
    chunk_results = [
        {
            "chunk_id": "chunk_000",
            "chunk_index": 0,
            "entities": [
                ChunkEntityProposal(
                    name="Jessie Williams",
                    ontology="Character",
                    confidence=0.92,
                    why="Main character",
                ),
            ],
        },
        {
            "chunk_id": "chunk_001",
            "chunk_index": 1,
            "entities": [
                ChunkEntityProposal(
                    name="Jessie Williams",  # Exact duplicate
                    ontology="Character",
                    confidence=0.85,
                    why="Referenced again",
                ),
            ],
        },
    ]

    deduped = orchestrator._deduplicate_entities(chunk_results)

    # Should have 1 entity (exact duplicates merged)
    assert len(deduped) == 1
    # Should keep the name
    assert deduped[0].name == "Jessie Williams"
    # Should average confidence
    expected_confidence = (0.92 + 0.85) / 2
    assert abs(deduped[0].confidence - expected_confidence) < 0.01
    # Should have both chunk indices
    assert len(deduped[0].chunk_indices) == 2


@pytest.mark.asyncio
async def test_architect_v2_reconciliation():
    """Test that reconciliation with existing entities works."""
    reconciliation_response = """
    {
      "existing": [
        {
          "proposed_name": "Jessie Williams",
          "matched_node_id": "char_001",
          "ontology": "Character"
        }
      ],
      "new": [
        {
          "name": "Baron Jackie",
          "ontology": "Character"
        }
      ]
    }
    """

    llm = StubLLMV2({"reconciliation": reconciliation_response})
    orchestrator = ArchitectOrchestratorV2(
        llm_client=llm,
        model_policy=StubPolicy(),
        graph_retriever=StubRetrieverV2(),
    )

    parsed = orchestrator._parse_reconciliation(reconciliation_response)

    assert len(parsed.existing) == 1
    assert len(parsed.new) == 1
    assert parsed.existing[0].proposed_name == "Jessie Williams"
    assert parsed.existing[0].matched_node_id == "char_001"
    assert parsed.new[0].name == "Baron Jackie"


@pytest.mark.asyncio
async def test_architect_v2_canonical_alias():
    """Test the canonical alias normalization."""
    orchestrator = ArchitectOrchestratorV2(
        llm_client=StubLLMV2({}),
        model_policy=StubPolicy(),
        graph_retriever=StubRetrieverV2(),
    )

    # Test parenthesis removal
    assert orchestrator._canonical_alias("Mithras (god)") == "mithras"

    # Test title removal
    assert orchestrator._canonical_alias("Dr. Smith") == "smith"
    assert orchestrator._canonical_alias("Professor Jones") == "jones"

    # Test article removal (only at the beginning)
    assert (
        orchestrator._canonical_alias("The Court of Nightmares")
        == "court of nightmares"
    )
    assert orchestrator._canonical_alias("A New World") == "new world"

    # Test case normalization
    assert orchestrator._canonical_alias("JOHN SMITH") == "john smith"

    # Test that longer names are preferred in dedup
    assert orchestrator._canonical_alias("Jessie") == "jessie"
    assert orchestrator._canonical_alias("Jessie Williams") == "jessie williams"
