from __future__ import annotations

import os

import pytest

from app.models.ontology import AuthorType, Cardinality, PropertyDataType
from app.models.user import UserRole

pytestmark = pytest.mark.skipif(
    not os.getenv("NEO4J_TEST_URI"),
    reason="Neo4j test environment not configured",
)


@pytest.mark.asyncio
async def test_create_ontology_instance_flow(client):
    # Bootstrap admin user
    admin_payload = {
        "username": "graph-admin",
        "password": "GraphAdmin1",
        "full_name": "Graph Admin",
        "email": "graph-admin@example.com",
        "timezone": "UTC",
        "role": UserRole.ADMIN.value,
    }
    register_response = await client.post("/users/", json=admin_payload)
    assert register_response.status_code == 201, register_response.text

    token_response = await client.post(
        "/auth/token",
        data={
            "username": admin_payload["username"],
            "password": admin_payload["password"],
        },
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    assert token_response.status_code == 200, token_response.text
    token = token_response.json()["access_token"]
    headers = {"Authorization": f"Bearer {token}"}

    # Create ontology definition
    ontology_response = await client.post(
        "/ontologies/",
        json={"name": "Graph Test", "description": "Test ontology"},
        headers=headers,
    )
    assert ontology_response.status_code == 201, ontology_response.text
    ontology_id = ontology_response.json()["id"]

    entity_payload = {
        "name": "Character",
        "description": "Character definition",
        "auto_generatable": False,
        "author_type": AuthorType.HUMAN.value,
        "user_id": "def-1",
    }
    entity_response = await client.post(
        f"/ontologies/{ontology_id}/entities",
        json=entity_payload,
        headers=headers,
    )
    assert entity_response.status_code == 201, entity_response.text
    entity_definition = entity_response.json()
    entity_id = entity_definition["id"]

    property_payload = {
        "name": "Age",
        "cardinality": Cardinality.ONE.value,
        "data_type": PropertyDataType.NUMBER.value,
        "author_type": AuthorType.HUMAN.value,
        "user_id": "def-1",
    }
    property_response = await client.post(
        f"/ontologies/{ontology_id}/entities/{entity_id}/properties",
        json=property_payload,
        headers=headers,
    )
    assert property_response.status_code == 201, property_response.text
    property_definition_id = property_response.json()["id"]

    relationship_payload = {
        "name": "Knows",
        "bi_directional": True,
        "author_type": AuthorType.HUMAN.value,
        "user_id": "def-1",
        "destiny_entity_id": destiny_entity_id,
    }
    relationship_response = await client.post(
        f"/ontologies/{ontology_id}/entities/{entity_id}/relationships",
        json=relationship_payload,
        headers=headers,
    )
    assert relationship_response.status_code == 201, relationship_response.text
    relationship_definition_id = relationship_response.json()["id"]

    hero_relationships = await client.get(
        f"/ontologies/{ontology_id}/entities/{entity_id}/relationships",
        headers=headers,
    )
    assert hero_relationships.status_code == 200
    relationships_data = hero_relationships.json()
    assert any(
        rel["destiny_entity_id"] == destiny_entity_id for rel in relationships_data
    )

    mirror_response = await client.get(
        f"/ontologies/{ontology_id}/entities/{destiny_entity_id}/relationships",
        headers=headers,
    )
    assert mirror_response.status_code == 200
    mirror_data = mirror_response.json()
    assert any(rel["destiny_entity_id"] == entity_id for rel in mirror_data)

    # Create ontology instance
    instance_payload = {
        "ontology_id": ontology_id,
        "name": "Graph Instance",
        "entities": [
            {
                "definition_id": entity_id,
                "alias": "hero",
                "text": "Hero character",
                "node_avatar_url": "https://example.com/hero.png",
                "autogenerated_text": "Hero summary",
                "created_date": "2025-01-01T00:00:00Z",
                "last_updated_date": "2025-01-01T00:00:00Z",
                "author_type": AuthorType.HUMAN.value,
                "author_id": "user-hero",
                "properties": [{"definition_id": property_definition_id, "value": 30}],
                "relationships": [
                    {
                        "definition_id": relationship_definition_id,
                        "target_alias": "villain",
                        "data": {"met": "2025"},
                    }
                ],
            },
            {
                "definition_id": entity_id,
                "alias": "villain",
                "text": "Villain character",
                "node_avatar_url": "https://example.com/villain.png",
                "autogenerated_text": None,
                "created_date": "2025-01-02T00:00:00Z",
                "last_updated_date": "2025-01-02T00:00:00Z",
                "author_type": AuthorType.HUMAN.value,
                "author_id": "user-villain",
                "properties": [{"definition_id": property_definition_id, "value": 40}],
                "relationships": [],
            },
        ],
    }
    instance_response = await client.post(
        "/ontology-instances/", json=instance_payload, headers=headers
    )
    assert instance_response.status_code == 201, instance_response.text
    instance = instance_response.json()
    instance_id = instance["instance_id"]

    # Fetch instance
    fetched = await client.get(f"/ontology-instances/{instance_id}", headers=headers)
    assert fetched.status_code == 200
    fetched_data = fetched.json()
    hero_entity = next(e for e in fetched_data["entities"] if e["alias"] == "hero")
    assert hero_entity["text"] == "Hero character"
    assert hero_entity["author_id"] == "user-hero"

    # Update instance (rename)
    update_response = await client.put(
        f"/ontology-instances/{instance_id}",
        json={"name": "Updated Graph Instance"},
        headers=headers,
    )
    assert update_response.status_code == 200
    assert update_response.json()["name"] == "Updated Graph Instance"

    # Delete instance
    delete_response = await client.delete(
        f"/ontology-instances/{instance_id}", headers=headers
    )
    assert delete_response.status_code == 204


@pytest.mark.asyncio
async def test_delete_ontology_instance_cleans_embeddings(client):
    """Test that deleting an ontology instance properly removes all embeddings."""
    # Bootstrap admin user
    admin_payload = {
        "username": "embed-admin",
        "password": "EmbedAdmin1",
        "full_name": "Embed Admin",
        "email": "embed-admin@example.com",
        "timezone": "UTC",
        "role": UserRole.ADMIN.value,
    }
    register_response = await client.post("/users/", json=admin_payload)
    assert register_response.status_code == 201, register_response.text

    token_response = await client.post(
        "/auth/token",
        data={
            "username": admin_payload["username"],
            "password": admin_payload["password"],
        },
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    assert token_response.status_code == 200, token_response.text
    token = token_response.json()["access_token"]
    headers = {"Authorization": f"Bearer {token}"}

    # Create ontology definition
    ontology_response = await client.post(
        "/ontologies/",
        json={"name": "Embed Test Ontology", "description": "Test ontology for embeddings"},
        headers=headers,
    )
    assert ontology_response.status_code == 201, ontology_response.text
    ontology_id = ontology_response.json()["id"]

    # Create entity definition
    entity_payload = {
        "name": "TestEntity",
        "description": "Entity for testing embeddings",
        "auto_generatable": False,
        "author_type": AuthorType.HUMAN.value,
        "user_id": "test-user",
    }
    entity_response = await client.post(
        f"/ontologies/{ontology_id}/entities",
        json=entity_payload,
        headers=headers,
    )
    assert entity_response.status_code == 201, entity_response.text
    entity_id = entity_response.json()["id"]

    # Create property definition
    property_payload = {
        "name": "TestProperty",
        "cardinality": Cardinality.ONE.value,
        "data_type": PropertyDataType.TEXT.value,
        "author_type": AuthorType.HUMAN.value,
        "user_id": "test-user",
    }
    property_response = await client.post(
        f"/ontologies/{ontology_id}/entities/{entity_id}/properties",
        json=property_payload,
        headers=headers,
    )
    assert property_response.status_code == 201, property_response.text
    property_definition_id = property_response.json()["id"]

    # Create ontology instance with entities and timeline events
    instance_payload = {
        "ontology_id": ontology_id,
        "name": "Test Instance with Embeddings",
        "entities": [
            {
                "definition_id": entity_id,
                "alias": "entity1",
                "text": "This is entity one with some text for embedding",
                "node_avatar_url": None,
                "autogenerated_text": "Generated text for entity one",
                "created_date": "2025-01-01T00:00:00Z",
                "last_updated_date": "2025-01-01T00:00:00Z",
                "author_type": AuthorType.HUMAN.value,
                "author_id": "test-user",
                "properties": [{"definition_id": property_definition_id, "value": "test"}],
                "relationships": [],
            },
        ],
        "timeline_events": [
            {
                "title": "Test Event",
                "description": "A test timeline event with embeddings",
                "source_instance_id": None,
                "related_instance_ids": [],
                "before_event_id": None,
                "after_event_id": None,
            }
        ],
    }
    instance_response = await client.post(
        "/ontology-instances/", json=instance_payload, headers=headers
    )
    assert instance_response.status_code == 201, instance_response.text
    instance = instance_response.json()
    instance_id = instance["instance_id"]

    # Import neo4j session to verify embeddings directly
    from app.graph.neo4j import get_neo4j_session
    
    # Get Neo4j session
    async for graph_session in get_neo4j_session():
        # Verify that chunks can be created (simulate embedding)
        # Check that the instance and its entities exist
        check_result = await graph_session.run(
            """
            MATCH (i:OntologyInstance {instance_id: $instance_id})
            OPTIONAL MATCH (i)-[:HAS_ENTITY]->(e:EntityInstance)
            OPTIONAL MATCH (i)-[:HAS_TIMELINE_EVENT]->(t:TimelineEvent)
            RETURN i, count(DISTINCT e) as entity_count, count(DISTINCT t) as event_count
            """,
            instance_id=instance_id,
        )
        check_data = await check_result.single()
        assert check_data is not None
        assert check_data["entity_count"] > 0
        assert check_data["event_count"] > 0
        
        # Create some test chunks to simulate embeddings
        await graph_session.run(
            """
            MATCH (i:OntologyInstance {instance_id: $instance_id})-[:HAS_ENTITY]->(e:EntityInstance)
            CREATE (e)-[:HAS_CHUNK]->(c:EntityChunk {
                chunk_id: randomUUID(),
                parent_entity_instance_id: e.entity_instance_id,
                instance_id: $instance_id,
                ontology_id: $ontology_id,
                chunk_index: 0,
                chunk_type: "text",
                text_chunk: "Test chunk",
                text_embedding: [0.1, 0.2, 0.3],
                is_embedded: true
            })
            SET e.is_embedded = true
            """,
            instance_id=instance_id,
            ontology_id=ontology_id,
        )
        
        # Verify chunks were created
        chunks_before = await graph_session.run(
            """
            MATCH (c:EntityChunk {instance_id: $instance_id})
            RETURN count(c) as chunk_count
            """,
            instance_id=instance_id,
        )
        chunks_before_data = await chunks_before.single()
        assert chunks_before_data["chunk_count"] > 0, "Chunks should exist before deletion"
        
        break  # Exit the async generator

    # Now delete the instance
    delete_response = await client.delete(
        f"/ontology-instances/{instance_id}", headers=headers
    )
    assert delete_response.status_code == 204, "Instance deletion should succeed"

    # Verify that all chunks were deleted
    async for graph_session in get_neo4j_session():
        chunks_after = await graph_session.run(
            """
            MATCH (c:EntityChunk {instance_id: $instance_id})
            RETURN count(c) as chunk_count
            """,
            instance_id=instance_id,
        )
        chunks_after_data = await chunks_after.single()
        assert chunks_after_data["chunk_count"] == 0, "All chunks should be deleted"
        
        # Verify instance and entities are also deleted
        instance_check = await graph_session.run(
            """
            MATCH (i:OntologyInstance {instance_id: $instance_id})
            RETURN count(i) as instance_count
            """,
            instance_id=instance_id,
        )
        instance_data = await instance_check.single()
        assert instance_data["instance_count"] == 0, "Instance should be deleted"
        
        entities_check = await graph_session.run(
            """
            MATCH (e:EntityInstance {instance_id: $instance_id})
            RETURN count(e) as entity_count
            """,
            instance_id=instance_id,
        )
        entities_data = await entities_check.single()
        assert entities_data["entity_count"] == 0, "All entities should be deleted"
        
        break  # Exit the async generator

