"""Tests for the Architect entity generator (step 2)."""

from __future__ import annotations

import pytest

from app.jobs.architect.entity_generator import EntityGenerator
from app.jobs.architect.schemas import PropertyExtractionResponse


class StubLLMForGeneration:
    """Stub LLM client for testing entity generation."""

    def __init__(self, response: str) -> None:
        self._response = response

    async def chat(self, *args, **kwargs) -> str:
        return self._response


class StubPolicyForGeneration:
    """Stub model policy for testing."""

    def get_model(self, task):
        return "fake-model"


@pytest.mark.asyncio
async def test_entity_generator_extracts_properties():
    """Test that the entity generator can extract properties from text."""
    llm_response = """
    {
      "properties": [
        {
          "definition_id": 1,
          "value": "Tall, dark hair"
        }
      ],
      "relationships": [
        {
          "definition_id": 2,
          "target_alias": "Alice",
          "justification": "John is friends with Alice"
        }
      ],
      "autogenerated_summary": "John is a character with dark hair who is friends with Alice."
    }
    """

    generator = EntityGenerator(
        llm_client=StubLLMForGeneration(llm_response),
        model_policy=StubPolicyForGeneration(),
    )

    entity_def_map = {
        5: {
            "id": 5,
            "name": "Character",
            "description": "A person in the story",
            "properties": [
                {
                    "id": 1,
                    "name": "appearance",
                    "description": "Physical description",
                    "data_type": "text",
                    "cardinality": "one",
                }
            ],
            "relationships": [
                {
                    "id": 2,
                    "name": "friend_of",
                    "description": "Is friends with",
                    "destiny_entity_id": 5,
                    "destiny_entity_name": "Character",
                }
            ],
        }
    }

    proposals = [
        {
            "id": "proposal-1",
            "entity_definition_id": 5,
            "alias": "John",
            "chunks": ["John has dark hair and is tall. He is friends with Alice."],
        }
    ]

    entities = await generator.generate_new_entities(
        proposals=proposals,
        entity_definitions_map=entity_def_map,
        original_text="Story about John and Alice",
        author_type="agent",
        author_id="test-agent",
    )

    assert len(entities) == 1
    entity = entities[0]
    assert entity.alias == "John"
    assert entity.definition_id == 5
    assert len(entity.properties) == 1
    assert entity.properties[0].definition_id == 1
    assert entity.properties[0].value == "Tall, dark hair"
    assert "John is a character" in entity.autogenerated_text


@pytest.mark.asyncio
async def test_entity_generator_handles_empty_response():
    """Test that the generator handles empty LLM responses gracefully."""
    llm_response = """
    {
      "properties": [],
      "relationships": [],
      "autogenerated_summary": "A character in the story."
    }
    """

    generator = EntityGenerator(
        llm_client=StubLLMForGeneration(llm_response),
        model_policy=StubPolicyForGeneration(),
    )

    entity_def_map = {
        5: {
            "id": 5,
            "name": "Character",
            "description": "A person",
            "properties": [],
            "relationships": [],
        }
    }

    proposals = [
        {
            "id": "proposal-1",
            "entity_definition_id": 5,
            "alias": "Bob",
            "chunks": ["Bob is mentioned."],
        }
    ]

    entities = await generator.generate_new_entities(
        proposals=proposals,
        entity_definitions_map=entity_def_map,
        original_text="Story text",
        author_type="user",
        author_id="user-123",
    )

    assert len(entities) == 1
    entity = entities[0]
    assert entity.alias == "Bob"
    assert len(entity.properties) == 0
    assert "character in the story" in entity.autogenerated_text


@pytest.mark.asyncio
async def test_entity_generator_uses_corrected_alias():
    """Test that the generator uses corrected_alias when provided."""
    llm_response = """
    {
      "properties": [],
      "relationships": [],
      "autogenerated_summary": "A character."
    }
    """

    generator = EntityGenerator(
        llm_client=StubLLMForGeneration(llm_response),
        model_policy=StubPolicyForGeneration(),
    )

    entity_def_map = {
        5: {
            "id": 5,
            "name": "Character",
            "description": "A person",
            "properties": [],
            "relationships": [],
        }
    }

    proposals = [
        {
            "id": "proposal-1",
            "entity_definition_id": 5,
            "alias": "Jhon",  # Misspelled
            "corrected_alias": "John",  # Corrected by user
            "chunks": ["John is here."],
        }
    ]

    entities = await generator.generate_new_entities(
        proposals=proposals,
        entity_definitions_map=entity_def_map,
        original_text="Story text",
        author_type="user",
        author_id="user-123",
    )

    assert len(entities) == 1
    # Should use corrected alias
    assert entities[0].alias == "John"


def test_format_properties_catalog():
    """Test that the properties catalog is formatted correctly."""
    generator = EntityGenerator(
        llm_client=StubLLMForGeneration("{}"),
        model_policy=StubPolicyForGeneration(),
    )

    properties = [
        {
            "id": 1,
            "name": "age",
            "description": "Age in years",
            "data_type": "number",
            "cardinality": "one",
        },
        {
            "id": 2,
            "name": "titles",
            "description": "Noble titles",
            "data_type": "text",
            "cardinality": "many",
        },
    ]

    catalog = generator._format_properties_catalog(properties)

    assert "ID 1: age (number, one)" in catalog
    assert "Age in years" in catalog
    assert "ID 2: titles (text, many)" in catalog
    assert "Noble titles" in catalog


def test_format_relationships_catalog():
    """Test that the relationships catalog is formatted correctly."""
    generator = EntityGenerator(
        llm_client=StubLLMForGeneration("{}"),
        model_policy=StubPolicyForGeneration(),
    )

    relationships = [
        {
            "id": 1,
            "name": "works_for",
            "description": "Employment relationship",
            "destiny_entity_name": "Organization",
        },
        {
            "id": 2,
            "name": "friend_of",
            "description": "Friendship",
            "destiny_entity_name": "Character",
        },
    ]

    catalog = generator._format_relationships_catalog(relationships)

    assert "ID 1: works_for (to: Organization)" in catalog
    assert "Employment relationship" in catalog
    assert "ID 2: friend_of (to: Character)" in catalog
    assert "Friendship" in catalog
