from __future__ import annotations

from datetime import datetime

import pytest

from app.jobs.architect.architect import ArchitectOrchestrator
from app.jobs.elder.schemas import RetrievedChunk
from app.schemas.ontology_instance import (
    OntologyInstanceEntityRead,
    OntologyInstanceRead,
)
from app.models.ontology import AuthorType


class StubLLM:
    def __init__(self, response: str) -> None:
        self._response = response

    async def chat(self, *args, **kwargs) -> str:  # noqa: D401 - simple stub
        return self._response


class StubRetriever:
    async def search(self, **kwargs):
        return [
            RetrievedChunk(
                node_id="entity-1",
                node_label="Character",
                instance_id="instance-1",
                text="Alice - Prince of the city, cunning and decisive.",
                score=0.87,
                confidence_pct=87.0,
                source="ontology_42",
            )
        ]


class StubPolicy:
    def get_model(self, task):
        return "fake-model"


@pytest.mark.asyncio
async def test_architect_orchestrator_aggregates_results():
    llm_response = """
    {
      "new_instances": [
        {
          "alias": "Court of Nightmares",
          "entity_definition_id": 2,
          "confidence": 0.82,
          "justification": "The story introduces a new court overseeing the city.",
          "metadata": {"supporting_sentences": ["The Court of Nightmares holds sway over Chicago."]}
        }
      ],
      "existing_instances": [
        {
          "entity_instance_id": "entity-1",
          "entity_definition_id": 1,
          "confidence": 0.66,
          "justification": "Alice is referenced again in this passage."
        }
      ]
    }
    """
    orchestrator = ArchitectOrchestrator(
        llm_client=StubLLM(llm_response),
        model_policy=StubPolicy(),
        graph_retriever=StubRetriever(),
        chunk_size=400,
        chunk_overlap=50,
    )

    now = datetime.utcnow()
    entity = OntologyInstanceEntityRead(
        entity_instance_id="entity-1",
        definition_id=1,
        alias="Alice",
        text="Alice rules over the Court of Nightmares in Chicago.",
        text_linked=None,
        node_avatar_url=None,
        autogenerated_text="",
        autogenerated_text_linked=None,
        created_date=now,
        last_updated_date=now,
        author_type=AuthorType.AGENT,
        author_id="agent-1",
        properties=[],
        relationships=[],
    )
    instance = OntologyInstanceRead(
        instance_id="instance-1",
        ontology_id=42,
        name="Test Instance",
        created_at=now,
        updated_at=now,
        entities=[entity],
    )

    entity_definitions = [
        {"id": 1, "name": "Character", "description": "Individuals in the world."},
        {"id": 2, "name": "Organization", "description": "Groups with influence."},
    ]

    result = await orchestrator.analyse(
        agent_ontology_ids=[42],
        ontology_instance=instance,
        entity_definitions=entity_definitions,
    )

    proposals = result["proposals"]
    assert len(proposals) == 2

    new_items = [p for p in proposals if p["entity_instance_id"] is None]
    assert new_items[0]["alias"] == "Court of Nightmares"
    assert new_items[0]["entity_definition_id"] == 2
    assert new_items[0]["confidence"] == pytest.approx(0.82, abs=0.01)
    assert new_items[0]["proposal_metadata"]["supporting_sentences"][0].startswith(
        "The Court"
    )

    existing_items = [p for p in proposals if p["entity_instance_id"] == "entity-1"]
    assert existing_items[0]["entity_definition_id"] == 1
    assert existing_items[0]["confidence"] == pytest.approx(0.66, abs=0.01)
