"""Entity generation orchestrator for Architect step 2."""

from __future__ import annotations

import asyncio
import json
import logging
import re
from pathlib import Path
from typing import Any

from app.integrations.llm.model_policy import LLMTask, ModelPolicy
from app.integrations.llm.shreckllm_client import ShreckLLMClient
from app.jobs.architect.prompts import (
    ARCHITECT_PROPERTY_EXTRACTION_PROMPT,
    ARCHITECT_PROPERTY_UPDATE_PROMPT,
)
from app.jobs.architect.schemas import (
    PropertyExtractionResponse,
    PropertyUpdateResponse,
    StrictPropertyUpdateResponse,
)
from app.models.ontology import AuthorType
from app.schemas.ontology_instance import (
    OntologyInstanceEntityCreate,
    OntologyInstancePropertyValue,
    OntologyInstanceRelationshipCreate,
)

logger = logging.getLogger(__name__)

# Regex pattern to remove markdown code block delimiters (e.g., ```html, ```javascript, ```)
MARKDOWN_CODE_BLOCK_PATTERN = r"```[a-zA-Z]*\s*\n?(.*?)\n?```"


class EntityGenerator:
    """Generates entities and updates with properties/relationships from text."""

    def __init__(
        self,
        llm_client: ShreckLLMClient,
        model_policy: ModelPolicy,
        *,
        concurrent_extractions: int = 4,
    ) -> None:
        self.llm_client = llm_client
        self.model_policy = model_policy
        self.concurrent_extractions = max(1, concurrent_extractions)

    async def generate_new_entities(
        self,
        *,
        proposals: list[dict[str, Any]],
        entity_definitions_map: dict[int, dict[str, Any]],
        original_text: str,
        author_type: str,
        author_id: str,
    ) -> list[tuple[str, OntologyInstanceEntityCreate, list[dict[str, Any]]]]:
        """Generate new entity instances from approved proposals."""
        semaphore = asyncio.Semaphore(self.concurrent_extractions)

        async def process_new_entity(
            proposal: dict[str, Any],
        ) -> tuple[str, OntologyInstanceEntityCreate, list[dict[str, Any]]] | None:
            async with semaphore:
                try:
                    entity, relationships = await self._generate_new_entity(
                        proposal=proposal,
                        entity_definitions_map=entity_definitions_map,
                        original_text=original_text,
                        author_type=author_type,
                        author_id=author_id,
                    )
                    return proposal["id"], entity, relationships
                except Exception as exc:
                    logger.error(
                        "Failed to generate new entity for proposal %s: %s",
                        proposal.get("id"),
                        exc,
                        exc_info=True,
                    )
                    return None

        results = await asyncio.gather(*(process_new_entity(p) for p in proposals))
        return [r for r in results if r is not None]

    async def _generate_new_entity(
        self,
        *,
        proposal: dict[str, Any],
        entity_definitions_map: dict[int, dict[str, Any]],
        original_text: str,
        author_type: str,
        author_id: str,
    ) -> tuple[OntologyInstanceEntityCreate, list[dict[str, Any]]]:
        """Generate a single new entity."""
        entity_def_id = (
            proposal.get("corrected_entity_definition_id")
            or proposal["entity_definition_id"]
        )
        alias = proposal.get("corrected_alias") or proposal["alias"]
        chunks = proposal.get("chunks", [])

        entity_def = entity_definitions_map.get(entity_def_id)
        if not entity_def:
            raise ValueError(f"Entity definition {entity_def_id} not found")

        author_enum = self._normalize_author_type(author_type)

        # Extract auto-generatable properties and relationships
        extracted = await self._extract_properties_and_relationships(
            entity_definition_id=entity_def_id,
            entity_alias=alias,
            entity_type_name=entity_def["name"],
            properties_catalog=entity_def["properties"],
            relationships_catalog=entity_def["relationships"],
            chunks=chunks,
            original_text=original_text,
            is_update=False,
        )

        logger.debug(
            "architect_generation: extracted new entity props=%d rels=%d summary=%s for proposal=%s alias=%s",
            len(extracted.properties),
            len(extracted.relationships),
            bool(extracted.autogenerated_summary),
            proposal.get("id"),
            alias,
        )

        # Build entity create payload
        properties = [
            OntologyInstancePropertyValue(definition_id=p.definition_id, value=p.value)
            for p in extracted.properties
        ]

        relationships = [
            {
                "definition_id": rel.definition_id,
                "target_alias": rel.target_alias,
                "target_entity_instance_id": rel.target_entity_instance_id,
                "justification": rel.justification,
            }
            for rel in extracted.relationships
        ]

        # Note: Relationships will be added in a second pass
        # For now, we just collect them for later processing
        entity_payload = OntologyInstanceEntityCreate(
            definition_id=entity_def_id,
            alias=alias,
            text="",  # No user text for auto-generated entities
            autogenerated_text=extracted.autogenerated_summary or "",
            author_type=author_enum,
            author_id=author_id,
            properties=properties,
            relationships=[],  # Will be populated in second pass
        )
        return entity_payload, relationships

    async def update_existing_entities(
        self,
        *,
        proposals: list[dict[str, Any]],
        entity_definitions_map: dict[int, dict[str, Any]],
        existing_entities_map: dict[str, dict[str, Any]],
        original_text: str,
        author_type: str,
        author_id: str,
    ) -> list[dict[str, Any]]:
        """Update existing entities with new information from proposals."""
        semaphore = asyncio.Semaphore(self.concurrent_extractions)

        async def process_update(proposal: dict[str, Any]) -> dict[str, Any] | None:
            async with semaphore:
                try:
                    return await self._update_existing_entity(
                        proposal=proposal,
                        entity_definitions_map=entity_definitions_map,
                        existing_entities_map=existing_entities_map,
                        original_text=original_text,
                        author_type=author_type,
                        author_id=author_id,
                    )
                except Exception as exc:
                    logger.error(
                        "Failed to update entity for proposal %s: %s",
                        proposal.get("id"),
                        exc,
                        exc_info=True,
                    )
                    return None

        results = await asyncio.gather(*(process_update(p) for p in proposals))
        return [r for r in results if r is not None]

    async def _update_existing_entity(
        self,
        *,
        proposal: dict[str, Any],
        entity_definitions_map: dict[int, dict[str, Any]],
        existing_entities_map: dict[str, dict[str, Any]],
        original_text: str,
        author_type: str,
        author_id: str,
    ) -> dict[str, Any]:
        """Update a single existing entity."""
        entity_instance_id = proposal["entity_instance_id"]
        chunks = proposal.get("chunks", [])

        existing_entity = existing_entities_map.get(entity_instance_id)
        if not existing_entity:
            raise ValueError(f"Entity instance {entity_instance_id} not found")

        entity_def_id = existing_entity["definition_id"]
        entity_def = entity_definitions_map.get(entity_def_id)
        if not entity_def:
            raise ValueError(f"Entity definition {entity_def_id} not found")

        # Extract new properties and relationships
        extracted = await self._extract_properties_and_relationships(
            entity_definition_id=entity_def_id,
            entity_alias=existing_entity.get("alias", ""),
            entity_type_name=entity_def["name"],
            properties_catalog=entity_def["properties"],
            relationships_catalog=entity_def["relationships"],
            chunks=chunks,
            original_text=original_text,
            is_update=True,
            existing_text=existing_entity.get("text", ""),
            existing_autogenerated_text=existing_entity.get("autogenerated_text", ""),
            existing_properties=existing_entity.get("properties", []),
            existing_relationships=existing_entity.get("relationships", []),
        )

        normalized_author = self._normalize_author_type(author_type).value

        logger.debug(
            "architect_generation: extracted update props=%d rels=%d summary=%s for proposal=%s entity=%s",
            len(extracted.new_properties),
            len(extracted.new_relationships),
            bool(extracted.updated_autogenerated_summary),
            proposal.get("id"),
            entity_instance_id,
        )

        return {
            "proposal_id": proposal.get("id"),
            "entity_instance_id": entity_instance_id,
            "new_properties": extracted.new_properties,
            "new_relationships": extracted.new_relationships,
            "updated_autogenerated_summary": extracted.updated_autogenerated_summary,
            "author_type": normalized_author,
            "author_id": author_id,
        }

    @staticmethod
    def _normalize_author_type(author_type: str) -> AuthorType:
        value = (author_type or "").strip().lower()
        if value in {"human", "user"}:
            return AuthorType.HUMAN
        if value in {"agent", "ai", "assistant"}:
            return AuthorType.AGENT
        raise ValueError(f"Unsupported author_type '{author_type}'")

    async def _extract_properties_and_relationships(
        self,
        *,
        entity_definition_id: int,
        entity_alias: str,
        entity_type_name: str,
        properties_catalog: list[dict[str, Any]],
        relationships_catalog: list[dict[str, Any]],
        chunks: list[str],
        related_entities: list[dict[str, Any]] | None = None,
        original_text: str = "",
        is_update: bool,
        existing_text: str = "",
        existing_autogenerated_text: str = "",
        existing_properties: list[dict[str, Any]] | None = None,
        existing_relationships: list[dict[str, Any]] | None = None,
        debug_job_id: int | None = None,
        debug_entity_id: str | None = None,
        debug_anomalies: list[str] | None = None,
        debug_context_package: dict[str, Any] | None = None,
        update_response_mode: str = "legacy",
    ) -> PropertyExtractionResponse | PropertyUpdateResponse | StrictPropertyUpdateResponse:
        """Extract properties and relationships from text chunks using LLM."""
        combined_chunks = "\n\n---\n\n".join(chunks) if chunks else ""

        # Format catalogs
        props_catalog_str = self._format_properties_catalog(properties_catalog)
        rels_catalog_str = self._format_relationships_catalog(relationships_catalog)
        related_entities_str = self._format_related_entities(related_entities or [])
        scenes_context_str = self._format_scenes_context(
            (debug_context_package or {}).get("scenes") or []
        )

        logger.info(
            "architect.generate enrichment_prompt entity=%s property_catalog_count=%d relationship_catalog_count=%d related_entities_count=%d chunk_count=%d",
            entity_alias,
            len(properties_catalog or []),
            len(relationships_catalog or []),
            len(related_entities or []),
            len(chunks or []),
        )
        if not properties_catalog:
            logger.warning(
                "architect.generate enrichment_prompt entity=%s has_empty_property_catalog",
                entity_alias,
            )
        if not relationships_catalog:
            logger.warning(
                "architect.generate enrichment_prompt entity=%s has_empty_relationship_catalog",
                entity_alias,
            )

        # Always pass existing state so extraction and update semantics stay in one step.
        existing_props_str = self._format_existing_properties(
            existing_properties or [], properties_catalog
        )
        existing_rels_str = self._format_existing_relationships(
            existing_relationships or [], relationships_catalog
        )

        prompt = ARCHITECT_PROPERTY_UPDATE_PROMPT.format(
            entity_alias=entity_alias,
            entity_type_name=entity_type_name,
            existing_properties=existing_props_str,
            existing_relationships=existing_rels_str,
            properties_catalog=props_catalog_str,
            relationships_catalog=rels_catalog_str,
            related_entities=related_entities_str,
            scenes_context=scenes_context_str,
            combined_chunks=combined_chunks or "(no text)",
            existing_text=existing_text or "(no text)",
            existing_autogenerated_text=existing_autogenerated_text or "(no summary)",
            entity_definition_id=entity_definition_id,
        )

        model = self.model_policy.get_model(LLMTask.ARCHITECT_EXTRACT)
        debug_payload: dict[str, Any] = {
            "entity_alias": entity_alias,
            "entity_id": debug_entity_id,
            "entity_definition_id": entity_definition_id,
            "entity_type_name": entity_type_name,
            "is_update": is_update,
            "anomalies": debug_anomalies or [],
            "context_package": debug_context_package or {},
            "llm_request": {
                "model": model,
                "temperature": 0.1,
                "messages": [{"role": "user", "content": prompt}],
            },
            "llm_response": {
                "raw_response": None,
            },
            "processing_status": "processing",
        }
        response_text = await self.llm_client.chat(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            usage_tag="architect.generate.enrichment",
        )
        debug_payload["llm_response"]["raw_response"] = response_text

        parsed = self._parse_extraction_response(
            response_text=response_text,
            is_update=is_update,
            update_response_mode=update_response_mode,
        )

        if parsed is None:
            debug_payload["processing_status"] = "failed_parse"
            self._write_enrichment_debug_file(
                debug_job_id=debug_job_id,
                entity_alias=entity_alias,
                entity_id=debug_entity_id,
                payload=debug_payload,
            )
            return (
                (
                    StrictPropertyUpdateResponse()
                    if is_update and update_response_mode == "strict_name_based"
                    else PropertyUpdateResponse()
                )
                if is_update
                else PropertyExtractionResponse()
            )

        # Ensure we always have a usable summary even if the model omits one
        if is_update:
            if not parsed.updated_autogenerated_summary:
                parsed.updated_autogenerated_summary = self._fallback_summary(
                    combined_chunks,
                    existing_autogenerated_text,
                    existing_text,
                )
        else:
            if not parsed.autogenerated_summary:
                parsed.autogenerated_summary = self._fallback_summary(
                    combined_chunks
                )

        debug_payload["processing_status"] = "parsed"
        debug_payload["parsed_payload"] = (
            parsed.model_dump()
            if hasattr(parsed, "model_dump")
            else {}
        )
        self._write_enrichment_debug_file(
            debug_job_id=debug_job_id,
            entity_alias=entity_alias,
            entity_id=debug_entity_id,
            payload=debug_payload,
        )

        return parsed

    @staticmethod
    def _safe_filename(value: str) -> str:
        normalized = re.sub(r"[^A-Za-z0-9._-]+", "_", (value or "").strip())
        return normalized[:120] or "entity"

    def _write_enrichment_debug_file(
        self,
        *,
        debug_job_id: int | None,
        entity_alias: str,
        entity_id: str | None,
        payload: dict[str, Any],
    ) -> None:
        if not debug_job_id:
            return
        # Debug artifact writing is intentionally disabled for architect/generate.
        # Keep the implementation below commented for quick re-enable when needed.
        return

        # try:
        #     stem = self._safe_filename(entity_alias or "entity")
        #     if entity_id:
        #         stem = f"{stem}_{self._safe_filename(entity_id)[:12]}"
        #     target_name = f"{stem}_enrich.json"
        #     write_errors: list[str] = []
        #     wrote_any = False
        #     for base_dir in self._resolve_architect_generate_debug_dirs(debug_job_id=debug_job_id):
        #         try:
        #             base_dir.mkdir(parents=True, exist_ok=True)
        #             target = base_dir / target_name
        #             target.write_text(
        #                 json.dumps(payload, ensure_ascii=False, indent=2),
        #                 encoding="utf-8",
        #             )
        #             wrote_any = True
        #         except Exception as exc:
        #             write_errors.append(f"{base_dir}: {exc}")
        #     if not wrote_any:
        #         raise OSError("; ".join(write_errors) or "no writable debug directory")
        # except Exception:
        #     logger.exception(
        #         "architect.generate failed writing enrich debug file job_id=%s entity=%s",
        #         debug_job_id,
        #         entity_alias or entity_id or "",
        #     )

    @staticmethod
    def _resolve_architect_generate_debug_dirs(*, debug_job_id: int) -> list[Path]:
        import os

        module_root = Path(__file__).resolve().parents[3]
        cwd = Path.cwd()
        data_root = Path(os.getenv("SHRECKNET_DATA_DIR", "")).expanduser() if os.getenv("SHRECKNET_DATA_DIR") else None
        candidates = [
            *( [data_root / "local_test" / "architect" / "generate" / str(debug_job_id)] if data_root else [] ),
            module_root / "databases" / "local_test" / "architect" / "generate" / str(debug_job_id),
            cwd / "shrecknet" / "databases" / "local_test" / "architect" / "generate" / str(debug_job_id),
            cwd / "databases" / "local_test" / "architect" / "generate" / str(debug_job_id),
        ]
        # Deduplicate while preserving order.
        unique: list[Path] = []
        seen: set[str] = set()
        for candidate in candidates:
            key = str(candidate.resolve()) if candidate.exists() else str(candidate)
            if key in seen:
                continue
            seen.add(key)
            unique.append(candidate)
        return unique

    def _parse_extraction_response(
        self, *, response_text: str, is_update: bool, update_response_mode: str
    ) -> PropertyExtractionResponse | PropertyUpdateResponse | StrictPropertyUpdateResponse | None:
        """Parse the LLM response and return the typed payload or None on failure."""
        try:
            json_block = self._extract_json_block(response_text)
            payload = json.loads(json_block)

            # Strip markdown code blocks from text fields in the response
            if "autogenerated_summary" in payload and isinstance(
                payload["autogenerated_summary"], str
            ):
                payload["autogenerated_summary"] = self._strip_markdown_code_blocks(
                    payload["autogenerated_summary"]
                )
            if "updated_autogenerated_summary" in payload and isinstance(
                payload["updated_autogenerated_summary"], str
            ):
                payload["updated_autogenerated_summary"] = (
                    self._strip_markdown_code_blocks(
                        payload["updated_autogenerated_summary"]
                    )
                )

            # Strip markdown from relationship justifications (legacy mode only).
            for rel in payload.get("relationships", []) or payload.get("new_relationships", []):
                if isinstance(rel.get("justification"), str):
                    rel["justification"] = self._strip_markdown_code_blocks(
                        rel["justification"]
                    )

            # Strip markdown from property values if they're text.
            for prop in payload.get("properties", []) or payload.get(
                "new_properties", []
            ):
                if isinstance(prop.get("value"), str):
                    prop["value"] = self._strip_markdown_code_blocks(prop["value"])
            for prop in payload.get("properties_update", []):
                if isinstance(prop.get("property_value"), str):
                    prop["property_value"] = self._strip_markdown_code_blocks(
                        prop["property_value"]
                    )

            def _coerce_int(value: Any) -> int | None:
                if isinstance(value, bool):
                    return None
                if isinstance(value, int):
                    return value
                if isinstance(value, str) and value.strip().isdigit():
                    return int(value.strip())
                return None

            def _sanitize_items(items: Any) -> list[dict[str, Any]]:
                if not isinstance(items, list):
                    return []
                return [item for item in items if isinstance(item, dict)]

            # Be tolerant to partial LLM drift: drop malformed items instead of
            # failing the whole payload (which would also lose summary updates).
            for key in ("properties", "new_properties"):
                sanitized: list[dict[str, Any]] = []
                for item in _sanitize_items(payload.get(key)):
                    definition_id = _coerce_int(item.get("definition_id"))
                    if definition_id is None:
                        continue
                    sanitized.append({**item, "definition_id": definition_id})
                if key in payload:
                    payload[key] = sanitized

            for key in ("relationships", "new_relationships"):
                sanitized = []
                for item in _sanitize_items(payload.get(key)):
                    definition_id = _coerce_int(item.get("definition_id"))
                    if definition_id is None:
                        continue
                    sanitized.append({**item, "definition_id": definition_id})
                if key in payload:
                    payload[key] = sanitized

            if is_update:
                if update_response_mode == "strict_name_based":
                    allowed_keys = {
                        "properties_update",
                        "relationships_update",
                        "updated_autogenerated_summary",
                    }
                    if any(key not in allowed_keys for key in payload.keys()):
                        raise ValueError("Unexpected keys in strict update payload")
                    return StrictPropertyUpdateResponse.model_validate(payload)
                return PropertyUpdateResponse.model_validate(payload)
            if "properties" not in payload and "new_properties" in payload:
                payload["properties"] = payload.get("new_properties", [])
            if "relationships" not in payload and "new_relationships" in payload:
                payload["relationships"] = payload.get("new_relationships", [])
            if (
                "autogenerated_summary" not in payload
                and "updated_autogenerated_summary" in payload
            ):
                payload["autogenerated_summary"] = payload.get(
                    "updated_autogenerated_summary"
                )
            return PropertyExtractionResponse.model_validate(payload)
        except Exception as exc:
            logger.warning(
                "Failed to parse property extraction response: %s\nResponse: %s",
                exc,
                response_text,
            )
            return None

    @staticmethod
    def _strip_markdown_code_blocks(text: str | None) -> str:
        """
        Remove markdown code block delimiters from text.

        This is needed because LLMs sometimes wrap HTML/text content in markdown code blocks,
        which makes them unparsable on the frontend.

        Handles code blocks with any language identifier (e.g., ```html, ```javascript, ```css)
        or no identifier (e.g., ```).

        Args:
            text: The text to clean, may be None

        Returns:
            Clean text without markdown code block delimiters
        """
        if not text:
            return ""
        # Remove markdown code blocks with any optional language identifier
        # Use DOTALL flag to match across newlines
        cleaned = re.sub(
            MARKDOWN_CODE_BLOCK_PATTERN,
            r"\1",
            text,
            flags=re.DOTALL | re.IGNORECASE,
        )
        return cleaned.strip()

    @staticmethod
    def _fallback_summary(*texts: str | None, limit: int = 500) -> str:
        """Build a lightweight fallback summary from provided text snippets."""
        chosen = next((t for t in texts if t), "")
        collapsed = " ".join(chosen.split())
        if len(collapsed) > limit:
            return collapsed[: limit - 1] + "…"
        return collapsed

    @staticmethod
    def _extract_json_block(raw: str) -> str:
        """Extract JSON object from LLM response."""
        start = raw.find("{")
        end = raw.rfind("}")
        if start == -1 or end == -1 or end <= start:
            raise ValueError("No JSON object found in LLM response")
        return raw[start : end + 1]

    @staticmethod
    def _format_properties_catalog(properties: list[dict[str, Any]]) -> str:
        """Format properties catalog for prompt."""
        if not properties:
            return "(no auto-generatable properties)"
        lines = []
        for prop in properties:
            desc = (prop.get("description") or "").strip()
            lines.append(
                f"- ID {prop['id']}: {prop['name']} ({prop['data_type']}, {prop['cardinality']}) - {desc or 'No description'}"
            )
        return "\n".join(lines)

    @staticmethod
    def _format_relationships_catalog(relationships: list[dict[str, Any]]) -> str:
        """Format relationships catalog for prompt."""
        if not relationships:
            return "(no auto-generatable relationships)"
        lines = []
        for rel in relationships:
            desc = (rel.get("description") or "").strip()
            target = rel.get("destiny_entity_name", "any entity")
            lines.append(
                f"- ID {rel['id']}: {rel['name']} (related to entity type: {target}) - {desc or 'No description'}"
            )
        return "\n".join(lines)

    @staticmethod
    def _format_existing_properties(
        existing: list[dict[str, Any]], catalog: list[dict[str, Any]]
    ) -> str:
        """Format existing properties for prompt."""
        if not existing:
            return "(none)"
        catalog_map = {p["id"]: p["name"] for p in catalog}
        lines = []
        for prop in existing:
            prop_name = catalog_map.get(
                prop["definition_id"], f"Property {prop['definition_id']}"
            )
            lines.append(f"- {prop_name}: {prop['value']}")
        return "\n".join(lines) if lines else "(none)"

    @staticmethod
    def _format_existing_relationships(
        existing: list[dict[str, Any]], catalog: list[dict[str, Any]]
    ) -> str:
        """Format existing relationships for prompt."""
        if not existing:
            return "(none)"
        catalog_map = {r["id"]: r["name"] for r in catalog}
        lines = []
        for rel in existing:
            rel_name = catalog_map.get(
                rel["definition_id"], f"Relationship {rel['definition_id']}"
            )
            target = rel.get("target_alias") or rel.get(
                "target_entity_instance_id", "unknown"
            )
            lines.append(f"- {rel_name} -> {target}")
        return "\n".join(lines) if lines else "(none)"

    @staticmethod
    def _format_related_entities(related_entities: list[dict[str, Any]]) -> str:
        """Format allowed relationship targets for prompt grounding."""
        if not related_entities:
            return "[]"
        lines: list[str] = []
        for item in related_entities:
            entity_id = str(item.get("entity_instance_id") or "").strip() or "unknown-id"
            alias = str(item.get("name") or item.get("alias") or "").strip() or "(no alias)"
            entity_type = str(item.get("entity_type_name") or "").strip() or "(unknown type)"
            lines.append(f"- {{name: \"{alias}\", id: \"{entity_id}\", type: \"{entity_type}\"}}")
        return "\n".join(lines)

    @staticmethod
    def _format_scenes_context(scenes: list[dict[str, Any]]) -> str:
        if not scenes:
            return "(none)"
        lines: list[str] = []
        for idx, scene in enumerate(scenes, start=1):
            title = str(scene.get("title") or "Scene").strip()
            description = str(scene.get("description") or "").strip()
            related_items = scene.get("related_entities") or []
            related_parts: list[str] = []
            for item in related_items:
                if isinstance(item, dict):
                    related_parts.append(
                        "{name: \""
                        + str(item.get("name") or "")
                        + "\", id: \""
                        + str(item.get("id") or "")
                        + "\", type: \""
                        + str(item.get("type") or "")
                        + "\"}"
                    )
                else:
                    related_parts.append(str(item))
            related = ", ".join(related_parts)
            lines.append(f"Scene {idx} - Title: {title}")
            lines.append(f"Description: {description or '(no description)'}")
            lines.append(f"Related entities: {related or '(none)'}")
        return "\n".join(lines)

    async def add_relationships_to_entities(
        self,
        *,
        entities: list[OntologyInstanceEntityCreate],
        relationship_data: dict[str, list[dict[str, Any]]],
        entity_alias_map: dict[str, str],
    ) -> list[OntologyInstanceEntityCreate]:
        """Add relationships to entities in a second pass after all entities are created."""
        for entity in entities:
            alias_key = entity.alias.lower().strip()
            if alias_key not in relationship_data:
                continue

            relationships = []
            for rel_data in relationship_data[alias_key]:
                target_alias = rel_data.get("target_alias")
                if not target_alias:
                    continue

                # Check if target exists in new entities or should reference existing
                target_key = target_alias.lower().strip()
                if target_key in entity_alias_map or target_alias:
                    # Target exists, add relationship
                    relationships.append(
                        OntologyInstanceRelationshipCreate(
                            definition_id=rel_data["definition_id"],
                            target_alias=target_alias,
                            data={"justification": rel_data.get("justification", "")},
                        )
                    )

            entity.relationships = relationships

        return entities
