from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass
from html import unescape
from html.parser import HTMLParser
from typing import Any

from app.integrations.llm.shreckllm_client import ShreckLLMClient
from app.jobs.architect import prompts as architect_prompts


logger = logging.getLogger(__name__)


PARAGRAPH_MARKER_PATTERN = re.compile(r"^\[P(\d+)\]\s*(.*)$")
_BULLET_OR_NUMBERED_START = re.compile(r"^\s*(?:[●•\-\*]\s+|\d+[.)]\s+)")
_TIMESTAMP_MARKER = re.compile(r"\(\d{1,2}:\d{2}:\d{2}\)")


@dataclass
class SceneChunk:
    chunk_index: int
    paragraph_start: int
    paragraph_end: int
    paragraph_count: int
    token_count: int
    paragraphs: list[str]
    marked_paragraphs: str


class _NarrativeHTMLParagraphParser(HTMLParser):
    """Extract paragraph-like units and preserve heading -> paragraph grouping."""

    _PARAGRAPH_TAGS = {"p", "li", "blockquote"}
    _HEADING_TAGS = {"h1", "h2", "h3", "h4", "h5", "h6", "title"}

    def __init__(self) -> None:
        super().__init__()
        self._tag_stack: list[str] = []
        self._paragraph_buffer: list[str] = []
        self._pending_non_paragraph: list[str] = []
        self._paragraphs: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        del attrs
        self._tag_stack.append(tag.lower())

    def handle_endtag(self, tag: str) -> None:
        normalized = tag.lower()
        if self._tag_stack:
            for idx in range(len(self._tag_stack) - 1, -1, -1):
                if self._tag_stack[idx] == normalized:
                    del self._tag_stack[idx]
                    break

        if normalized in self._PARAGRAPH_TAGS:
            self._flush_paragraph()
            return

        if normalized in self._HEADING_TAGS:
            self._flush_heading_to_pending()

    def handle_data(self, data: str) -> None:
        cleaned = " ".join(unescape(data).split())
        if not cleaned:
            return

        current_tag = self._tag_stack[-1] if self._tag_stack else ""
        if current_tag in self._PARAGRAPH_TAGS:
            self._paragraph_buffer.append(cleaned)
            return

        if current_tag in self._HEADING_TAGS:
            self._pending_non_paragraph.append(cleaned)
            return

        self._pending_non_paragraph.append(cleaned)

    def close(self) -> None:
        super().close()
        self._flush_paragraph()
        if self._pending_non_paragraph:
            self._paragraphs.append(" ".join(self._pending_non_paragraph))
            self._pending_non_paragraph = []

    @property
    def paragraphs(self) -> list[str]:
        return [p for p in self._paragraphs if p]

    def _flush_heading_to_pending(self) -> None:
        if self._paragraph_buffer:
            self._pending_non_paragraph.append(" ".join(self._paragraph_buffer))
            self._paragraph_buffer = []

    def _flush_paragraph(self) -> None:
        if not self._paragraph_buffer:
            return

        paragraph_text = " ".join(self._paragraph_buffer)
        self._paragraph_buffer = []

        if self._pending_non_paragraph:
            paragraph_text = " ".join(self._pending_non_paragraph + [paragraph_text])
            self._pending_non_paragraph = []

        self._paragraphs.append(paragraph_text)


def _looks_like_html(value: str) -> bool:
    return bool(re.search(r"<[^>]+>", value))


def _extract_non_html_paragraphs(text: str) -> list[str]:
    parts = re.split(r"\n\s*\n+", text)
    normalized_parts = [
        " ".join(unescape(part).split()) for part in parts if part and part.strip()
    ]
    if len(normalized_parts) > 1:
        return normalized_parts

    # Fallback for transcript-like inputs that use single newlines with list markers
    # rather than blank lines between semantic blocks.
    lines = [line.strip() for line in text.splitlines() if line and line.strip()]
    if not lines:
        return []

    blocks: list[list[str]] = []
    current: list[str] = []
    for line in lines:
        starts_block = bool(_BULLET_OR_NUMBERED_START.match(line)) or bool(
            _TIMESTAMP_MARKER.search(line)
        )
        if starts_block and current:
            blocks.append(current)
            current = [line]
            continue
        current.append(line)

    if current:
        blocks.append(current)

    if len(blocks) <= 1:
        return normalized_parts

    return [" ".join(unescape(" ".join(block)).split()) for block in blocks if block]


def extract_paragraphs_from_sources(
    text: str | None,
    autogenerated_text: str | None,
) -> list[str]:
    paragraphs: list[str] = []

    for source in (text, autogenerated_text):
        if not source:
            continue

        if _looks_like_html(source):
            parser = _NarrativeHTMLParagraphParser()
            parser.feed(source)
            parser.close()
            paragraphs.extend(parser.paragraphs)
        else:
            paragraphs.extend(_extract_non_html_paragraphs(source))

    return [p for p in paragraphs if p]


def build_scene_chunks(
    paragraphs: list[str],
    *,
    token_limit: int,
    encoding_name: str = "cl100k_base",
) -> list[SceneChunk]:
    if not paragraphs:
        return []

    try:
        import tiktoken  # type: ignore
    except ImportError as exc:  # pragma: no cover - dependency/runtime guard
        raise RuntimeError(
            "tiktoken is required for scene-centric chunking. Install project dependencies."
        ) from exc

    encoder = tiktoken.get_encoding(encoding_name)

    chunks: list[SceneChunk] = []
    chunk_index = 0
    index = 0
    paragraph_total = len(paragraphs)

    while index < paragraph_total:
        current: list[str] = []
        current_tokens = 0
        start_idx = index

        while index < paragraph_total:
            marker = f"[P{len(current) + 1}] {paragraphs[index]}"
            marker_tokens = len(encoder.encode(marker))
            if current and current_tokens + marker_tokens > token_limit:
                break
            if not current and marker_tokens > token_limit:
                # Keep forward progress even for oversized paragraphs.
                current.append(paragraphs[index])
                current_tokens = marker_tokens
                index += 1
                break

            current.append(paragraphs[index])
            current_tokens += marker_tokens
            index += 1

        marked = "\n".join(
            f"[P{position}] {paragraph}" for position, paragraph in enumerate(current, start=1)
        )
        chunks.append(
            SceneChunk(
                chunk_index=chunk_index,
                paragraph_start=start_idx + 1,
                paragraph_end=start_idx + len(current),
                paragraph_count=len(current),
                token_count=current_tokens,
                paragraphs=current,
                marked_paragraphs=marked,
            )
        )
        chunk_index += 1

    return chunks


def _extract_json_object(raw: str) -> str:
    start = raw.find("{")
    end = raw.rfind("}")
    if start == -1 or end == -1 or end <= start:
        raise ValueError("No JSON object found in model response")
    return raw[start : end + 1]


def _normalize_scene_ranges(
    scenes: list[dict[str, Any]],
    paragraph_count: int,
    *,
    strict: bool = True,
) -> list[dict[str, Any]]:
    if not scenes:
        raise ValueError("Model returned no scenes")

    # Accept model output as either zero-based or one-based indices.
    starts = [int(scene.get("start_paragraph", -1)) for scene in scenes]
    ends = [int(scene.get("end_paragraph", -1)) for scene in scenes]
    zero_based = any(value == 0 for value in starts + ends)

    normalized: list[dict[str, Any]] = []
    for scene in scenes:
        start = int(scene.get("start_paragraph", -1))
        end = int(scene.get("end_paragraph", -1))
        if zero_based:
            start += 1
            end += 1
        if strict and (start < 1 or end < 1 or start > end or end > paragraph_count):
            raise ValueError(
                f"Invalid scene range start={start} end={end} for paragraph_count={paragraph_count}"
            )

        # In tolerant mode we clamp and repair invalid model output.
        if not strict:
            start = max(1, min(start, paragraph_count))
            end = max(1, min(end, paragraph_count))
            if end < start:
                end = start

        normalized.append(
            {
                "scene_id": int(scene.get("scene_id", len(normalized))),
                "name": str(scene.get("name", "")).strip(),
                "description": str(scene.get("description", "")).strip(),
                "start_paragraph": start,
                "end_paragraph": end,
            }
        )

    normalized.sort(key=lambda item: (item["start_paragraph"], item["end_paragraph"]))

    if not strict:
        repaired: list[dict[str, Any]] = []
        expected = 1
        total = len(normalized)

        for idx, item in enumerate(normalized):
            if expected > paragraph_count:
                break

            start = expected
            raw_end = item["end_paragraph"]
            end = max(start, min(raw_end, paragraph_count))

            # Keep at least one paragraph available for remaining scenes.
            remaining = total - idx - 1
            max_end_for_item = max(start, paragraph_count - remaining)
            if end > max_end_for_item:
                end = max_end_for_item

            repaired.append(
                {
                    **item,
                    "start_paragraph": start,
                    "end_paragraph": end,
                }
            )
            expected = end + 1

        if not repaired:
            repaired = [
                {
                    "scene_id": 0,
                    "name": "Scene 0",
                    "description": "",
                    "start_paragraph": 1,
                    "end_paragraph": paragraph_count,
                }
            ]
        elif repaired[-1]["end_paragraph"] < paragraph_count:
            repaired[-1]["end_paragraph"] = paragraph_count

        if repaired != normalized:
            logger.warning(
                "scene_range_repair_applied: scene_count=%d paragraph_count=%d",
                len(normalized),
                paragraph_count,
            )
        return repaired

    expected = 1
    for item in normalized:
        if item["start_paragraph"] != expected:
            raise ValueError(
                f"Scene coverage gap/overlap near paragraph {expected}; got start={item['start_paragraph']}"
            )
        expected = item["end_paragraph"] + 1

    if expected != paragraph_count + 1:
        raise ValueError(
            f"Scene coverage incomplete, expected paragraph {paragraph_count}, got up to {expected - 1}"
        )

    return normalized


def attach_scene_text(
    scenes: list[dict[str, Any]],
    paragraphs: list[str],
) -> list[dict[str, Any]]:
    enriched: list[dict[str, Any]] = []
    for scene in scenes:
        start = scene["start_paragraph"]
        end = scene["end_paragraph"]
        marked_lines = [
            f"[P{idx}] {paragraphs[idx - 1]}" for idx in range(start, end + 1)
        ]
        enriched.append({**scene, "text": "\n".join(marked_lines)})
    return enriched


def _serialize_scenes_for_unifier(scenes: list[dict[str, Any]]) -> str:
    payload = [
        {
            "scene_id": int(scene.get("scene_id", idx)),
            "name": str(scene.get("name", "")).strip(),
            "description": str(scene.get("description", "")).strip(),
            "start_paragraph": int(scene.get("start_paragraph", -1)),
            "end_paragraph": int(scene.get("end_paragraph", -1)),
        }
        for idx, scene in enumerate(scenes)
    ]
    return json.dumps(payload, ensure_ascii=False, indent=2)


async def _run_scene_unifier(
    *,
    llm_client: ShreckLLMClient,
    model: str,
    scenes: list[dict[str, Any]],
    paragraph_count: int,
    instructions: str | None = None,
) -> list[dict[str, Any]]:
    prompt = architect_prompts.ARCHITECT_SCENE_UNIFIER_PROMPT.format(
        scene_list=_serialize_scenes_for_unifier(scenes)
    )
    instructions_text = str(instructions or "").strip()
    if instructions_text:
        prompt = (
            f"{prompt}\n\nFrontend instructions (authoritative constraints):\n"
            f"{instructions_text}"
        )
    response_text = await llm_client.chat(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
        usage_tag="architect.scene_unifier",
    )

    payload = json.loads(_extract_json_object(response_text))
    unified_scenes = payload.get("scenes") or []
    if not isinstance(unified_scenes, list):
        raise ValueError("Invalid scene unifier payload: 'scenes' must be a list")

    # Strict mode guarantees no coverage loss after refinement.
    return _normalize_scene_ranges(unified_scenes, paragraph_count, strict=True)


async def segment_chunk_into_scenes(
    *,
    llm_client: ShreckLLMClient,
    model: str,
    marked_paragraphs: str,
    paragraph_count: int,
    paragraphs: list[str],
    instructions: str | None = None,
) -> list[dict[str, Any]]:
    prompt = architect_prompts.ARCHITECT_SCENE_CENTRIC_CHUNKING_PROMPT.format(
        marked_paragraphs=marked_paragraphs
    )
    instructions_text = str(instructions or "").strip()
    if instructions_text:
        prompt = (
            f"{prompt}\n\nFrontend instructions (authoritative constraints):\n"
            f"{instructions_text}"
        )
    response_text = await llm_client.chat(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
        usage_tag="architect.scene_discovery",
    )

    payload = json.loads(_extract_json_object(response_text))
    scenes = payload.get("scenes") or []
    if not isinstance(scenes, list):
        raise ValueError("Invalid scene segmentation payload: 'scenes' must be a list")

    normalized = _normalize_scene_ranges(scenes, paragraph_count, strict=False)
    unified = normalized
    unifier_status = "applied"
    try:
        unified = await _run_scene_unifier(
            llm_client=llm_client,
            model=model,
            scenes=normalized,
            paragraph_count=paragraph_count,
            instructions=instructions,
        )
    except Exception as exc:
        unifier_status = "fallback_original"
        logger.warning("scene_unifier_failed_using_original: error=%s", exc)

    logger.info(
        (
            "scene_unifier_result: status=%s initial_scene_count=%d "
            "kept_scene_count=%d merged_scene_count=%d"
        ),
        unifier_status,
        len(normalized),
        len(unified),
        max(0, len(normalized) - len(unified)),
    )

    return attach_scene_text(unified, paragraphs)
