"""Entity generation orchestrator for Architect step 2."""

from __future__ import annotations

import asyncio
import json
import logging
from typing import Any

from app.integrations.llm.model_policy import LLMTask, ModelPolicy
from app.integrations.llm.openai_client import OpenAIClient
from app.jobs.architect.prompts import (
    ARCHITECT_PROPERTY_EXTRACTION_PROMPT,
    ARCHITECT_PROPERTY_UPDATE_PROMPT,
)
from app.jobs.architect.schemas import (
    PropertyExtractionResponse,
    PropertyUpdateResponse,
)
from app.models.ontology import AuthorType
from app.schemas.ontology_instance import (
    OntologyInstanceEntityCreate,
    OntologyInstancePropertyValue,
    OntologyInstanceRelationshipCreate,
)

logger = logging.getLogger(__name__)


class EntityGenerator:
    """Generates entities and updates with properties/relationships from text."""

    def __init__(
        self,
        llm_client: OpenAIClient,
        model_policy: ModelPolicy,
        *,
        concurrent_extractions: int = 4,
    ) -> None:
        self.llm_client = llm_client
        self.model_policy = model_policy
        self.concurrent_extractions = max(1, concurrent_extractions)

    async def generate_new_entities(
        self,
        *,
        proposals: list[dict[str, Any]],
        entity_definitions_map: dict[int, dict[str, Any]],
        original_text: str,
        author_type: str,
        author_id: str,
    ) -> list[OntologyInstanceEntityCreate]:
        """Generate new entity instances from approved proposals."""
        semaphore = asyncio.Semaphore(self.concurrent_extractions)

        async def process_new_entity(proposal: dict[str, Any]) -> OntologyInstanceEntityCreate | None:
            async with semaphore:
                try:
                    return await self._generate_new_entity(
                        proposal=proposal,
                        entity_definitions_map=entity_definitions_map,
                        original_text=original_text,
                        author_type=author_type,
                        author_id=author_id,
                    )
                except Exception as exc:
                    logger.error(
                        "Failed to generate new entity for proposal %s: %s",
                        proposal.get("id"),
                        exc,
                        exc_info=True,
                    )
                    return None

        results = await asyncio.gather(*(process_new_entity(p) for p in proposals))
        return [r for r in results if r is not None]

    async def _generate_new_entity(
        self,
        *,
        proposal: dict[str, Any],
        entity_definitions_map: dict[int, dict[str, Any]],
        original_text: str,
        author_type: str,
        author_id: str,
    ) -> OntologyInstanceEntityCreate:
        """Generate a single new entity."""
        entity_def_id = proposal.get("corrected_entity_definition_id") or proposal["entity_definition_id"]
        alias = proposal.get("corrected_alias") or proposal["alias"]
        chunks = proposal.get("chunks", [])

        entity_def = entity_definitions_map.get(entity_def_id)
        if not entity_def:
            raise ValueError(f"Entity definition {entity_def_id} not found")

        # Extract auto-generatable properties and relationships
        extracted = await self._extract_properties_and_relationships(
            entity_definition_id=entity_def_id,
            entity_alias=alias,
            entity_type_name=entity_def["name"],
            properties_catalog=entity_def["properties"],
            relationships_catalog=entity_def["relationships"],
            chunks=chunks,
            original_text=original_text,
            is_update=False,
        )

        # Build entity create payload
        properties = [
            OntologyInstancePropertyValue(definition_id=p.definition_id, value=p.value)
            for p in extracted.properties
        ]

        # Note: Relationships will be added in a second pass
        # For now, we just collect them for later processing
        return OntologyInstanceEntityCreate(
            definition_id=entity_def_id,
            alias=alias,
            text="",  # No user text for auto-generated entities
            autogenerated_text=extracted.autogenerated_summary or "",
            author_type=AuthorType(author_type),
            author_id=author_id,
            properties=properties,
            relationships=[],  # Will be populated in second pass
        )

    async def update_existing_entities(
        self,
        *,
        proposals: list[dict[str, Any]],
        entity_definitions_map: dict[int, dict[str, Any]],
        existing_entities_map: dict[str, dict[str, Any]],
        original_text: str,
        author_type: str,
        author_id: str,
    ) -> list[dict[str, Any]]:
        """Update existing entities with new information from proposals."""
        semaphore = asyncio.Semaphore(self.concurrent_extractions)

        async def process_update(proposal: dict[str, Any]) -> dict[str, Any] | None:
            async with semaphore:
                try:
                    return await self._update_existing_entity(
                        proposal=proposal,
                        entity_definitions_map=entity_definitions_map,
                        existing_entities_map=existing_entities_map,
                        original_text=original_text,
                        author_type=author_type,
                        author_id=author_id,
                    )
                except Exception as exc:
                    logger.error(
                        "Failed to update entity for proposal %s: %s",
                        proposal.get("id"),
                        exc,
                        exc_info=True,
                    )
                    return None

        results = await asyncio.gather(*(process_update(p) for p in proposals))
        return [r for r in results if r is not None]

    async def _update_existing_entity(
        self,
        *,
        proposal: dict[str, Any],
        entity_definitions_map: dict[int, dict[str, Any]],
        existing_entities_map: dict[str, dict[str, Any]],
        original_text: str,
        author_type: str,
        author_id: str,
    ) -> dict[str, Any]:
        """Update a single existing entity."""
        entity_instance_id = proposal["entity_instance_id"]
        chunks = proposal.get("chunks", [])

        existing_entity = existing_entities_map.get(entity_instance_id)
        if not existing_entity:
            raise ValueError(f"Entity instance {entity_instance_id} not found")

        entity_def_id = existing_entity["definition_id"]
        entity_def = entity_definitions_map.get(entity_def_id)
        if not entity_def:
            raise ValueError(f"Entity definition {entity_def_id} not found")

        # Extract new properties and relationships
        extracted = await self._extract_properties_and_relationships(
            entity_definition_id=entity_def_id,
            entity_alias=existing_entity.get("alias", ""),
            entity_type_name=entity_def["name"],
            properties_catalog=entity_def["properties"],
            relationships_catalog=entity_def["relationships"],
            chunks=chunks,
            original_text=original_text,
            is_update=True,
            existing_text=existing_entity.get("text", ""),
            existing_autogenerated_text=existing_entity.get("autogenerated_text", ""),
            existing_properties=existing_entity.get("properties", []),
            existing_relationships=existing_entity.get("relationships", []),
        )

        return {
            "entity_instance_id": entity_instance_id,
            "new_properties": extracted.new_properties,
            "new_relationships": extracted.new_relationships,
            "updated_autogenerated_summary": extracted.updated_autogenerated_summary,
            "author_type": author_type,
            "author_id": author_id,
        }

    async def _extract_properties_and_relationships(
        self,
        *,
        entity_definition_id: int,
        entity_alias: str,
        entity_type_name: str,
        properties_catalog: list[dict[str, Any]],
        relationships_catalog: list[dict[str, Any]],
        chunks: list[str],
        original_text: str,
        is_update: bool,
        existing_text: str = "",
        existing_autogenerated_text: str = "",
        existing_properties: list[dict[str, Any]] | None = None,
        existing_relationships: list[dict[str, Any]] | None = None,
    ) -> PropertyExtractionResponse | PropertyUpdateResponse:
        """Extract properties and relationships from text chunks using LLM."""
        combined_chunks = "\n\n---\n\n".join(chunks) if chunks else ""

        # Format catalogs
        props_catalog_str = self._format_properties_catalog(properties_catalog)
        rels_catalog_str = self._format_relationships_catalog(relationships_catalog)

        if is_update:
            # Format existing data
            existing_props_str = self._format_existing_properties(
                existing_properties or [], properties_catalog
            )
            existing_rels_str = self._format_existing_relationships(
                existing_relationships or [], relationships_catalog
            )

            prompt = ARCHITECT_PROPERTY_UPDATE_PROMPT.format(
                entity_instance_id=entity_alias,  # Using alias as display identifier
                entity_alias=entity_alias,
                entity_type_name=entity_type_name,
                existing_text=existing_text or "(no text)",
                existing_autogenerated_text=existing_autogenerated_text or "(no summary)",
                existing_properties=existing_props_str,
                existing_relationships=existing_rels_str,
                properties_catalog=props_catalog_str,
                relationships_catalog=rels_catalog_str,
                combined_chunks=combined_chunks or "(no new text)",
                original_text=original_text[:2000] if original_text else "(no context)",
            )
        else:
            prompt = ARCHITECT_PROPERTY_EXTRACTION_PROMPT.format(
                entity_definition_id=entity_definition_id,
                entity_alias=entity_alias,
                entity_type_name=entity_type_name,
                properties_catalog=props_catalog_str,
                relationships_catalog=rels_catalog_str,
                combined_chunks=combined_chunks or "(no text)",
                original_text=original_text[:2000] if original_text else "(no context)",
            )

        model = self.model_policy.get_model(LLMTask.ARCHITECT_EXTRACT)
        response_text = await self.llm_client.chat(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
        )

        # Parse response
        try:
            json_block = self._extract_json_block(response_text)
            payload = json.loads(json_block)
            if is_update:
                return PropertyUpdateResponse.model_validate(payload)
            else:
                return PropertyExtractionResponse.model_validate(payload)
        except Exception as exc:
            logger.warning(
                "Failed to parse property extraction response: %s\nResponse: %s",
                exc,
                response_text,
            )
            if is_update:
                return PropertyUpdateResponse()
            else:
                return PropertyExtractionResponse()

    @staticmethod
    def _extract_json_block(raw: str) -> str:
        """Extract JSON object from LLM response."""
        start = raw.find("{")
        end = raw.rfind("}")
        if start == -1 or end == -1 or end <= start:
            raise ValueError("No JSON object found in LLM response")
        return raw[start : end + 1]

    @staticmethod
    def _format_properties_catalog(properties: list[dict[str, Any]]) -> str:
        """Format properties catalog for prompt."""
        if not properties:
            return "(no auto-generatable properties)"
        lines = []
        for prop in properties:
            desc = (prop.get("description") or "").strip()
            lines.append(
                f"- ID {prop['id']}: {prop['name']} ({prop['data_type']}, {prop['cardinality']}) - {desc or 'No description'}"
            )
        return "\n".join(lines)

    @staticmethod
    def _format_relationships_catalog(relationships: list[dict[str, Any]]) -> str:
        """Format relationships catalog for prompt."""
        if not relationships:
            return "(no auto-generatable relationships)"
        lines = []
        for rel in relationships:
            desc = (rel.get("description") or "").strip()
            target = rel.get("destiny_entity_name", "any entity")
            lines.append(
                f"- ID {rel['id']}: {rel['name']} (to: {target}) - {desc or 'No description'}"
            )
        return "\n".join(lines)

    @staticmethod
    def _format_existing_properties(
        existing: list[dict[str, Any]], catalog: list[dict[str, Any]]
    ) -> str:
        """Format existing properties for prompt."""
        if not existing:
            return "(none)"
        catalog_map = {p["id"]: p["name"] for p in catalog}
        lines = []
        for prop in existing:
            prop_name = catalog_map.get(prop["definition_id"], f"Property {prop['definition_id']}")
            lines.append(f"- {prop_name}: {prop['value']}")
        return "\n".join(lines) if lines else "(none)"

    @staticmethod
    def _format_existing_relationships(
        existing: list[dict[str, Any]], catalog: list[dict[str, Any]]
    ) -> str:
        """Format existing relationships for prompt."""
        if not existing:
            return "(none)"
        catalog_map = {r["id"]: r["name"] for r in catalog}
        lines = []
        for rel in existing:
            rel_name = catalog_map.get(rel["definition_id"], f"Relationship {rel['definition_id']}")
            target = rel.get("target_alias") or rel.get("target_entity_instance_id", "unknown")
            lines.append(f"- {rel_name} -> {target}")
        return "\n".join(lines) if lines else "(none)"

    async def add_relationships_to_entities(
        self,
        *,
        entities: list[OntologyInstanceEntityCreate],
        relationship_data: dict[str, list[dict[str, Any]]],
        entity_alias_map: dict[str, str],
    ) -> list[OntologyInstanceEntityCreate]:
        """Add relationships to entities in a second pass after all entities are created."""
        for entity in entities:
            alias_key = entity.alias.lower().strip()
            if alias_key not in relationship_data:
                continue

            relationships = []
            for rel_data in relationship_data[alias_key]:
                target_alias = rel_data.get("target_alias")
                if not target_alias:
                    continue

                # Check if target exists in new entities or should reference existing
                target_key = target_alias.lower().strip()
                if target_key in entity_alias_map or target_alias:
                    # Target exists, add relationship
                    relationships.append(
                        OntologyInstanceRelationshipCreate(
                            definition_id=rel_data["definition_id"],
                            target_alias=target_alias,
                            data={"justification": rel_data.get("justification", "")},
                        )
                    )

            entity.relationships = relationships

        return entities
