"""Prompt templates for the Architect pipeline."""

ARCHITECT_EXTRACTION_PROMPT = """You are the Architect Agent. Your task is to analyse a story excerpt
and suggest ontology instance updates using the provided schema.

Consider the ontology entities and the list of existing instances that might match.
Focus only on additions or updates that are material to the narrative.

Ontology Entities (id, name, description):
{entity_catalog}

Candidate Existing Instances (instance_id, alias, summary):
{existing_instances}

Story Chunk:
\"\"\"{chunk_text}\"\"\"

Return STRICT JSON with the following structure:
{{
  "new_instances": [
    {{
      "alias": "string",
      "entity_definition_id": 123,
      "confidence": 0.0,
      "justification": "why this matters",
      "metadata": {{
        "supporting_sentences": ["optional text snippets"]
      }}
    }}
  ],
  "existing_instances": [
    {{
      "entity_instance_id": "string",
      "entity_definition_id": 123,
      "confidence": 0.0,
      "justification": "why this is relevant",
      "metadata": {{
        "alias": "entity alias from the candidate list",
        "supporting_sentences": ["optional text snippets"]
      }}
    }}
  ]
}}

Rules:
- If there are no suggestions, return empty arrays.
- confidence must be between 0 and 1.
- entity_definition_id must be an integer from the entity catalog.
- entity_instance_id must come from the existing instances list.
- Do not invent properties or relationships, only flag the entity occurrence.
- The response MUST be valid JSON with double quotes.
- For existing_instances, ALWAYS include the "alias" field in metadata with the entity's alias from the candidate list.
- IMPORTANT: When matching entities, consider that names may be mentioned in different forms (e.g., "Prof. Wentworth" and "Wentworth" are the same person, "Jack" and "Jack Radford" are the same person). If an entity in the text could refer to an existing instance with a similar or abbreviated name, update the existing instance rather than creating a new one. Use the context to determine if variations of a name refer to the same entity.
"""

ARCHITECT_PROPERTY_EXTRACTION_PROMPT = """You are the Architect Agent. Your task is to extract properties and relationships for an entity from story text.

Entity Information:
- Entity Definition ID: {entity_definition_id}
- Entity Alias: {entity_alias}
- Entity Type: {entity_type_name}

Available Auto-generatable Properties (extract these if present in text):
{properties_catalog}

Available Auto-generatable Relationships (extract these if present in text):
{relationships_catalog}

Story Text Chunks:
\"\"\"
{combined_chunks}
\"\"\"

Full Original Text Context:
\"\"\"
{original_text}
\"\"\"

Return STRICT JSON with the following structure:
{{
  "properties": [
    {{
      "definition_id": 123,
      "value": "extracted value from text"
    }}
  ],
  "relationships": [
    {{
      "definition_id": 456,
      "target_alias": "name of related entity",
      "justification": "why this relationship exists based on the text"
    }}
  ],
  "autogenerated_summary": "A concise 2-3 sentence summary of this entity based on all the text provided. This should be complete and informative, suitable as a short description."
}}

Rules:
- ONLY extract properties and relationships that are explicitly mentioned or strongly implied in the text.
- Do NOT invent information not present in the text.
- For relationships, the target_alias must refer to an entity name/alias that appears in the text or is otherwise known.
- If no properties or relationships are found, return empty arrays.
- The autogenerated_summary should synthesize information from all text chunks into a coherent, concise description.
- For numerical properties, extract the number as a string or number type.
- For text properties, extract the relevant text snippet.
- The response MUST be valid JSON with double quotes.
"""

ARCHITECT_PROPERTY_UPDATE_PROMPT = """You are the Architect Agent. Your task is to update properties and relationships for an existing entity with new information from story text.

Entity Information:
- Entity Instance ID: {entity_instance_id}
- Entity Alias: {entity_alias}
- Entity Type: {entity_type_name}

Existing Entity Text:
\"\"\"
{existing_text}
\"\"\"

Existing Autogenerated Summary:
\"\"\"
{existing_autogenerated_text}
\"\"\"

Existing Properties:
{existing_properties}

Existing Relationships:
{existing_relationships}

Available Auto-generatable Properties (add new ones if present in new text):
{properties_catalog}

Available Auto-generatable Relationships (add new ones if present in new text):
{relationships_catalog}

New Story Text Chunks:
\"\"\"
{combined_chunks}
\"\"\"

Full Original Text Context:
\"\"\"
{original_text}
\"\"\"

Return STRICT JSON with the following structure:
{{
  "new_properties": [
    {{
      "definition_id": 123,
      "value": "extracted value from text"
    }}
  ],
  "new_relationships": [
    {{
      "definition_id": 456,
      "target_alias": "name of related entity",
      "justification": "why this relationship exists based on the text"
    }}
  ],
  "updated_autogenerated_summary": "An updated concise 2-3 sentence summary incorporating both the existing information and the new information from the text. This should be complete and informative, suitable as a short description."
}}

Rules:
- ONLY include properties and relationships in new_properties and new_relationships that DO NOT already exist.
- Do NOT duplicate existing properties or relationships.
- ONLY extract information that is explicitly mentioned or strongly implied in the new text.
- Do NOT invent information not present in the text.
- For relationships, the target_alias must refer to an entity name/alias that appears in the text or is otherwise known.
- If no new properties or relationships are found, return empty arrays.
- The updated_autogenerated_summary should integrate existing information with new information into a coherent, concise description.
- The response MUST be valid JSON with double quotes.
"""
