from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class ExtractedNewInstance(BaseModel):
    alias: str = Field(..., min_length=1, description="Proposed instance alias")
    entity_definition_id: int = Field(..., description="Target ontology entity definition id")
    confidence: float | None = Field(default=None, ge=0.0, le=1.0)
    justification: str | None = None
    metadata: dict[str, Any] | None = None


class ExtractedExistingInstance(BaseModel):
    entity_instance_id: str = Field(..., description="Existing entity instance identifier")
    entity_definition_id: int = Field(..., description="Ontology entity definition id")
    confidence: float | None = Field(default=None, ge=0.0, le=1.0)
    justification: str | None = None
    metadata: dict[str, Any] | None = None


class ArchitectLLMResponse(BaseModel):
    new_instances: list[ExtractedNewInstance] = Field(default_factory=list)
    existing_instances: list[ExtractedExistingInstance] = Field(default_factory=list)


class ChunkAnalysisResult(BaseModel):
    """Internal container for chunk-level suggestions."""

    chunk_index: int
    chunk_text: str
    source_entity_alias: str | None = None
    source_entity_definition_id: int | None = None
    new_instances: list[ExtractedNewInstance] = Field(default_factory=list)
    existing_instances: list[ExtractedExistingInstance] = Field(default_factory=list)
    retrieval_alias_map: dict[str, str] = Field(
        default_factory=dict,
        description="Maps entity_instance_id to alias from retrieval results",
    )

    model_config = ConfigDict(arbitrary_types_allowed=True)


class ExtractedProperty(BaseModel):
    """A property extracted from text."""

    definition_id: int
    value: Any


class ExtractedRelationship(BaseModel):
    """A relationship extracted from text."""

    definition_id: int
    target_alias: str | None = None
    target_entity_instance_id: str | None = None
    justification: str | None = None


class PropertyExtractionResponse(BaseModel):
    """Response for property extraction from text (new entity)."""

    properties: list[ExtractedProperty] = Field(default_factory=list)
    relationships: list[ExtractedRelationship] = Field(default_factory=list)
    autogenerated_summary: str | None = None


class PropertyUpdateResponse(BaseModel):
    """Response for property extraction from text (update entity)."""

    new_properties: list[ExtractedProperty] = Field(default_factory=list)
    new_relationships: list[ExtractedRelationship] = Field(default_factory=list)
    updated_autogenerated_summary: str | None = None
