from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING, Any
from uuid import uuid4

from sqlalchemy import (
    JSON,
    DateTime,
    Float,
    Enum as SqlEnum,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:  # pragma: no cover
    from app.models.agent import Agent
    from app.models.background_job import BackgroundJob


class ArchitectRunStatus(str, Enum):
    """Status values for an architect analysis run."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class ArchitectProposalStatus(str, Enum):
    """Lifecycle status for a proposal item."""

    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    MERGED = "merged"


class ArchitectProposalType(str, Enum):
    """Type of proposal produced by the architect."""

    NEW_INSTANCE = "new_instance"
    UPDATE_INSTANCE = "update_instance"


class ArchitectAnalysisRun(Base):
    """Represents a single execution of the Architect step-one pipeline."""

    __tablename__ = "architect_analysis_runs"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid4()), index=True
    )
    agent_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("agents.id", ondelete="SET NULL"), nullable=True
    )
    background_job_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("background_jobs.id", ondelete="SET NULL"), nullable=True
    )
    generation_job_id: Mapped[int | None] = mapped_column(
        Integer, nullable=True
    )
    ontology_id: Mapped[int | None] = mapped_column(Integer, nullable=True, index=True)
    ontology_instance_id: Mapped[str] = mapped_column(
        String(64), nullable=False, index=True
    )
    status: Mapped[ArchitectRunStatus] = mapped_column(
        SqlEnum(ArchitectRunStatus), nullable=False, default=ArchitectRunStatus.PENDING
    )
    settings: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    input_chunk_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    agent: Mapped["Agent"] = relationship("Agent", back_populates="architect_runs")
    background_job: Mapped["BackgroundJob"] = relationship("BackgroundJob")
    proposals: Mapped[list["ArchitectProposal"]] = relationship(
        "ArchitectProposal",
        back_populates="run",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    def __repr__(self) -> str:  # pragma: no cover - debug helper
        return (
            f"<ArchitectAnalysisRun(id={self.id}, ontology_instance={self.ontology_instance_id}, "
            f"status={self.status})>"
        )


class ArchitectProposal(Base):
    """A single proposal generated by the Architect pipeline."""

    __tablename__ = "architect_proposals"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid4()), index=True
    )
    run_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("architect_analysis_runs.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    proposal_type: Mapped[ArchitectProposalType] = mapped_column(
        SqlEnum(ArchitectProposalType), nullable=False
    )
    status: Mapped[ArchitectProposalStatus] = mapped_column(
        SqlEnum(ArchitectProposalStatus),
        nullable=False,
        default=ArchitectProposalStatus.PENDING,
    )
    entity_definition_id: Mapped[int | None] = mapped_column(Integer, nullable=True)
    entity_instance_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    alias: Mapped[str | None] = mapped_column(String(255), nullable=True)
    confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    justification: Mapped[str | None] = mapped_column(Text, nullable=True)
    evidence: Mapped[list[dict[str, Any]] | None] = mapped_column(JSON, nullable=True)
    proposal_metadata: Mapped[dict[str, Any] | None] = mapped_column(
        "metadata", JSON, nullable=True
    )
    merged_into_proposal_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("architect_proposals.id", ondelete="SET NULL"), nullable=True
    )
    corrected_alias: Mapped[str | None] = mapped_column(String(255), nullable=True)
    corrected_entity_definition_id: Mapped[int | None] = mapped_column(Integer, nullable=True)
    corrected_proposal_type: Mapped[ArchitectProposalType | None] = mapped_column(
        SqlEnum(ArchitectProposalType), nullable=True
    )
    corrected_entity_instance_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    chunks: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)
    generated_entity_instance_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    run: Mapped["ArchitectAnalysisRun"] = relationship(
        "ArchitectAnalysisRun", back_populates="proposals"
    )

    def __repr__(self) -> str:  # pragma: no cover - debug helper
        return (
            f"<ArchitectProposal(id={self.id}, type={self.proposal_type}, "
            f"status={self.status})>"
        )
