// SUGGESTION CARD — SubStep A/B/C logic added
import { useState, useRef, useEffect } from "react";
import { Combobox } from "@headlessui/react";
import { useTranslation } from "../../hooks/useTranslation";
export default function SuggestionCard({
    suggestion,
    index,
    concepts,
    pages,
    suggestions,
    token,
    subStep,
    onUpdate,
  }) {
    const { t } = useTranslation();
    const [filter, setFilter] = useState("");
    const isUpdate = suggestion.exists || suggestion.mode === "update";
    const targetPage = pages.find((p) => p.id === suggestion.target_page_id);
  
    const backgroundClass = isUpdate
      ? "bg-blue-100 border-blue-300"
      : "bg-green-100 border-green-300";
  
    const targetedByOther = suggestions.some(
      (other, i) =>
        i !== index &&
        Array.isArray(other.merge_targets) &&
        other.merge_targets.includes(suggestion.name)
    );
    const firstIndex = suggestions.findIndex((s) => s.name === suggestion.name);
    const isMerged =
      targetedByOther ||
      (firstIndex !== index &&
        Array.isArray(suggestions[firstIndex]?.merge_targets) &&
        suggestions[firstIndex].merge_targets.includes(suggestion.name));
  
    if (isMerged && subStep !== 'b') {
      return (
        <div className="border-2 border-gray-300 bg-gray-100 rounded-xl p-4">
          <div className="text-sm italic text-gray-500">
            {t('merged_suggestion_note')}
          </div>
        </div>
      );
    }
  
    return (
      <div
        className={`border-2 ${
          isMerged ? "border-gray-300 bg-gray-100" : backgroundClass
        } rounded-xl p-4 space-y-3 transition-colors duration-200`}
      >
        <div className="flex justify-between items-start">
          <div className="flex items-center gap-2">
            <h3 className="text-lg font-bold text-[var(--primary)]">
              {suggestion.name}
            </h3>
            <span
              className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                isUpdate
                  ? "bg-blue-200 text-blue-800"
                  : "bg-green-200 text-green-800"
              }`}
            >
              {isUpdate ? t('update_page') : t('new_page')}
            </span>
          </div>
          {subStep === "a" && (
            <label className="text-red-500 text-sm flex items-center gap-1 cursor-pointer">
              <input
                type="checkbox"
                className="accent-red-500 w-4 h-4"
                checked={!!suggestion._delete}
                onChange={(e) =>
                  onUpdate(index, { _delete: e.target.checked })
                }
              />
              {t('remove')}
            </label>
          )}
        </div>
  
        <div className="text-sm whitespace-pre-line border-l-4 border-yellow-400 pl-4">
          <div dangerouslySetInnerHTML={{ __html: suggestion.autogenerated_content }} />
        </div>
        {Array.isArray(suggestion.source_pages) && suggestion.source_pages.length > 0 && (
          <div className="text-xs text-[var(--muted-foreground)]">
            {t('from')} {suggestion.source_pages.map((sp: any) => sp.name).join(', ')}
          </div>
        )}
  
        {!isMerged && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {subStep === 'c' && (
              <>
                <div>
                  <label className="block text-sm font-semibold mb-1">{t('action')}</label>
                  <select
                    value={suggestion.mode || (suggestion.exists ? "update" : "create")}
                    onChange={(e) => onUpdate(index, { mode: e.target.value, target_page_id: undefined })}
                    className="w-full px-2 py-1 rounded border border-[var(--primary)] bg-[var(--surface)] text-[var(--foreground)]"
                  >
                    <option value="create">{t('create_new')}</option>
                    <option value="update">{t('update_existing')}</option>
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-semibold mb-1">{t('concept')}</label>
                  <select
                    className="w-full px-2 py-1 rounded border border-[var(--primary)] bg-[var(--surface)] text-[var(--foreground)]"
                    value={suggestion.concept_id || ""}
                    onChange={(e) =>
                      onUpdate(index, {
                        concept_id: Number(e.target.value),
                        concept: concepts.find((c) => c.id === Number(e.target.value))?.name || "",
                      })
                    }
                  >
                    <option value="">{t('select')}</option>
                    {concepts.map((c) => (
                      <option key={c.id} value={c.id}>
                        {c.name}
                      </option>
                    ))}
                  </select>
                </div>
              </>
            )}
  
            {subStep === 'c' && (suggestion.mode === "update" || (!suggestion.mode && suggestion.exists)) && (
              <div className="col-span-2">
                <label className="block text-sm font-semibold mb-1">
                  {suggestion.exists && targetPage
                    ? `${t('update_this_page')}: ${targetPage.name}`
                    : t('select_page_to_update')}
                </label>
                <Combobox
                  value={suggestion.target_page_id ?? ""}
                  onChange={(val) => onUpdate(index, { target_page_id: val })}
                >
                  <div className="relative">
                    <Combobox.Input
                      className="w-full rounded border border-[var(--primary)] px-2 py-1 bg-[var(--surface)] text-[var(--foreground)]"
                      placeholder={t('search_page')}
                      onChange={(e) => setFilter(e.target.value)}
                      displayValue={(id) => pages.find((p) => p.id === id)?.name || ""}
                    />
                    <Combobox.Options className="absolute mt-1 max-h-60 w-full overflow-auto rounded-xl bg-[var(--surface)] shadow-lg z-20 border border-[var(--primary)]">
                      {pages
                        .filter(
                          (p) =>
                            p.concept_id === suggestion.concept_id &&
                            p.name.toLowerCase().includes(filter.toLowerCase())
                        )
                        .sort((a, b) => a.name.localeCompare(b.name))
                        .map((p) => (
                          <Combobox.Option
                            key={p.id}
                            value={p.id}
                            className="px-2 py-1 cursor-pointer hover:bg-[var(--accent)]/20"
                          >
                            {p.name}
                          </Combobox.Option>
                        ))}
                    </Combobox.Options>
                  </div>
                </Combobox>
              </div>
            )}
  
            {subStep === 'b' && (
              <div className="col-span-2">
                <label className="block text-sm font-semibold mb-1">{t('merge_with')}</label>
                <Combobox
                  multiple
                  value={suggestion.merge_targets || []}
                  onChange={(vals) => onUpdate(index, { merge_targets: vals })}
                >
                  <div className="relative">
                    <Combobox.Input
                      className="w-full rounded border border-[var(--primary)] px-2 py-1 bg-[var(--surface)] text-[var(--foreground)]"
                      placeholder={t('search_page')}
                      onChange={(e) => setFilter(e.target.value)}
                      displayValue={() => ''}
                    />
                    <Combobox.Options className="absolute mt-1 max-h-60 w-full overflow-auto rounded-xl bg-[var(--surface)] shadow-lg z-20 border border-[var(--primary)]">
                      {suggestions
                        .filter((s, i) => i !== index && s.name.toLowerCase().includes(filter.toLowerCase()))
                        .sort((a, b) => a.name.localeCompare(b.name))
                        .map((suggOption, i) => (
                          <Combobox.Option
                            key={i}
                            value={suggOption.name}
                            className="px-2 py-1 cursor-pointer hover:bg-[var(--accent)]/20"
                          >
                            {suggOption.name}
                          </Combobox.Option>
                        ))}
                    </Combobox.Options>
                  </div>
                </Combobox>
                <div className="flex flex-wrap gap-2 mt-2">
                  {(suggestion.merge_targets || []).map((tgt: string) => (
                    <span key={tgt} className="px-2 py-1 rounded-full text-xs bg-[var(--primary)] text-white flex items-center gap-1">
                      {tgt}
                      <button
                        type="button"
                        onClick={() => {
                          const updated = (suggestion.merge_targets || []).filter((n: string) => n !== tgt);
                          onUpdate(index, { merge_targets: updated });
                        }}
                        className="ml-1 text-white hover:text-gray-200"
                      >
                        &times;
                      </button>
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    );
  }
  
  