from __future__ import annotations

import pytest

from app.integrations.llm.model_policy import ModelPolicy
from app.jobs.architect.timeline_generation import (
    dedup_timeline_events,
    generate_timeline_events_for_entity,
)


class _FakeGraphSession:
    async def run(self, *_args, **_kwargs):
        class _Result:
            async def single(self):
                return None

            async def data(self):
                return []

        return _Result()


class _FakeLLM:
    async def chat(self, **_kwargs):
        return "[]"


@pytest.mark.asyncio
async def test_generate_timeline_events_skips_when_existing(monkeypatch):
    async def _fetch_entity(_gs, _id):
        return {
            "instance_id": "inst-1",
            "ontology_id": 1,
            "entity_instance_id": "ent-1",
            "alias": "Alice",
            "text": "Alice did something.",
            "autogenerated_text": "",
        }

    monkeypatch.setattr(
        "app.jobs.architect.timeline_generation._fetch_entity_context",
        _fetch_entity,
    )

    async def _has_events(_graph_session, **_kwargs):
        return True

    monkeypatch.setattr(
        "app.jobs.architect.timeline_generation._entity_has_timeline_events",
        _has_events,
    )

    result = await generate_timeline_events_for_entity(
        graph_session=_FakeGraphSession(),
        llm_client=_FakeLLM(),
        model_policy=ModelPolicy(),
        entity_instance_id="ent-1",
        max_events=3,
        force=False,
    )

    assert result["status"] == "skipped"
    assert result["reason"] == "existing_events_present"


@pytest.mark.asyncio
async def test_generate_timeline_events_fails_without_text(monkeypatch):
    async def _fetch_entity(_gs, _id):
        return {
            "instance_id": "inst-1",
            "ontology_id": 1,
            "entity_instance_id": "ent-1",
            "alias": "Alice",
            "text": "",
            "autogenerated_text": "",
        }

    monkeypatch.setattr(
        "app.jobs.architect.timeline_generation._fetch_entity_context",
        _fetch_entity,
    )

    async def _has_events(_graph_session, **_kwargs):
        return False

    monkeypatch.setattr(
        "app.jobs.architect.timeline_generation._entity_has_timeline_events",
        _has_events,
    )

    with pytest.raises(ValueError, match="no usable source text"):
        await generate_timeline_events_for_entity(
            graph_session=_FakeGraphSession(),
            llm_client=_FakeLLM(),
            model_policy=ModelPolicy(),
            entity_instance_id="ent-1",
            max_events=3,
            force=False,
        )


def test_dedup_timeline_events_limits_and_sorts():
    events = [
        {"title": "Battle Starts", "description": "The battle begins.", "order": 2, "chunk_index": 0, "chunk_order": 2, "temporal_hint": 0.0},
        {"title": "Battle Starts", "description": "The battle begins (duplicate).", "order": 3, "chunk_index": 0, "chunk_order": 3, "temporal_hint": 0.0},
        {"title": "Arrival", "description": "They arrive.", "order": 1, "chunk_index": 0, "chunk_order": 1, "temporal_hint": 0.0},
        {"title": "Aftermath", "description": "The dust settles.", "order": 4, "chunk_index": 0, "chunk_order": 4, "temporal_hint": 0.0},
    ]
    result = dedup_timeline_events(events, max_events=2)
    assert len(result) == 2
    titles = [item["title"] for item in result]
    assert len(set(titles)) == 2
