import pytest

from app.agentic_ai.agentic_worker_shrecknet import extract_metadata_and_chunks_worker
from app.agentic_ai import agentic_worker_llm
from app.agentic_ai.agentic_worker_llm import generate_process_source_worker
from app.models.model_page import Page


@pytest.mark.anyio
async def test_extract_metadata_uses_autogenerated_content():
    page = Page(
        gameworld_id=1, concept_id=1, name="P", autogenerated_content="<p>Generated</p>"
    )
    meta, chunks = await extract_metadata_and_chunks_worker(page)
    assert meta == ""
    assert chunks == ["Generated"]


@pytest.mark.anyio
async def test_generate_process_source_uses_autogenerated_content(monkeypatch):
    page = Page(
        gameworld_id=1, concept_id=1, name="Src", autogenerated_content="<p>Chunk</p>"
    )
    recorded_chunks = []

    async def fake_chunk_worker(llm, concept_map, sp, chunk, specs, spec_data):
        recorded_chunks.append(chunk)

    monkeypatch.setattr(
        agentic_worker_llm, "generate_process_chunk_worker", fake_chunk_worker
    )
    await generate_process_source_worker(
        page, [], llm=None, concept_map={}, spec_data={}
    )
    assert recorded_chunks == ["Chunk"]
