import json
from types import SimpleNamespace
from unittest.mock import patch

from langchain_core.runnables import RunnableLambda

import pytest

from app.crud.crud_agent_writer import generate_pages_worker
from app.crud import crud_page
from app.models.model_agent import Agent
from app.models.model_concept import Concept
from app.models.model_gameworld import GameWorld
from app.models.model_page import Page


@pytest.mark.anyio
async def test_update_existing_page_no_duplicate(session):
    gw = GameWorld(name="W", system="s", description="d", created_by=1)
    session.add(gw)
    await session.commit()
    await session.refresh(gw)

    concept = Concept(gameworld_id=gw.id, name="C")
    session.add(concept)
    await session.commit()
    await session.refresh(concept)

    agent = Agent(name="A", world_id=gw.id)
    session.add(agent)
    await session.commit()
    await session.refresh(agent)

    page = Page(
        name="Hero",
        gameworld_id=gw.id,
        concept_id=concept.id,
        autogenerated_content="Old text.",
    )
    other = Page(
        name="Other",
        gameworld_id=gw.id,
        concept_id=concept.id,
        content="T",
    )
    session.add(page)
    session.add(other)
    await session.commit()
    await session.refresh(page)
    await session.refresh(other)

    spec = {
        "mode": "update",
        "target_page_id": page.id,
        "concept_id": concept.id,
    }

    payload = {
        "autogenerated_content": "New text.",
        "key_events": [{"event_type": "founding", "description": "desc"}],
        "relationships": [
            {
                "target_page": "Other",
                "relationship_type": "ally",
                "direction": "outgoing",
            }
        ],
    }

    async def dummy_llm(_input, **_kwargs):
        return SimpleNamespace(content=json.dumps(payload))

    with patch(
        "app.crud.crud_agent_writer.ChatOpenAI",
        return_value=RunnableLambda(dummy_llm),
    ):
        result = await generate_pages_worker(session, agent, page, [spec])
        assert result["pages"] == []
        assert result["updated"][0]["id"] == page.id

    updated_page = await crud_page.get_page(session, page.id)
    assert updated_page.autogenerated_content == "Old text.\n\nNew text."

    events = await crud_page.get_key_events(session, page.id)
    assert len(events) == 1
    assert events[0].event_type == "founding"

    rels = await crud_page.get_relationships(session, page.id)
    assert len(rels) == 1
    assert rels[0].target_page_id == other.id

    # Run again to ensure no duplicates are created
    with patch(
        "app.crud.crud_agent_writer.ChatOpenAI",
        return_value=RunnableLambda(dummy_llm),
    ):
        await generate_pages_worker(session, agent, page, [spec])

    events = await crud_page.get_key_events(session, page.id)
    assert len(events) == 1
    rels = await crud_page.get_relationships(session, page.id)
    assert len(rels) == 1
