"""Celery task for Novelist draft generation (step 1)."""

from __future__ import annotations

import json
import logging
from types import SimpleNamespace
from typing import Any

from app.celery_app import celery_app
from app.core.config_store import get_settings, is_shreckllm_configured
from app.db.session import AsyncSessionMaker
from app.integrations.llm.model_policy import ModelPolicy
from app.integrations.llm.shreckllm_client import ShreckLLMClient
from app.integrations.retrieval.neo4j_retriever import Neo4jGraphRetriever
from app.graph.neo4j import get_driver
from app.jobs.elder.elder import ElderOrchestrator
from app.jobs.elder.schemas import ElderQueryRequest
from app.jobs.novelist.novelist import NovelistOrchestrator
from app.models.agent import Agent
from app.models.background_job import AuthorType, JobType
from app.models.novelist import NovelistRunStatus, NovelistStage
from app.repositories.agent_repository import AgentRepository
from app.repositories.ontology_repository import OntologyRepository
from app.repositories.novelist_repository import NovelistRepository
from app.schemas.novelist import NovelistRunCreate
from app.tasks.architect_analysis import (
    _build_allowed_ontology_map,
    _format_ontology_definitions_from_entities,
    _load_existing_nodes,
    _run_entity_proposal_phase,
    _run_milestone_proposal_phase,
    _run_scene_chunking_phase,
    _run_scene_proposal_phase,
)
from app.utils.async_helpers import run_async
from app.utils.job_tracking import (
    create_background_job,
    mark_job_done,
    mark_job_failed,
    mark_job_running,
    update_job_progress,
)

logger = logging.getLogger(__name__)


def _clean_optional_text(value: Any) -> str:
    if not isinstance(value, str):
        return ""
    return value.strip()


def _extract_best_text_from_record(record: Any) -> str:
    if not record:
        return ""
    for key in ("text", "text_linked", "autogenerated_text", "autogenerated_text_linked"):
        candidate = _clean_optional_text(record.get(key))
        if candidate:
            return candidate
    return ""


async def _resolve_previous_session_text(
    previous_session_id: str | None,
) -> tuple[str, str]:
    session_id = _clean_optional_text(previous_session_id)
    if not session_id:
        return "", "missing_id"
    try:
        settings = get_settings()
        driver = get_driver()
        async with driver.session(database=settings.neo4j_database) as graph_session:
            # 1) Direct match as EntityInstance id.
            entity_result = await graph_session.run(
                """
                MATCH (node:EntityInstance {entity_instance_id: $session_id})
                RETURN node.text AS text,
                       node.text_linked AS text_linked,
                       node.autogenerated_text AS autogenerated_text,
                       node.autogenerated_text_linked AS autogenerated_text_linked
                LIMIT 1
                """,
                session_id=session_id,
            )
            entity_record = await entity_result.single()

            # 2) Match as OntologyInstance id and read candidate entity texts.
            instance_entities_result = await graph_session.run(
                """
                MATCH (:OntologyInstance {instance_id: $session_id})-[:HAS_ENTITY]->(node:EntityInstance)
                RETURN node.text AS text,
                       node.text_linked AS text_linked,
                       node.autogenerated_text AS autogenerated_text,
                       node.autogenerated_text_linked AS autogenerated_text_linked
                ORDER BY size(coalesce(node.text, '')) DESC,
                         size(coalesce(node.autogenerated_text, '')) DESC
                LIMIT 20
                """,
                session_id=session_id,
            )
            instance_entity_records = await instance_entities_result.data()

    except Exception:
        logger.warning(
            "Could not resolve previous session text for session_id=%s",
            session_id,
            exc_info=True,
        )
        return "", "lookup_error"

    entity_text = _extract_best_text_from_record(entity_record)
    if entity_text:
        return entity_text, "matched_entity_instance_id"

    for record in instance_entity_records:
        text = _extract_best_text_from_record(record)
        if text:
            return text, "matched_ontology_instance_entities"

    return "", "no_text_found"


async def _execute_run(
    *,
    run_id: str,
    request_payload: dict[str, Any],
    job_id: int,
) -> dict[str, Any]:
    settings = get_settings()
    if not is_shreckllm_configured(settings):
        raise RuntimeError("shreckLLM is not configured")
    async with AsyncSessionMaker() as session:
        repo = NovelistRepository(session)
        agent_repo = AgentRepository(session)

        run = await repo.get_run(run_id)
        if not run:
            raise ValueError("Novelist run not found")

        novelist_agent = await agent_repo.get_by_id(run.agent_id)
        if not novelist_agent:
            raise ValueError("Agent not found")

        llm_client = ShreckLLMClient(base_url=settings.shreckllm_base_url, timeout=settings.shreckllm_request_timeout_s, max_retries=settings.shreckllm_max_retries)
        try:
            await update_job_progress(job_id, 0.05, {"status": "preparing orchestrator"})
            model_policy = ModelPolicy(
                default_model=settings.model_novelist,
                architect_extract_model=settings.model_architect,
            )
            # Attach novelist-specific model preferences for orchestrator
            setattr(model_policy, "model_novelist_draft", settings.model_novelist_draft)
            setattr(
                model_policy,
                "model_novelist",
                settings.model_novelist,
            )
            setattr(model_policy, "model_elder", settings.model_elder)

            async def elder_query_runner(agent: Agent, query: str) -> list[dict[str, Any]]:
                # Elder context is an optional flavor-only layer: never plot authority.
                ontology_ids = [ontology.id for ontology in (agent.ontologies or [])]
                if not ontology_ids:
                    return []
                try:
                    driver = get_driver()
                    async with driver.session(database=settings.neo4j_database) as graph_session:
                        retriever = Neo4jGraphRetriever(graph_session)
                        elder_orchestrator = ElderOrchestrator(
                            llm_client=llm_client,
                            model_policy=model_policy,
                            graph_retriever=retriever,
                            default_top_k=getattr(settings, "default_top_k", 8),
                        )
                        response = await elder_orchestrator.execute(
                            agent,
                            ElderQueryRequest(
                                query=query,
                                mode="context",
                                top_k=6,
                                include_trace=False,
                                fast=True,
                                route="fast",
                            ),
                        )
                except Exception:
                    logger.warning(
                        "Elder lookup failed for novelist enhancement query=%s",
                        query,
                        exc_info=True,
                    )
                    return []
                results: list[dict[str, Any]] = []
                for source in (response.sources or []):
                    if not hasattr(source, "model_dump"):
                        continue
                    payload = source.model_dump()
                    if not str(payload.get("text") or "").strip():
                        # Keep a context-like shape expected by downstream compactors.
                        payload["text"] = "; ".join(
                            [
                                str((chunk or {}).get("text") or "")
                                for chunk in payload.get("evidence_chunks", [])
                                if isinstance(chunk, dict)
                            ]
                        )
                    results.append(payload)
                return results

            async def architect_scaffolding_runner(
                agent: Agent,
                unstructured_text: str,
                instructions: str,
                _conversation_id: str | None,
            ) -> dict[str, Any]:
                ontology_repo = OntologyRepository(session)
                agent_ontology_ids = [ontology.id for ontology in (agent.ontologies or [])]
                ontology_entities: list[Any] = []
                for ontology_id in agent_ontology_ids:
                    ontology_entities.extend(await ontology_repo.list_entities(ontology_id))

                ontology_definitions = _format_ontology_definitions_from_entities(
                    ontology_entities
                )

                driver = get_driver()
                async with driver.session(database=settings.neo4j_database) as graph_session:
                    retriever = Neo4jGraphRetriever(graph_session)
                    existing_nodes = await _load_existing_nodes(
                        retriever,
                        agent_ontology_ids,
                    )

                source_entity = SimpleNamespace(
                    entity_instance_id=request_payload.get("previous_session_id") or "novelist-source",
                    alias="novelist-source",
                    text=unstructured_text,
                    autogenerated_text=None,
                )
                pseudo_instance = SimpleNamespace(entities=[source_entity])

                scene_chunking_model = settings.model_architect_scene_chunking
                architect_model = settings.model_architect
                chunking_phase = await _run_scene_chunking_phase(
                    run_id=run_id,
                    ontology_instance=pseudo_instance,
                    llm_client=llm_client,
                    model=scene_chunking_model,
                    instructions=instructions,
                )
                entity_phase = await _run_entity_proposal_phase(
                    run_id=run_id,
                    llm_client=llm_client,
                    model=architect_model,
                    ontology_definitions=ontology_definitions,
                    allowed_ontology_names=_build_allowed_ontology_map(ontology_entities),
                    existing_nodes=existing_nodes,
                    chunk_results=chunking_phase["chunk_results"],
                    instructions=instructions,
                )
                scene_phase = _run_scene_proposal_phase(
                    run_id=run_id,
                    scene_inputs=entity_phase["scene_inputs"],
                    proposed_entities=entity_phase["proposed_entities"],
                    author_id=agent.id,
                )
                milestone_phase = await _run_milestone_proposal_phase(
                    run_id=run_id,
                    llm_client=llm_client,
                    model=architect_model,
                    proposed_scenes=scene_phase["proposed_scenes"],
                    author_id=agent.id,
                    instructions=instructions,
                )

                milestone_titles_by_scene: dict[str, list[str]] = {}
                per_scene = milestone_phase.get("per_scene") or {}
                if isinstance(per_scene, list):
                    scene_milestone_pairs = [
                        (row.get("scene_ref"), row.get("milestones"))
                        for row in per_scene
                        if isinstance(row, dict)
                    ]
                elif isinstance(per_scene, dict):
                    scene_milestone_pairs = list(per_scene.items())
                else:
                    scene_milestone_pairs = []

                for scene_ref, milestones in scene_milestone_pairs:
                    scene_key = str(scene_ref or "").strip()
                    if not scene_key:
                        continue
                    milestone_titles_by_scene[scene_key] = [
                        str(item.get("title") or item.get("label") or "").strip()
                        for item in (milestones or [])
                        if isinstance(item, dict)
                        and str(item.get("title") or item.get("label") or "").strip()
                    ]

                scenes: list[dict[str, Any]] = []
                for order, scene in enumerate(scene_phase.get("proposed_scenes") or [], start=1):
                    scene_ref = str(scene.get("scene_ref") or f"scene_{order}")
                    related_entities = [
                        str(item.get("alias") or item.get("canonical") or "").strip()
                        for item in (scene.get("related_to") or [])
                        if isinstance(item, dict)
                        and str(item.get("alias") or item.get("canonical") or "").strip()
                    ]
                    # Preserve order and de-duplicate aliases.
                    dedup_related: list[str] = []
                    seen_related: set[str] = set()
                    for alias in related_entities:
                        key = alias.lower()
                        if key in seen_related:
                            continue
                        seen_related.add(key)
                        dedup_related.append(alias)

                    scenes.append(
                        {
                            "scene_id": f"scene-{order:03d}",
                            "name": str(scene.get("scene_name") or f"Scene {order}").strip(),
                            "scene_summary": str(scene.get("scene_description") or "").strip(),
                            "raw_scene_text": str(scene.get("scene_text") or "").strip(),
                            "source_paragraphs": [],
                            "source_anchors": [scene_ref],
                            "milestones": milestone_titles_by_scene.get(scene_ref, []),
                            "related_entities": dedup_related,
                            "new_or_update": "new",
                        }
                    )

                return {
                    "models": {
                        "scene_chunking": scene_chunking_model,
                        "architect": architect_model,
                    },
                    "scene_count": len(scenes),
                    "scene_chunking": {
                        "chunk_count": chunking_phase.get("chunk_count", 0),
                        "scene_count": chunking_phase.get("scene_count", 0),
                        "elapsed_seconds": chunking_phase.get("elapsed_seconds", 0.0),
                    },
                    "entity_phase": {
                        "updated_count": entity_phase.get("updated_count", 0),
                        "new_count": entity_phase.get("new_count", 0),
                        "elapsed_seconds": entity_phase.get("elapsed_seconds", 0.0),
                    },
                    "milestone_phase": {
                        "milestone_count": milestone_phase.get("milestone_count", 0),
                        "elapsed_seconds": milestone_phase.get("elapsed_seconds", 0.0),
                    },
                    "scenes": scenes,
                }

            orchestrator = NovelistOrchestrator(
                llm_client=llm_client,
                model_policy=model_policy,
                max_concurrency=4,
                elder_query_concurrency=settings.novelist_elder_query_concurrency,
                elder_query_timeout_s=settings.novelist_elder_query_timeout_s,
                elder_query_runner=elder_query_runner,
                architect_scaffolding_runner=architect_scaffolding_runner,
            )

            await repo.update_status(
                run_id,
                status=NovelistRunStatus.RUNNING,
                stage=NovelistStage.INGEST,
            )
            await session.commit()

            await update_job_progress(job_id, 0.1, {"status": "preparing sources"})
            previous_session_text, previous_session_lookup_status = await _resolve_previous_session_text(
                request_payload.get("previous_session_id")
            )
            request_payload_enriched = dict(request_payload)
            if previous_session_text:
                request_payload_enriched["previous_session_text"] = previous_session_text

            await repo.update_status(
                run_id,
                artifacts={
                    "inputs": {
                        "previous_session_id": request_payload.get("previous_session_id"),
                        "previous_session_lookup_status": previous_session_lookup_status,
                    }
                },
            )
            await session.commit()

            stage_progress = {
                NovelistStage.SCAFFOLDING: (0.2, "Building scene scaffolding"),
                NovelistStage.SCENE_PACKAGE: (0.35, "Building scene packages"),
                NovelistStage.RETRIEVAL: (0.5, "Retrieving scene context"),
                NovelistStage.INTENT_DRAFTING: (0.65, "Drafting scene intent"),
                NovelistStage.PROSE_GENERATION: (0.8, "Generating scene prose"),
                NovelistStage.CRITIC: (0.9, "Critic review"),
                NovelistStage.REVISION: (0.95, "Applying targeted revisions"),
                NovelistStage.MERGING: (0.98, "Merging final chapter"),
            }

            async def stage_callback(
                stage: NovelistStage, payload: dict[str, Any] | None = None
            ) -> None:
                payload = payload or {}
                update_kwargs: dict[str, Any] = {"stage": stage}
                if "artifacts" in payload:
                    update_kwargs["artifacts"] = payload["artifacts"]
                if "draft_text" in payload:
                    update_kwargs["draft_text"] = payload["draft_text"]
                if "critic_notes" in payload:
                    critic_notes = payload["critic_notes"]
                    if critic_notes is None:
                        update_kwargs["critic_notes"] = None
                    elif isinstance(critic_notes, str):
                        update_kwargs["critic_notes"] = critic_notes
                    else:
                        update_kwargs["critic_notes"] = json.dumps(
                            critic_notes, ensure_ascii=True
                        )
                await repo.update_status(run_id, **update_kwargs)
                await session.commit()
                progress_info = stage_progress.get(stage)
                if progress_info:
                    progress_value, progress_status = progress_info
                    detail_payload: dict[str, Any] = {"status": progress_status}
                    scene_count = payload.get("scene_count")
                    if isinstance(scene_count, int):
                        detail_payload["scene_count"] = scene_count
                    timing_summary = payload.get("timing_summary")
                    if isinstance(timing_summary, dict):
                        detail_payload["timing_summary"] = timing_summary
                    if isinstance(payload.get("scene_results"), list):
                        detail_payload["scene_results_count"] = len(payload["scene_results"])
                    await update_job_progress(
                        job_id,
                        progress_value,
                        detail_payload,
                    )

            result = await orchestrator.execute(
                agent=novelist_agent,
                payload=NovelistRunCreate.model_validate(request_payload_enriched),
                conversation_id=f"novelist_run:{run_id}",
                stage_callback=stage_callback,
            )
            result_artifacts = result.get("artifacts")
            update_kwargs: dict[str, Any] = {
                "status": NovelistRunStatus.COMPLETED,
                "stage": NovelistStage.DONE,
                "draft_text": result.get("final_text_html"),
                "critic_notes": json.dumps(result.get("critic_remarks", {}), ensure_ascii=True),
            }
            if isinstance(result_artifacts, dict):
                inputs_artifact = result_artifacts.get("inputs")
                if not isinstance(inputs_artifact, dict):
                    inputs_artifact = {}
                inputs_artifact.setdefault(
                    "previous_session_id", request_payload.get("previous_session_id")
                )
                inputs_artifact["previous_session_lookup_status"] = previous_session_lookup_status
                result_artifacts["inputs"] = inputs_artifact
                result["artifacts"] = result_artifacts
                update_kwargs["artifacts"] = result_artifacts

            await repo.update_status(run_id, **update_kwargs)
            await session.commit()
            await update_job_progress(job_id, 1.0, {"status": "completed"})
            await mark_job_done(job_id, {"run_id": run_id, "status": "completed"})
            usage_summary = llm_client.get_usage_summary()
            logger.info(
                "novelist_llm_usage run_id=%s totals=%s by_model=%s",
                run_id,
                usage_summary.get("totals"),
                usage_summary.get("by_model"),
            )
            return result
        except Exception as exc:
            logger.error("Novelist run %s failed: %s", run_id, exc, exc_info=True)
            await session.rollback()
            await repo.update_status(
                run_id,
                status=NovelistRunStatus.FAILED,
                error_message=str(exc),
            )
            await session.commit()
            await mark_job_failed(job_id, str(exc))
            raise
        finally:
            await llm_client.aclose()


@celery_app.task(name="novelist.generate_draft")
def generate_draft(
    run_id: str,
    request_payload: dict[str, Any],
    *,
    author_type: str = "user",
    author_id: str = "system",
) -> dict[str, Any]:
    """Entry-point Celery task for novelist draft generation (step 1)."""
    description = f"Novelist draft generation for run {run_id}"
    job_id = run_async(
        create_background_job(
            author_type=AuthorType(author_type),
            author_id=author_id,
            job_type=JobType.NOVELIST_DRAFT,
            description=description,
            celery_task_id=generate_draft.request.id,
            details={"run_id": run_id},
        )
    )

    try:
        run_async(mark_job_running(job_id))

        async def _attach() -> None:
            async with AsyncSessionMaker() as session:
                repo = NovelistRepository(session)
                await repo.attach_background_job(run_id, job_id)
                await session.commit()

        run_async(_attach())
        result = run_async(
            _execute_run(run_id=run_id, request_payload=request_payload, job_id=job_id)
        )
        return {"job_id": job_id, "status": "success", "run_id": run_id, **result}
    except Exception as exc:
        run_async(mark_job_failed(job_id, str(exc)))
        raise
