"""Celery task for Novelist draft generation (step 1)."""

from __future__ import annotations

import json
import logging
from typing import Any

from app.celery_app import celery_app
from app.core.config_store import get_settings, is_openai_configured
from app.db.session import AsyncSessionMaker
from app.integrations.llm.model_policy import ModelPolicy
from app.integrations.llm.openai_client import OpenAIClient
from app.integrations.retrieval.neo4j_retriever import Neo4jGraphRetriever
from app.graph.neo4j import get_driver
from app.jobs.elder.elder import ElderOrchestrator
from app.jobs.elder.schemas import ElderQueryRequest
from app.jobs.novelist.novelist import NovelistOrchestrator
from app.models.agent import Agent
from app.models.background_job import AuthorType, JobType
from app.models.novelist import NovelistRunStatus, NovelistStage
from app.repositories.agent_repository import AgentRepository
from app.repositories.novelist_repository import NovelistRepository
from app.schemas.novelist import NovelistRunCreate
from app.utils.async_helpers import run_async
from app.utils.job_tracking import (
    create_background_job,
    mark_job_done,
    mark_job_failed,
    mark_job_running,
    update_job_progress,
)

logger = logging.getLogger(__name__)


def _clean_optional_text(value: Any) -> str:
    if not isinstance(value, str):
        return ""
    return value.strip()


def _extract_best_text_from_record(record: Any) -> str:
    if not record:
        return ""
    for key in ("text", "text_linked", "autogenerated_text", "autogenerated_text_linked"):
        candidate = _clean_optional_text(record.get(key))
        if candidate:
            return candidate
    return ""


async def _resolve_previous_session_text(
    previous_session_id: str | None,
) -> tuple[str, str]:
    session_id = _clean_optional_text(previous_session_id)
    if not session_id:
        return "", "missing_id"
    try:
        settings = get_settings()
        driver = get_driver()
        async with driver.session(database=settings.neo4j_database) as graph_session:
            # 1) Direct match as EntityInstance id.
            entity_result = await graph_session.run(
                """
                MATCH (node:EntityInstance {entity_instance_id: $session_id})
                RETURN node.text AS text,
                       node.text_linked AS text_linked,
                       node.autogenerated_text AS autogenerated_text,
                       node.autogenerated_text_linked AS autogenerated_text_linked
                LIMIT 1
                """,
                session_id=session_id,
            )
            entity_record = await entity_result.single()

            # 2) Match as OntologyInstance id and read candidate entity texts.
            instance_entities_result = await graph_session.run(
                """
                MATCH (:OntologyInstance {instance_id: $session_id})-[:HAS_ENTITY]->(node:EntityInstance)
                RETURN node.text AS text,
                       node.text_linked AS text_linked,
                       node.autogenerated_text AS autogenerated_text,
                       node.autogenerated_text_linked AS autogenerated_text_linked
                ORDER BY size(coalesce(node.text, '')) DESC,
                         size(coalesce(node.autogenerated_text, '')) DESC
                LIMIT 20
                """,
                session_id=session_id,
            )
            instance_entity_records = await instance_entities_result.data()

    except Exception:
        logger.warning(
            "Could not resolve previous session text for session_id=%s",
            session_id,
            exc_info=True,
        )
        return "", "lookup_error"

    entity_text = _extract_best_text_from_record(entity_record)
    if entity_text:
        return entity_text, "matched_entity_instance_id"

    for record in instance_entity_records:
        text = _extract_best_text_from_record(record)
        if text:
            return text, "matched_ontology_instance_entities"

    return "", "no_text_found"


async def _execute_run(
    *,
    run_id: str,
    request_payload: dict[str, Any],
    job_id: int,
) -> dict[str, Any]:
    settings = get_settings()
    if not is_openai_configured(settings):
        raise RuntimeError("OpenAI API key not configured")
    async with AsyncSessionMaker() as session:
        repo = NovelistRepository(session)
        agent_repo = AgentRepository(session)

        run = await repo.get_run(run_id)
        if not run:
            raise ValueError("Novelist run not found")

        novelist_agent = await agent_repo.get_by_id(run.agent_id)
        if not novelist_agent:
            raise ValueError("Agent not found")

        llm_client = OpenAIClient(
            api_key=settings.openai_api_key,
            timeout=180,
            max_retries=3,
        )
        try:
            await update_job_progress(job_id, 0.05, {"status": "preparing orchestrator"})
            model_policy = ModelPolicy(
                decompose_model=settings.model_decompose,
                subanswer_model=settings.model_subanswer,
                synthesis_model=settings.model_synthesis,
                validation_model=settings.model_validation,
                style_model=settings.model_style,
                architect_extract_model=getattr(
                    settings, "model_architect_extract", settings.model_decompose
                ),
            )
            # Attach novelist-specific model preferences for orchestrator
            setattr(model_policy, "model_novelist_draft", settings.model_novelist_draft)
            setattr(model_policy, "model_novelist_critic", settings.model_novelist_critic)

            async def elder_query_runner(agent: Agent, query: str) -> list[dict[str, Any]]:
                # Elder context is an optional flavor-only layer: never plot authority.
                ontology_ids = [ontology.id for ontology in agent.ontologies]
                if not ontology_ids:
                    return []
                try:
                    driver = get_driver()
                    async with driver.session(database=settings.neo4j_database) as graph_session:
                        retriever = Neo4jGraphRetriever(graph_session)
                        elder_orchestrator = ElderOrchestrator(
                            llm_client=llm_client,
                            model_policy=model_policy,
                            graph_retriever=retriever,
                            default_top_k=getattr(settings, "default_top_k", 8),
                        )
                        response = await elder_orchestrator.execute(
                            agent,
                            ElderQueryRequest(
                                query=query,
                                mode="context",
                                top_k=6,
                                include_trace=False,
                                fast=True,
                            ),
                        )
                except Exception:
                    logger.warning(
                        "Elder lookup failed for novelist enhancement query=%s",
                        query,
                        exc_info=True,
                    )
                    return []
                return [
                    chunk.model_dump()
                    for chunk in (response.context or [])
                    if hasattr(chunk, "model_dump")
                ]

            orchestrator = NovelistOrchestrator(
                llm_client=llm_client,
                model_policy=model_policy,
                max_concurrency=2,
                elder_query_runner=elder_query_runner,
            )

            await repo.update_status(
                run_id,
                status=NovelistRunStatus.RUNNING,
                stage=NovelistStage.INGEST,
            )
            await session.commit()

            await update_job_progress(job_id, 0.1, {"status": "preparing sources"})
            previous_session_text, previous_session_lookup_status = await _resolve_previous_session_text(
                request_payload.get("previous_session_id")
            )
            previous_session_summary = await orchestrator._build_continuity_brief(
                previous_session_text=previous_session_text,
                language=_clean_optional_text(request_payload.get("language")),
                instructions=_clean_optional_text(request_payload.get("instructions")),
                conversation_id=f"novelist_run:{run_id}:continuity",
            )
            request_payload_enriched = dict(request_payload)
            if previous_session_text:
                request_payload_enriched["previous_session_text"] = previous_session_text
            if previous_session_summary:
                request_payload_enriched["previous_session_summary"] = previous_session_summary

            await repo.update_status(
                run_id,
                artifacts={
                    "inputs": {
                        "previous_session_id": request_payload.get("previous_session_id"),
                        "previous_session_summary": previous_session_summary or None,
                        "previous_session_lookup_status": previous_session_lookup_status,
                    }
                },
            )
            await session.commit()

            stage_progress = {
                NovelistStage.PLANNING: (0.25, "Planning chapter parts"),
                NovelistStage.WRITING: (0.55, "Drafting chapter parts"),
                NovelistStage.CRITIC: (0.75, "Critic review"),
                NovelistStage.APPLY_CRITIC: (0.9, "Applying critic revisions"),
                NovelistStage.MERGING: (0.95, "Merging final chapter"),
            }

            async def stage_callback(
                stage: NovelistStage, payload: dict[str, Any] | None = None
            ) -> None:
                payload = payload or {}
                update_kwargs: dict[str, Any] = {"stage": stage}
                if "artifacts" in payload:
                    update_kwargs["artifacts"] = payload["artifacts"]
                if "draft_text" in payload:
                    update_kwargs["draft_text"] = payload["draft_text"]
                if "critic_notes" in payload:
                    critic_notes = payload["critic_notes"]
                    if critic_notes is None:
                        update_kwargs["critic_notes"] = None
                    elif isinstance(critic_notes, str):
                        update_kwargs["critic_notes"] = critic_notes
                    else:
                        update_kwargs["critic_notes"] = json.dumps(
                            critic_notes, ensure_ascii=True
                        )
                await repo.update_status(run_id, **update_kwargs)
                await session.commit()
                progress_info = stage_progress.get(stage)
                if progress_info:
                    progress_value, progress_status = progress_info
                    await update_job_progress(
                        job_id, progress_value, {"status": progress_status}
                    )

            result = await orchestrator.execute(
                agent=novelist_agent,
                payload=NovelistRunCreate.model_validate(request_payload_enriched),
                conversation_id=f"novelist_run:{run_id}",
                stage_callback=stage_callback,
            )
            result_artifacts = result.get("artifacts")
            if not isinstance(result_artifacts, dict):
                result_artifacts = {}
            inputs_artifact = result_artifacts.get("inputs")
            if not isinstance(inputs_artifact, dict):
                inputs_artifact = {}
            inputs_artifact.setdefault(
                "previous_session_id", request_payload.get("previous_session_id")
            )
            inputs_artifact.setdefault(
                "previous_session_summary", previous_session_summary or None
            )
            inputs_artifact["previous_session_lookup_status"] = previous_session_lookup_status
            result_artifacts["inputs"] = inputs_artifact
            result["artifacts"] = result_artifacts

            await repo.update_status(
                run_id,
                status=NovelistRunStatus.COMPLETED,
                stage=NovelistStage.DONE,
                artifacts=result_artifacts,
                draft_text=result.get("draft_text"),
                critic_notes=result.get("critic_notes"),
            )
            await session.commit()
            await update_job_progress(job_id, 1.0, {"status": "completed"})
            await mark_job_done(job_id, {"run_id": run_id, "status": "completed"})
            return result
        except Exception as exc:
            logger.error("Novelist run %s failed: %s", run_id, exc, exc_info=True)
            await session.rollback()
            await repo.update_status(
                run_id,
                status=NovelistRunStatus.FAILED,
                error_message=str(exc),
            )
            await session.commit()
            await mark_job_failed(job_id, str(exc))
            raise
        finally:
            await llm_client.aclose()


@celery_app.task(name="novelist.generate_draft")
def generate_draft(
    run_id: str,
    request_payload: dict[str, Any],
    *,
    author_type: str = "user",
    author_id: str = "system",
) -> dict[str, Any]:
    """Entry-point Celery task for novelist draft generation (step 1)."""
    description = f"Novelist draft generation for run {run_id}"
    job_id = run_async(
        create_background_job(
            author_type=AuthorType(author_type),
            author_id=author_id,
            job_type=JobType.NOVELIST_DRAFT,
            description=description,
            celery_task_id=generate_draft.request.id,
            details={"run_id": run_id},
        )
    )

    try:
        run_async(mark_job_running(job_id))

        async def _attach() -> None:
            async with AsyncSessionMaker() as session:
                repo = NovelistRepository(session)
                await repo.attach_background_job(run_id, job_id)
                await session.commit()

        run_async(_attach())
        result = run_async(
            _execute_run(run_id=run_id, request_payload=request_payload, job_id=job_id)
        )
        return {"job_id": job_id, "status": "success", "run_id": run_id, **result}
    except Exception as exc:
        run_async(mark_job_failed(job_id, str(exc)))
        raise
