"""Celery entry point for the single Novelist v3 pipeline."""

from __future__ import annotations

import logging
from typing import Any

from app.celery_app import celery_app
from app.core.config_store import get_settings, is_shreckllm_configured
from app.db.session import AsyncSessionMaker
from app.graph.neo4j import get_driver
from app.integrations.llm.model_policy import ModelPolicy
from app.integrations.llm.shreckllm_client import ShreckLLMClient
from app.jobs.novelist.orchestrator import NovelistOrchestrator
from app.models.background_job import AuthorType, JobType
from app.models.novelist import NovelistRunStatus, NovelistStage
from app.repositories.agent_repository import AgentRepository
from app.repositories.novelist_repository import NovelistRepository
from app.schemas.novelist import NovelistRunCreate
from app.utils.async_helpers import run_async
from app.utils.job_tracking import create_background_job, mark_job_done, mark_job_failed, mark_job_running, update_job_progress

logger = logging.getLogger(__name__)


def _clean(value: Any) -> str:
    return value.strip() if isinstance(value, str) else ""


async def _resolve_previous_session_text(session_id: str | None) -> tuple[str, str]:
    """Legacy continuity text lookup; it is lower authority than the new ledger."""
    if not _clean(session_id):
        return "", "missing_id"
    try:
        settings = get_settings()
        driver = get_driver()
        async with driver.session(database=settings.neo4j_database) as graph_session:
            result = await graph_session.run("MATCH (node:EntityInstance {entity_instance_id: $id}) RETURN node.text AS text, node.autogenerated_text AS autogenerated_text LIMIT 1", id=session_id)
            row = await result.single()
        if row:
            return _clean(row.get("text")) or _clean(row.get("autogenerated_text")), "matched_entity_instance_id"
    except Exception:
        logger.warning("Could not resolve Novelist continuity text", exc_info=True)
        return "", "lookup_error"
    return "", "no_text_found"


async def _previous_ledger(repo: NovelistRepository, run_id: str | None) -> dict[str, Any] | None:
    if not _clean(run_id):
        return None
    run = await repo.get_run(str(run_id))
    if not run or run.status != NovelistRunStatus.COMPLETED:
        return None
    artifacts = run.artifacts if isinstance(run.artifacts, dict) else {}
    ledger = artifacts.get("evidence_ledger")
    return ledger if isinstance(ledger, dict) and artifacts.get("pipeline_version") == "v3" else None


def _json_safe(value: Any) -> Any:
    if hasattr(value, "model_dump"):
        return _json_safe(value.model_dump())
    if isinstance(value, dict):
        return {str(key): _json_safe(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_json_safe(item) for item in value]
    return value


async def _execute_run(*, run_id: str, request_payload: dict[str, Any], job_id: int) -> dict[str, Any]:
    settings = get_settings()
    if not is_shreckllm_configured(settings):
        raise RuntimeError("shreckLLM is not configured")
    async with AsyncSessionMaker() as session:
        repo = NovelistRepository(session)
        run = await repo.get_run(run_id)
        if not run:
            raise ValueError("Novelist run not found")
        agent = await AgentRepository(session).get_by_id(run.agent_id)
        if not agent:
            raise ValueError("Novelist agent not found")
        client = ShreckLLMClient(base_url=settings.shreckllm_base_url, timeout=settings.shreckllm_request_timeout_s, max_retries=settings.shreckllm_max_retries)
        try:
            policy = ModelPolicy(default_model=settings.model_novelist_writer)
            setattr(policy, "model_novelist_analysis", settings.model_novelist_analysis)
            setattr(policy, "model_novelist_writer", settings.model_novelist_writer)
            prior_text, prior_status = await _resolve_previous_session_text(request_payload.get("previous_session_id"))
            enriched = dict(request_payload)
            if prior_text:
                enriched["previous_session_text"] = prior_text
            payload = NovelistRunCreate.model_validate(enriched)
            object.__setattr__(payload, "previous_ledger", await _previous_ledger(repo, payload.previous_novelist_run_id))
            await repo.update_status(run_id, status=NovelistRunStatus.RUNNING, stage=NovelistStage.INGEST)
            await session.commit()
            await update_job_progress(job_id, 0.08, {"status": "interpreting source"})
            stages = {
                NovelistStage.INTERPRETATION: (0.22, "building evidence ledger"), NovelistStage.CONTINUITY: (0.32, "loading continuity"),
                NovelistStage.BLOCK_PLANNING: (0.40, "planning writing blocks"), NovelistStage.WRITING: (0.65, "writing chapter blocks"),
                NovelistStage.QUALITY_GATE: (0.76, "checking prose structure"), NovelistStage.MERGING: (0.82, "merging chapter"),
                NovelistStage.FIDELITY: (0.90, "verifying fidelity"), NovelistStage.CORRECTION: (0.95, "correcting affected blocks"),
            }
            async def callback(stage: NovelistStage, data: dict[str, Any]) -> None:
                await repo.update_status(run_id, stage=stage, artifacts=_json_safe(data.get("artifacts", {})), draft_text=data.get("draft_text"))
                await session.commit()
                progress, message = stages.get(stage, (0.1, str(stage.value)))
                await update_job_progress(job_id, progress, {"status": message, "block_count": data.get("block_count"), "completed_blocks": data.get("completed_blocks")})
            result = await NovelistOrchestrator(llm_client=client, model_policy=policy).execute(agent=agent, payload=payload, conversation_id=f"novelist_run:{run_id}", stage_callback=callback)
            artifacts = result["artifacts"]
            artifacts.setdefault("inputs", {})["previous_session_lookup_status"] = prior_status
            artifacts["llm_usage_summary"] = client.get_usage_summary()
            await repo.update_status(run_id, status=NovelistRunStatus.COMPLETED, stage=NovelistStage.DONE, artifacts=_json_safe(artifacts), draft_text=result["final_text_html"], critic_notes=None)
            await session.commit()
            await update_job_progress(job_id, 1.0, {"status": "completed", "pipeline_version": "v3"})
            await mark_job_done(job_id, {"run_id": run_id, "status": "completed", "pipeline_version": "v3"})
            return result
        except Exception as exc:
            await session.rollback()
            await repo.update_status(run_id, status=NovelistRunStatus.FAILED, stage=NovelistStage.DONE, error_message=str(exc))
            await session.commit()
            await mark_job_failed(job_id, str(exc))
            raise
        finally:
            await client.aclose()


@celery_app.task(name="novelist.generate_draft")
def generate_draft(run_id: str, request_payload: dict[str, Any], *, author_type: str = "user", author_id: str | None = None) -> dict[str, Any]:
    async def runner() -> dict[str, Any]:
        job = await create_background_job(job_type=JobType.NOVELIST_DRAFT, author_type=AuthorType(author_type), author_id=author_id or "system", description=f"Novelist v3 draft generation for run {run_id}")
        async with AsyncSessionMaker() as session:
            await NovelistRepository(session).attach_background_job(run_id, job.id)
            await session.commit()
        await mark_job_running(job.id)
        return await _execute_run(run_id=run_id, request_payload=request_payload, job_id=job.id)
    return run_async(runner())
