"""CRUD operations for the novelist agent."""

from __future__ import annotations

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.model_agent import Agent
from app.crud.crud_agent import ensure_personality_prompts
from app.agentic_ai.agentic_worker_utils import split_into_arcs
from app.agentic_ai.agentic_worker_llm import chat_completion_worker


async def create_novel(
    session: AsyncSession,
    agent: Agent,
    text: str,
    instructions: str,
    previous_page_id: int | None = None,
    inspiration_page_id: int | None = None,
    progress_cb=None,
) -> str:
    """Generate a novelized summary from transcript and world context."""

    personalities = [
        p.strip() for p in (agent.personality or "helpful NPC").split(",") if p.strip()
    ]
    all_tones = await ensure_personality_prompts(personalities)
    tone = "\n".join(all_tones.get(p, "") for p in personalities if all_tones.get(p))
    tone = tone or "You are a creative, helpful fantasy novelist."

    previous_summary = ""
    if previous_page_id:
        from app.crud import crud_page

        prev_page = await crud_page.get_page(session, previous_page_id)
        if prev_page:
            prev_text = (
                (prev_page.content or "")
                + "\n"
                + (prev_page.autogenerated_content or "")
                + "\n"
                + (prev_page.keyevents or "")
                + "\n"
                + (prev_page.relationships or "")
            )
            summary_prompt = (
                "Summarize the following previous session notes in a short paragraph highlighting important characters, actions and dialogues.\n\n"
                f"{prev_text}"
            )
            previous_summary = await chat_completion_worker(
                system_prompt="You are a helpful editor summarizing an RPG session.",
                user_prompt=summary_prompt,
                temperature=0.3,
                max_tokens=512,
            )

    previous_session_text = (
        f"Happened in the previous session:\n{previous_summary}\n"
        if previous_summary
        else ""
    )

    inspiration_style = ""
    if inspiration_page_id:
        from app.crud import crud_page

        insp_page = await crud_page.get_page(session, inspiration_page_id)
        if insp_page:
            insp_text = (
                (insp_page.autogenerated_content or "")
                + "\n"
                + (insp_page.content or "")
            )
            style_prompt = (
                "Analyze the writing style of the following text. Describe tone, pacing, vocabulary, and narrative perspective in 3-5 bullet points.\n\n"
                f"{insp_text}"
            )
            inspiration_style = await chat_completion_worker(
                system_prompt="You are a literary style analyst.",
                user_prompt=style_prompt,
                temperature=0.3,
                max_tokens=256,
            )

    arcs = split_into_arcs(text, min_words_per_arc=1000, max_arcs=5)
    arc_novels: list[str] = []
    arc_critic_notes: list[str] = []

    for idx, arc_text in enumerate(arcs):
        if progress_cb:
            progress_cb(idx, len(arcs) + 2)

        novel_prompt = (
            "You are a talented fantasy novelist. Rewrite the following RPG transcript arc as a **brief, engaging, and flowing novel segment** (max 1000 words).\n"
            + (
                f"Writing style to emulate:\n{inspiration_style}\n"
                if inspiration_style
                else ""
            )
            + f"{previous_session_text}\n"
            + "Instructions:\n"
            + f"{instructions}\n"
            + "- Write your answer in the same language as the transcript below.\n"
            + "- Format dialogue as in a novel (for example: — Gryx: What's happening here?).\n"
            + "- Keep it concise, focus on main events, character emotions, and dramatic transitions.\n"
            + "- Take in consideration what happened in the previous session! Make continuity with scenes, dialogues, events, and characters.\n"
            + "- You may add brief invented narration, dialogue, or transitions for flow, as long as they fit the characters and events.\n"
            + "- Do NOT repeat or invent entire scenes; only fill gaps for readability.\n"
            + "- Give the segment a clear beginning, middle, and end.\n"
            + "Transcript:\n"
            + f"{arc_text}\n"
        )
        novel_arc = await chat_completion_worker(
            system_prompt=tone,
            user_prompt=novel_prompt,
        )
        arc_novels.append(novel_arc)

        critic_system_prompt = "You are an experienced, constructive but critical fantasy literature reviewer."
        critic_prompt = (
            "You are a fantasy literary critic. Read this novelized arc and the context. Give bullet-point feedback on:\n"
            + f"- story flow,\n"
            + f"- character consistency,\n"
            + f"- world accuracy,\n"
            + f" - narrative immersion.\n"
            + f" - history continuity based on the previous sessions.\n"
            + f" Point out anything that contradicts the world, characters, or instructions. Suggest brief improvements if needed.\n"
            + f"{previous_session_text}\n"
            + " Novelized arc:\n"
            + f"{novel_arc}\n"
        )
        critic_notes = await chat_completion_worker(
            system_prompt=critic_system_prompt,
            user_prompt=critic_prompt,
            temperature=0.2,
            max_tokens=512,
        )
        arc_critic_notes.append(critic_notes)

    if progress_cb:
        progress_cb(len(arcs) + 1, len(arcs) + 2)

    arc_novels_joined = "\n\n".join(arc_novels)
    arc_critic_notes_joined = "\n\n".join(arc_critic_notes)

    final_writer_prompt = (
        "You are a talented fantasy novelist. Combine and polish the following arcs into a single, seamless, concise fantasy novel chapter.\n"
        + (
            f"Writing style to emulate:\n{inspiration_style}\n"
            if inspiration_style
            else ""
        )
        + f"{previous_session_text}\n"
        + f"Critic notes for each arc:\n"
        + f"{arc_critic_notes_joined}\n"
        + f"Novelized arcs:\n"
        + f"{arc_novels_joined}\n"
        + " Instructions:\n"
        + "- Incorporate important world details where appropriate.\n"
        + "- Apply the critic's suggestions to improve narrative flow, character depth, and world consistency.\n"
        + "- You may invent brief dialogue lines or transitions if needed for story cohesion, as long as they do not contradict the story so far.\n"
        + "- Take in consideration what happened in the previous session! Make continuity with scenes, dialogues, events, and characters.\n"
        + "- The entire output must be **no more than 4000 words**.\n"
        + "- Eliminate repetition, awkward transitions, or extraneous detail.\n"
        + " - Make the final chapter emotionally engaging and easy to read.\n"
        + "- Format the output using valid HTML: wrap each paragraph in <p>. Use <h2>/<h3> for titles if relevant. Format dialogue as you would in a novel, with each line in its own <p> or <blockquote> if appropriate.\n"
    )

    draft = await chat_completion_worker(
        system_prompt=tone,
        user_prompt=final_writer_prompt,
        max_tokens=4000,
    )

    if previous_summary:
        draft = (
            f"<h3>In the previous session</h3>\n<p>{previous_summary}</p>\n"
            + draft.strip()
        )

    if progress_cb:
        progress_cb(len(arcs) + 2, len(arcs) + 2)

    return draft.strip()
