#!/usr/bin/env python
"""
Example script demonstrating the Architect V2 pipeline.

This script shows how to use the new V2 pipeline with example data.
"""
import asyncio
import json
from datetime import datetime

from app.jobs.architect.architect_v2 import ArchitectOrchestratorV2
from app.jobs.elder.schemas import RetrievedChunk
from app.schemas.ontology_instance import (
    OntologyInstanceEntityRead,
    OntologyInstanceRead,
)


class MockLLM:
    """Mock LLM client that returns predefined responses."""

    def __init__(self):
        self.call_count = 0

    async def chat(self, *args, **kwargs):
        """Return mock responses based on the prompt."""
        messages = kwargs.get("messages", [])
        prompt = messages[0]["content"] if messages else ""

        if "reconciling" in prompt.lower():
            # Reconciliation response
            return json.dumps(
                {
                    "existing": [
                        {
                            "proposed_name": "Camarilla",
                            "matched_node_id": "org_101",
                            "ontology": "Organization",
                        }
                    ],
                    "new": [
                        {"name": "Baron Jackie", "ontology": "Character"},
                        {"name": "The Elysium", "ontology": "Location"},
                    ],
                }
            )
        else:
            # Chunk extraction response
            self.call_count += 1
            if self.call_count == 1:
                return json.dumps(
                    {
                        "entities": [
                            {
                                "name": "Baron Jackie",
                                "ontology": "Character",
                                "confidence": 0.85,
                                "why": "Main character organizing the meeting",
                            },
                            {
                                "name": "Camarilla",
                                "ontology": "Organization",
                                "confidence": 0.78,
                                "why": "Power group mentioned as antagonist",
                            },
                        ]
                    }
                )
            elif self.call_count == 2:
                return json.dumps(
                    {
                        "entities": [
                            {
                                "name": "The Elysium",
                                "ontology": "Location",
                                "confidence": 0.72,
                                "why": "Meeting location mentioned",
                            },
                            {
                                "name": "Baron Jackie",
                                "ontology": "Character",
                                "confidence": 0.88,
                                "why": "Referenced again as host",
                            },
                        ]
                    }
                )
            else:
                return json.dumps({"entities": []})


class MockRetriever:
    """Mock retriever that returns predefined existing entities."""

    async def search_aliases(self, **kwargs):
        """Return mock existing entities."""
        return [
            RetrievedChunk(
                node_id="org_101",
                node_label="Camarilla",
                node_alias="Camarilla",
                instance_id="instance-1",
                text="",
                score=0.95,
                confidence_pct=95.0,
                source="Organization",
            ),
            RetrievedChunk(
                node_id="char_042",
                node_label="Prince Marcus",
                node_alias="Prince Marcus",
                instance_id="instance-2",
                text="",
                score=0.88,
                confidence_pct=88.0,
                source="Character",
            ),
        ]


class MockPolicy:
    """Mock model policy."""

    def get_model(self, task):
        return "gpt-4"


async def main():
    """Run the example pipeline."""
    print("=" * 80)
    print("Architect V2 Pipeline - Example Execution")
    print("=" * 80)
    print()

    # Create mock instance with story text
    now = datetime.utcnow()
    entities = [
        OntologyInstanceEntityRead(
            entity_instance_id="story-1",
            definition_id=1,
            alias="Chapter 1",
            text="""
            Baron Jackie convened the meeting at the Elysium. Representatives from
            various domains gathered to discuss the rising Camarilla threat. The
            ancient laws of hospitality protected them all, but tension filled the air.
            """,
            text_linked=None,
            node_avatar_url=None,
            autogenerated_text="",
            autogenerated_text_linked=None,
            created_date=now,
            updated_date=now,
            last_updated_date=now,
            author_type="human",
            author_id="user-1",
        ),
        OntologyInstanceEntityRead(
            entity_instance_id="story-2",
            definition_id=1,
            alias="Chapter 2",
            text="""
            As the host, Baron Jackie opened the discussion. She explained the recent
            Camarilla incursions into their territory and called for a unified response.
            The Elysium's neutral ground provided safety, but action was needed.
            """,
            text_linked=None,
            node_avatar_url=None,
            autogenerated_text="",
            autogenerated_text_linked=None,
            created_date=now,
            updated_date=now,
            last_updated_date=now,
            author_type="human",
            author_id="user-1",
        ),
    ]

    instance = OntologyInstanceRead(
        instance_id="game-001",
        ontology_id=42,
        name="Vampire Chronicle",
        entities=entities,
        created_date=now,
        updated_date=now,
        created_at=now,
        updated_at=now,
    )

    # Define ontology
    entity_definitions = [
        {
            "id": 1,
            "name": "Character",
            "description": "People, mortals, vampires, and other characters",
        },
        {
            "id": 2,
            "name": "Location",
            "description": "Cities, places, domains, and territories",
        },
        {
            "id": 3,
            "name": "Organization",
            "description": "Coteries, clans, sects, and power groups",
        },
    ]

    # Create orchestrator
    orchestrator = ArchitectOrchestratorV2(
        llm_client=MockLLM(),
        model_policy=MockPolicy(),
        graph_retriever=MockRetriever(),
        chunk_size=100,  # Small chunks for example
        chunk_overlap=20,
    )

    print("Running pipeline...")
    print()

    # Execute pipeline
    result = await orchestrator.analyse(
        agent_ontology_ids=[42],
        ontology_instance=instance,
        entity_definitions=entity_definitions,
    )

    # Display results
    print("Pipeline completed!")
    print(f"Version: {result.get('pipeline_version')}")
    print(f"Chunks processed: {result.get('chunk_count')}")
    print(f"Unique entities found: {result.get('deduped_count')}")
    print(f"Existing entities: {result.get('existing_count')}")
    print(f"New entities: {result.get('new_count')}")
    print()

    print("-" * 80)
    print("PROPOSALS")
    print("-" * 80)
    print()

    for i, proposal in enumerate(result.get("proposals", []), 1):
        print(f"{i}. {proposal.get('alias', 'N/A')}")
        print(f"   Type: {proposal.get('proposal_type')}")
        print(
            f"   Status: {proposal.get('proposal_metadata', {}).get('resolved_status')}"
        )
        print(
            f"   Node ID: {proposal.get('entity_instance_id') or proposal.get('proposal_metadata', {}).get('resolved_node_id') or 'N/A'}"
        )
        print(f"   Confidence: {proposal.get('confidence', 0):.2f}")
        print(f"   Justification: {proposal.get('justification', 'N/A')[:80]}...")
        print()

    print("-" * 80)
    print("JSON OUTPUT (for frontend)")
    print("-" * 80)
    print()

    # Format as frontend-friendly JSON
    frontend_json = {
        "entities": [
            {
                "name": p.get("alias"),
                "ontology": p.get("proposal_metadata", {}).get("ontology_name"),
                "confidence": p.get("confidence"),
                "why": p.get("justification"),
                "resolved_status": p.get("proposal_metadata", {}).get(
                    "resolved_status"
                ),
                "resolved_node_id": p.get("entity_instance_id")
                or p.get("proposal_metadata", {}).get("resolved_node_id"),
                "mention_count": p.get("proposal_metadata", {}).get("mention_count"),
                "chunk_indices": p.get("proposal_metadata", {}).get("chunk_indices"),
            }
            for p in result.get("proposals", [])
        ]
    }

    print(json.dumps(frontend_json, indent=2))
    print()

    print("=" * 80)
    print("Example completed successfully!")
    print("=" * 80)


if __name__ == "__main__":
    asyncio.run(main())
