"""Schemas for GraphRAG API."""

from typing import Literal

from pydantic import BaseModel, Field


class EmbedNodeRequest(BaseModel):
    """Request to embed a single node."""

    node_id: str = Field(..., description="Entity instance ID")
    ontology_id: int | None = Field(None, description="Ontology ID filter")


class EmbedNodeResponse(BaseModel):
    """Response from embedding a node."""

    node_id: str
    context_text: str
    embedding_model: str
    embedding_dim: int


class EmbedOntologyRequest(BaseModel):
    """Request to embed all nodes in an ontology."""

    ontology_id: int = Field(..., description="Ontology ID")
    batch_size: int = Field(50, description="Batch size for processing", ge=1, le=100)


class EmbedOntologyResponse(BaseModel):
    """Response from embedding an ontology."""

    ontology_id: int
    nodes_processed: int
    nodes_failed: int


class ResetOntologyEmbeddingsRequest(BaseModel):
    """Request to remove embeddings for an ontology."""

    ontology_id: int = Field(..., description="Ontology ID to reset")


class ResetOntologyEmbeddingsResponse(BaseModel):
    """Response after removing embeddings for an ontology."""

    ontology_id: int
    nodes_reset: int
    orphans_deleted: int
    chunks_deleted: int


class SemanticSearchRequest(BaseModel):
    """Request for semantic search."""

    query: str = Field(..., description="Search query text", min_length=1)
    ontology_id: int | None = Field(None, description="Filter by ontology ID")
    k: int = Field(10, description="Number of results", ge=1, le=50)
    score_threshold: float = Field(0.0, description="Minimum score", ge=0.0, le=1.0)
    include_neighbors: bool = Field(True, description="Include neighbor nodes")
    neighbor_limit: int = Field(10, description="Max neighbors per node", ge=1, le=50)
    node_scope: Literal["everything", "entity", "scene", "milestone", "mixed"] = Field(
        "everything",
        description="Limit retrieval to entity, scene, milestone nodes, or mixed",
    )
    candidate_limit: int = Field(
        40,
        description="Max chunk candidates before node-level reranking",
        ge=5,
        le=200,
    )
    rerank_limit: int = Field(
        20,
        description="Max node candidates after reranking before final top-k",
        ge=1,
        le=100,
    )


class NodeResult(BaseModel):
    """Single node result from search."""

    node_id: str
    name: str
    labels: list[str]
    score: float
    context_text: str | None = None
    text: str | None = None
    autogenerated_text: str | None = None
    ontology_id: int | None = None
    neighbors: list[dict] | None = None
    chunk_score: float | None = None
    node_score: float | None = None
    importance_index: float | None = None
    matched_chunk_count: int | None = None
    score_breakdown: dict[str, float] | None = None
    graph_boost: float | None = None
    evidence_bundle: dict | None = None


class SemanticSearchResponse(BaseModel):
    """Response from semantic search."""

    query: str
    results: list[NodeResult]
    total: int
    ontology_id: int | None
    evidence_bundles: list[dict] = Field(default_factory=list)


class ContextRequest(BaseModel):
    """Request for LLM context."""

    query: str = Field(..., description="Search query", min_length=1)
    ontology_id: int | None = Field(None, description="Filter by ontology")
    k: int = Field(5, description="Number of results", ge=1, le=20)
    score_threshold: float = Field(0.5, description="Minimum score", ge=0.0, le=1.0)
    node_scope: Literal["everything", "entity", "scene", "milestone", "mixed"] = Field(
        "everything",
        description="Limit retrieval to entity, scene, milestone nodes, or mixed",
    )


class ContextResponse(BaseModel):
    """Response with formatted context."""

    query: str
    context: str
    ontology_id: int | None


class IndexStatusResponse(BaseModel):
    """Response for index status."""

    index_name: str
    exists: bool
    embedding_model: str
    embedding_dim: int


class ClearGraphResponse(BaseModel):
    """Response after clearing the Neo4j graph."""

    message: str
    nodes_deleted: int
    relationships_deleted: int
