from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator, model_validator
from pydantic import ConfigDict

from app.models.ontology import AuthorType


class OntologyInstancePropertyValue(BaseModel):
    model_config = ConfigDict(extra="ignore")
    definition_id: int
    value: Any


class OntologyInstanceRelationshipCreate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    definition_id: int
    target_alias: str | None = None
    target_entity_instance_id: str | None = None
    data: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_target(
        cls, values: "OntologyInstanceRelationshipCreate"
    ) -> "OntologyInstanceRelationshipCreate":
        alias = values.target_alias.strip() if values.target_alias else None
        target_id = (
            values.target_entity_instance_id.strip()
            if values.target_entity_instance_id
            else None
        )
        if bool(alias) == bool(target_id):
            raise ValueError(
                "Provide exactly one of target_alias or target_entity_instance_id"
            )
        if alias:
            values.target_alias = alias
        else:
            values.target_alias = None
        if target_id:
            values.target_entity_instance_id = target_id
        else:
            values.target_entity_instance_id = None
        return values


class OntologyInstanceRelationshipRead(BaseModel):
    model_config = ConfigDict(extra="ignore")
    relationship_instance_id: str
    definition_id: int
    target_entity_id: str
    destiny_entity_definition_id: int | None = None
    data: dict[str, Any] = Field(default_factory=dict)


class OntologyInstanceEntityCreate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    definition_id: int
    alias: str
    text: str | None = None
    node_avatar_url: str | None = None
    autogenerated_text: str | None = None
    created_date: datetime | None = None
    last_updated_date: datetime | None = None
    author_type: AuthorType
    author_id: str
    properties: list[OntologyInstancePropertyValue] = Field(default_factory=list)
    relationships: list[OntologyInstanceRelationshipCreate] = Field(
        default_factory=list
    )

    @field_validator("alias", "author_id", mode="before")
    def validate_non_empty(cls, value: str, info):
        if value is None:
            raise ValueError(f"{info.field_name} cannot be empty")
        value = value.strip()
        if not value:
            raise ValueError(f"{info.field_name} cannot be empty")
        return value


class OntologyInstanceEntityRead(BaseModel):
    model_config = ConfigDict(extra="ignore")
    entity_instance_id: str
    definition_id: int
    alias: str | None = None
    text: str
    text_linked: str | None = None
    node_avatar_url: str | None = None
    autogenerated_text: str | None = None
    autogenerated_text_linked: str | None = None
    created_date: datetime
    last_updated_date: datetime
    author_type: AuthorType
    author_id: str
    properties: list[OntologyInstancePropertyValue] = Field(default_factory=list)
    relationships: list[OntologyInstanceRelationshipRead] = Field(default_factory=list)


EventRelationType = Literal["BEFORE", "AFTER", "DERIVED_FROM", "RELATED_TO"]


class EventRelation(BaseModel):
    model_config = ConfigDict(extra="ignore")
    relation_type: EventRelationType
    target_event_id: str

    @field_validator("target_event_id", mode="before")
    def validate_target_event_id(cls, value: str) -> str:
        if value is None:
            raise ValueError("target_event_id cannot be empty")
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("target_event_id cannot be empty")
        return cleaned


class TimelineEventBase(BaseModel):
    model_config = ConfigDict(extra="ignore")
    title: str
    description: str
    source: str | None = None
    source_entity_id: str | None = None
    involves_entity_ids: list[str] = Field(default_factory=list)
    relations: list[EventRelation] = Field(default_factory=list)
    # Internal transitional fields (excluded from API serialization)
    created_from_instance_id: str | None = Field(default=None, exclude=True)
    created_from_entity_id: str | None = Field(default=None, exclude=True)
    related_instance_ids: list[str] = Field(default_factory=list, exclude=True)
    related_entity_ids: list[str] = Field(default_factory=list, exclude=True)
    before_event_id: str | None = Field(default=None, exclude=True)
    after_event_id: str | None = Field(default=None, exclude=True)

    @field_validator("title", "description", mode="before")
    def validate_text(cls, value: str, info):
        if value is None:
            raise ValueError(f"{info.field_name} cannot be empty")
        value = value.strip()
        if not value:
            raise ValueError(f"{info.field_name} cannot be empty")
        return value


class TimelineEventCreate(TimelineEventBase):
    event_id: str | None = None
    timeline_event_id: str | None = Field(default=None, exclude=True)


class TimelineEventUpdate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    title: str | None = None
    description: str | None = None
    source: str | None = None
    source_entity_id: str | None = None
    involves_entity_ids: list[str] | None = None
    relations: list[EventRelation] | None = None
    created_from_instance_id: str | None = Field(default=None, exclude=True)
    created_from_entity_id: str | None = Field(default=None, exclude=True)
    related_instance_ids: list[str] | None = Field(default=None, exclude=True)
    related_entity_ids: list[str] | None = Field(default=None, exclude=True)
    before_event_id: str | None = Field(default=None, exclude=True)
    after_event_id: str | None = Field(default=None, exclude=True)


class TimelineEventRead(TimelineEventBase):
    event_id: str
    timeline_event_id: str | None = Field(default=None, exclude=True)
    instance_id: str
    ontology_id: int
    created_at: datetime
    updated_at: datetime


class OntologyInstanceBase(BaseModel):
    model_config = ConfigDict(extra="ignore")
    name: str


class OntologyInstanceCreate(OntologyInstanceBase):
    model_config = ConfigDict(extra="ignore")
    ontology_id: int
    entities: list[OntologyInstanceEntityCreate]
    events: list[TimelineEventCreate] = Field(default_factory=list)


class OntologyInstanceUpdate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    name: str | None = None
    entities: list[OntologyInstanceEntityCreate] | None = None
    events: list[TimelineEventCreate] | None = None


class OntologyInstanceRead(OntologyInstanceBase):
    model_config = ConfigDict(extra="ignore")
    instance_id: str
    ontology_id: int
    created_at: datetime
    updated_at: datetime
    entities: list[OntologyInstanceEntityRead]
    events: list[TimelineEventRead] = Field(default_factory=list)


class OntologyInstanceSummary(BaseModel):
    model_config = ConfigDict(extra="ignore")
    instance_id: str
    ontology_id: int
    name: str
    created_at: datetime
    updated_at: datetime
    primary_alias: str | None = None
    aliases: list[str] = Field(default_factory=list)
    avatar_url: str | None = None
    entity_count: int = 0


class OntologyInstanceSummaryPage(BaseModel):
    model_config = ConfigDict(extra="ignore")
    total: int
    skip: int
    limit: int
    results: list[OntologyInstanceSummary] = Field(default_factory=list)


class OntologyInstanceCountResponse(BaseModel):
    model_config = ConfigDict(extra="ignore")
    total: int


class OntologyInstanceEntityTypeClearRequest(BaseModel):
    model_config = ConfigDict(extra="ignore")
    ontology_id: int
    entity_definition_ids: list[int] = Field(default_factory=list)
    entity_type_names: list[str] = Field(default_factory=list)


class OntologyInstanceEntityTypeClearJobResponse(BaseModel):
    model_config = ConfigDict(extra="ignore")
    message: str
    kind: str
    job_id: int
    status: str
    monitor_url: str


class OntologyTimelineEventsClearRequest(BaseModel):
    model_config = ConfigDict(extra="ignore")
    ontology_id: int


class OntologyTimelineEventsClearJobResponse(BaseModel):
    model_config = ConfigDict(extra="ignore")
    message: str
    kind: str
    job_id: int
    status: str
    monitor_url: str


class OntologyInstanceSearchHit(BaseModel):
    model_config = ConfigDict(extra="ignore")
    instance: OntologyInstanceRead
    ontology_name: str | None = None
    world_name: str | None = None
    match_reason: str | None = None
    matched_aliases: list[str] = Field(default_factory=list)
    snippet: str | None = None
    score: float | None = None
    source_node_id: str | None = None
    source_labels: list[str] = Field(default_factory=list)


class OntologyInstanceSearchResponse(BaseModel):
    model_config = ConfigDict(extra="ignore")
    query: str
    ontology_id: int | None = None
    ontology_name: str | None = None
    world_name: str | None = None
    direct_results: list[OntologyInstanceSearchHit] = Field(default_factory=list)
    deep_results: list[OntologyInstanceSearchHit] = Field(default_factory=list)
