from __future__ import annotations

from datetime import datetime
import re
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator, model_validator
from pydantic import ConfigDict

from app.models.ontology import AuthorType


class OntologyInstancePropertyValue(BaseModel):
    model_config = ConfigDict(extra="ignore")
    definition_id: int
    value: Any


class OntologyInstanceRelationshipCreate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    definition_id: int
    target_alias: str | None = None
    target_entity_instance_id: str | None = None
    data: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_target(self) -> "OntologyInstanceRelationshipCreate":
        alias = self.target_alias.strip() if self.target_alias else None
        target_id = (
            self.target_entity_instance_id.strip()
            if self.target_entity_instance_id
            else None
        )
        if bool(alias) == bool(target_id):
            raise ValueError(
                "Provide exactly one of target_alias or target_entity_instance_id"
            )
        if alias:
            self.target_alias = alias
        else:
            self.target_alias = None
        if target_id:
            self.target_entity_instance_id = target_id
        else:
            self.target_entity_instance_id = None
        return self


class OntologyInstanceRelationshipRead(BaseModel):
    model_config = ConfigDict(extra="ignore")
    relationship_instance_id: str
    definition_id: int
    target_entity_id: str
    destiny_entity_definition_id: int | None = None
    data: dict[str, Any] = Field(default_factory=dict)


class OntologyInstanceEntityCreate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    entity_instance_id: str | None = None
    definition_id: int
    alias: str
    text: str | None = None
    node_avatar_url: str | None = None
    autogenerated_text: str | None = None
    created_date: datetime | None = None
    last_updated_date: datetime | None = None
    author_type: AuthorType
    author_id: str
    properties: list[OntologyInstancePropertyValue] = Field(default_factory=list)
    relationships: list[OntologyInstanceRelationshipCreate] = Field(
        default_factory=list
    )

    @field_validator("alias", "author_id", mode="before")
    def validate_non_empty(cls, value: str, info):
        if value is None:
            raise ValueError(f"{info.field_name} cannot be empty")
        value = value.strip()
        if not value:
            raise ValueError(f"{info.field_name} cannot be empty")
        return value

    @field_validator("entity_instance_id", mode="before")
    def validate_optional_entity_instance_id(cls, value: str | None) -> str | None:
        if value is None:
            return None
        cleaned = str(value).strip()
        if not cleaned:
            return None
        return cleaned


class OntologyInstanceEntityRead(BaseModel):
    model_config = ConfigDict(extra="ignore")
    entity_instance_id: str
    definition_id: int
    alias: str | None = None
    text: str
    text_linked: str | None = None
    node_avatar_url: str | None = None
    autogenerated_text: str | None = None
    autogenerated_text_linked: str | None = None
    created_date: datetime
    last_updated_date: datetime
    author_type: AuthorType
    author_id: str
    properties: list[OntologyInstancePropertyValue] = Field(default_factory=list)
    relationships: list[OntologyInstanceRelationshipRead] = Field(default_factory=list)


MilestoneTemporalType = Literal["beginning", "ending", "other"]
MilestoneBoundaryType = Literal["begin", "end", "none"]


class SceneDerivedFrom(BaseModel):
    model_config = ConfigDict(extra="ignore")
    entity_instance_id: str

    @field_validator("entity_instance_id", mode="before")
    def validate_entity_instance_id(cls, value: str) -> str:
        if value is None:
            raise ValueError("entity_instance_id cannot be empty")
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("entity_instance_id cannot be empty")
        return cleaned


class MilestoneDerivedFrom(BaseModel):
    model_config = ConfigDict(extra="ignore")
    entity_instance_id: str

    @field_validator("entity_instance_id", mode="before")
    def validate_entity_instance_id(cls, value: str) -> str:
        if value is None:
            raise ValueError("entity_instance_id cannot be empty")
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("entity_instance_id cannot be empty")
        return cleaned


class MilestoneEntityRelation(BaseModel):
    model_config = ConfigDict(extra="ignore")
    entity_instance_id: str
    label: str

    @field_validator("entity_instance_id", mode="before")
    def validate_entity_instance_id(cls, value: str) -> str:
        if value is None:
            raise ValueError("entity_instance_id cannot be empty")
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("entity_instance_id cannot be empty")
        return cleaned

    @field_validator("label", mode="before")
    def validate_label(cls, value: str) -> str:
        if value is None:
            raise ValueError("label cannot be empty")
        cleaned = value.strip().lower()
        if not cleaned:
            raise ValueError("label cannot be empty")
        if not re.fullmatch(r"[a-z0-9_]{2,64}", cleaned):
            raise ValueError(
                "label must be a normalized short token using lowercase letters, numbers, or underscores"
            )
        return cleaned


class MilestoneLocalOrder(BaseModel):
    model_config = ConfigDict(extra="ignore")
    followed_by_milestone_id: str | None = None
    preceded_by_milestone_id: str | None = None

    @field_validator(
        "followed_by_milestone_id", "preceded_by_milestone_id", mode="before"
    )
    def validate_optional_ids(cls, value: str | None) -> str | None:
        if value is None:
            return None
        cleaned = value.strip()
        if not cleaned:
            return None
        return cleaned


class SceneLocalOrder(BaseModel):
    model_config = ConfigDict(extra="ignore")
    followed_by_scene_id: str | None = None
    preceded_by_scene_id: str | None = None

    @field_validator("followed_by_scene_id", "preceded_by_scene_id", mode="before")
    def validate_optional_ids(cls, value: str | None) -> str | None:
        if value is None:
            return None
        cleaned = value.strip()
        if not cleaned:
            return None
        return cleaned


class SceneEntityRelation(BaseModel):
    model_config = ConfigDict(extra="ignore")
    entity_instance_id: str
    label: str = "related_to"

    @field_validator("entity_instance_id", mode="before")
    def validate_entity_instance_id(cls, value: str) -> str:
        if value is None:
            raise ValueError("entity_instance_id cannot be empty")
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("entity_instance_id cannot be empty")
        return cleaned

    @field_validator("label", mode="before")
    def validate_label(cls, value: str) -> str:
        if value is None:
            raise ValueError("label cannot be empty")
        cleaned = value.strip().lower()
        if not cleaned:
            raise ValueError("label cannot be empty")
        if not re.fullmatch(r"[a-z0-9_]{2,64}", cleaned):
            raise ValueError(
                "label must be a normalized short token using lowercase letters, numbers, or underscores"
            )
        return cleaned


class MilestoneBase(BaseModel):
    model_config = ConfigDict(extra="ignore")
    name: str
    description: str
    created_by_type: Literal["agent", "human"]
    created_by_author: str
    temporal_type: MilestoneTemporalType = "other"
    boundary_type: MilestoneBoundaryType = "none"
    local_order: MilestoneLocalOrder = Field(default_factory=MilestoneLocalOrder)
    derived_from: MilestoneDerivedFrom
    relates_to: list[MilestoneEntityRelation] = Field(default_factory=list)

    @field_validator("name", "description", "created_by_author", mode="before")
    def validate_non_empty_text(cls, value: str, info):
        if value is None:
            raise ValueError(f"{info.field_name} cannot be empty")
        cleaned = value.strip()
        if not cleaned:
            raise ValueError(f"{info.field_name} cannot be empty")
        return cleaned


class MilestoneCreate(MilestoneBase):
    id: str | None = None


class MilestoneUpdate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    name: str | None = None
    description: str | None = None
    created_by_type: Literal["agent", "human"] | None = None
    created_by_author: str | None = None
    temporal_type: MilestoneTemporalType | None = None
    boundary_type: MilestoneBoundaryType | None = None
    local_order: MilestoneLocalOrder | None = None
    derived_from: MilestoneDerivedFrom | None = None
    relates_to: list[MilestoneEntityRelation] | None = None

    @field_validator("name", "description", "created_by_author", mode="before")
    def validate_optional_non_empty_text(cls, value: str | None, info):
        if value is None:
            return None
        cleaned = value.strip()
        if not cleaned:
            raise ValueError(f"{info.field_name} cannot be empty")
        return cleaned


class MilestoneRead(MilestoneBase):
    id: str
    scene_id: str
    instance_id: str
    ontology_id: int
    created_at: datetime
    updated_at: datetime


class SceneBase(BaseModel):
    model_config = ConfigDict(extra="ignore")
    name: str
    description: str
    created_by_type: Literal["agent", "human"]
    created_by_author: str
    local_order: SceneLocalOrder = Field(default_factory=SceneLocalOrder)
    derived_from: SceneDerivedFrom
    relates_to: list[SceneEntityRelation] = Field(default_factory=list)

    @field_validator("name", "description", "created_by_author", mode="before")
    def validate_non_empty_text(cls, value: str, info):
        if value is None:
            raise ValueError(f"{info.field_name} cannot be empty")
        cleaned = value.strip()
        if not cleaned:
            raise ValueError(f"{info.field_name} cannot be empty")
        return cleaned


class SceneCreate(SceneBase):
    id: str | None = None
    milestones: list[MilestoneCreate] = Field(default_factory=list)


class SceneUpdate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    name: str | None = None
    description: str | None = None
    created_by_type: Literal["agent", "human"] | None = None
    created_by_author: str | None = None
    local_order: SceneLocalOrder | None = None
    derived_from: SceneDerivedFrom | None = None
    relates_to: list[SceneEntityRelation] | None = None

    @field_validator("name", "description", "created_by_author", mode="before")
    def validate_optional_non_empty_text(cls, value: str | None, info):
        if value is None:
            return None
        cleaned = value.strip()
        if not cleaned:
            raise ValueError(f"{info.field_name} cannot be empty")
        return cleaned


class SceneRead(SceneBase):
    id: str
    instance_id: str
    ontology_id: int
    created_at: datetime
    updated_at: datetime
    milestones: list[MilestoneRead] = Field(default_factory=list)


class OntologyInstanceBase(BaseModel):
    model_config = ConfigDict(extra="ignore")
    name: str


class OntologyInstanceCreate(OntologyInstanceBase):
    model_config = ConfigDict(extra="ignore")
    ontology_id: int
    entities: list[OntologyInstanceEntityCreate]
    scenes: list[SceneCreate] = Field(default_factory=list)


class OntologyInstanceUpdate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    name: str | None = None
    entities: list[OntologyInstanceEntityCreate] | None = None
    scenes: list[SceneCreate] | None = None


class OntologyInstanceRead(OntologyInstanceBase):
    model_config = ConfigDict(extra="ignore")
    instance_id: str
    ontology_id: int
    created_at: datetime
    updated_at: datetime
    entities: list[OntologyInstanceEntityRead]
    scenes: list[SceneRead] = Field(default_factory=list)


class OntologyInstanceSummary(BaseModel):
    model_config = ConfigDict(extra="ignore")
    instance_id: str
    ontology_id: int
    name: str
    created_at: datetime
    updated_at: datetime
    primary_alias: str | None = None
    aliases: list[str] = Field(default_factory=list)
    avatar_url: str | None = None
    entity_count: int = 0


class OntologyInstanceSummaryPage(BaseModel):
    model_config = ConfigDict(extra="ignore")
    total: int
    skip: int
    limit: int
    results: list[OntologyInstanceSummary] = Field(default_factory=list)


class OntologyInstanceCountResponse(BaseModel):
    model_config = ConfigDict(extra="ignore")
    total: int


class OntologyInstanceSceneCountsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore")
    instance_ids: list[str] = Field(
        ...,
        min_length=1,
        max_length=200,
        description=(
            "Ontology instance ids to aggregate scene counts for. "
            "Duplicate values are deduplicated server-side while preserving first-seen order."
        ),
    )

    @field_validator("instance_ids", mode="before")
    def validate_instance_ids(cls, value: Any) -> list[str]:
        if value is None:
            raise ValueError("instance_ids cannot be empty")
        if not isinstance(value, list):
            raise ValueError("instance_ids must be a list of strings")

        normalized: list[str] = []
        seen: set[str] = set()
        for raw in value:
            if raw is None:
                continue
            cleaned = str(raw).strip()
            if not cleaned:
                continue
            if cleaned in seen:
                continue
            seen.add(cleaned)
            normalized.append(cleaned)

        if not normalized:
            raise ValueError("instance_ids cannot be empty")
        if len(normalized) > 200:
            raise ValueError("instance_ids cannot contain more than 200 unique ids")
        return normalized


class OntologyInstanceSceneCountItem(BaseModel):
    model_config = ConfigDict(extra="ignore")
    instance_id: str
    scene_count: int


class OntologyInstanceSceneCountsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore")
    results: list[OntologyInstanceSceneCountItem] = Field(default_factory=list)


class OntologyInstanceEntityTypeClearRequest(BaseModel):
    model_config = ConfigDict(extra="ignore")
    ontology_id: int
    entity_definition_ids: list[int] = Field(default_factory=list)
    entity_type_names: list[str] = Field(default_factory=list)


class OntologyInstanceEntityTypeClearJobResponse(BaseModel):
    model_config = ConfigDict(extra="ignore")
    message: str
    kind: str
    job_id: int
    status: str
    monitor_url: str


class OntologyInstanceTimelineClearRequest(BaseModel):
    model_config = ConfigDict(extra="ignore")
    ontology_id: int


class OntologyInstanceTimelineClearJobResponse(BaseModel):
    model_config = ConfigDict(extra="ignore")
    message: str
    kind: str
    job_id: int
    status: str
    monitor_url: str


class OntologyInstanceSearchHit(BaseModel):
    model_config = ConfigDict(extra="ignore")
    instance: OntologyInstanceRead
    ontology_name: str | None = None
    world_name: str | None = None
    match_reason: str | None = None
    matched_aliases: list[str] = Field(default_factory=list)
    snippet: str | None = None
    score: float | None = None
    source_node_id: str | None = None
    source_labels: list[str] = Field(default_factory=list)


class OntologyInstanceSearchResponse(BaseModel):
    model_config = ConfigDict(extra="ignore")
    query: str
    ontology_id: int | None = None
    ontology_name: str | None = None
    world_name: str | None = None
    direct_results: list[OntologyInstanceSearchHit] = Field(default_factory=list)
    deep_results: list[OntologyInstanceSearchHit] = Field(default_factory=list)


class OntologyEntityResolveRequest(BaseModel):
    model_config = ConfigDict(extra="ignore")
    ontology_id: int = Field(
        ...,
        ge=1,
        description="Ontology id used to scope the resolution.",
    )
    entity_instance_ids: list[str] = Field(
        ...,
        min_length=1,
        max_length=200,
        description=(
            "Entity instance ids to resolve. Duplicate values are deduplicated "
            "server-side while preserving first-seen order."
        ),
    )

    @field_validator("entity_instance_ids", mode="before")
    def validate_entity_instance_ids(cls, value: Any) -> list[str]:
        if value is None:
            raise ValueError("entity_instance_ids cannot be empty")
        if not isinstance(value, list):
            raise ValueError("entity_instance_ids must be a list of strings")

        normalized: list[str] = []
        seen: set[str] = set()
        for raw in value:
            if raw is None:
                continue
            cleaned = str(raw).strip()
            if not cleaned:
                continue
            if cleaned in seen:
                continue
            seen.add(cleaned)
            normalized.append(cleaned)

        if not normalized:
            raise ValueError("entity_instance_ids cannot be empty")
        if len(normalized) > 200:
            raise ValueError("entity_instance_ids cannot contain more than 200 unique ids")
        return normalized


class OntologyEntityResolveItem(BaseModel):
    model_config = ConfigDict(extra="ignore")
    entity_instance_id: str
    instance_id: str
    ontology_id: int
    entity_definition_id: int
    entity_alias: str | None = None
    instance_name: str | None = None


class OntologyEntityResolveResponse(BaseModel):
    model_config = ConfigDict(extra="ignore")
    results: list[OntologyEntityResolveItem] = Field(default_factory=list)
    missing_entity_instance_ids: list[str] = Field(default_factory=list)
