from __future__ import annotations

import asyncio
from typing import Any

from neo4j import AsyncSession

from app.celery_app import celery_app
from app.core.config import get_settings
from app.graph.neo4j import get_driver
from app.utils.linker import build_alias_pattern, link_text

settings = get_settings()


async def _link_instance_entities(instance_id: str) -> None:
    driver = get_driver()
    async with driver.session(database=settings.neo4j_database) as session:
        records = await _fetch_entities(session, instance_id)
        if not records:
            return

        alias_map: dict[str, list[str]] = {}
        for record in records:
            alias = record.get("alias") or ""
            entity_id = record["entity_id"]
            normalized = alias.lower()
            alias_map.setdefault(normalized, []).append(entity_id)

        pattern = build_alias_pattern(alias_map.keys())

        payload: list[dict[str, Any]] = []
        for record in records:
            entity_id = record["entity_id"]
            raw_text = record.get("text")
            raw_auto = record.get("autogenerated_text")
            alias = record.get("alias") or ""
            normalized = alias.lower()
            text_linked = link_text(
                raw_text, alias_map, entity_id, instance_id, pattern
            )
            auto_linked = link_text(
                raw_auto, alias_map, entity_id, instance_id, pattern
            )
            payload.append(
                {
                    "entity_id": entity_id,
                    "text_linked": text_linked if text_linked is not None else raw_text,
                    "autogenerated_text_linked": (
                        auto_linked if auto_linked is not None else raw_auto
                    ),
                }
            )

        await session.run(
            """
            UNWIND $payload AS item
            MATCH (e:EntityInstance {entity_instance_id: item.entity_id})
            SET e.text_linked = item.text_linked,
                e.autogenerated_text_linked = item.autogenerated_text_linked
            """,
            payload=payload,
        )


async def _fetch_entities(
    session: AsyncSession, instance_id: str
) -> list[dict[str, Any]]:
    result = await session.run(
        """
        MATCH (inst:OntologyInstance {instance_id: $instance_id})-[:HAS_ENTITY]->(e:EntityInstance)
        RETURN inst.instance_id AS instance_id,
               e.entity_instance_id AS entity_id,
               e.alias AS alias,
               e.text AS text,
               e.autogenerated_text AS autogenerated_text
        """,
        instance_id=instance_id,
    )
    return await result.data()


@celery_app.task(name="ontology.link_instance")
def link_instance(instance_id: str) -> None:
    asyncio.run(_link_instance_entities(instance_id))
