from typing import Optional, List, Dict
from sqlmodel import SQLModel
from datetime import datetime

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from .schema_page_characteristic_value import PageCharacteristicValueCreate, PageCharacteristicValueUpdate, PageCharacteristicValueRead
    from .schema_page_key_event import PageKeyEventRead
    from .schema_page_relationship import PageRelationshipRead
    from .schema_page_change import PageChangeRead

class PageBase(SQLModel):
    gameworld_id: int
    concept_id: int
    name: str
    content: Optional[str] = None
    autogenerated_content: Optional[str] = None
    updated_by_agent_id: Optional[int] = None
    logo: Optional[str] = None
    allowed_user_ids: Optional[List[int]] = []

    #Cross Link information    
    allow_crosslinks: Optional[bool] = True #allow crosslinks in this page
    ignore_crosslink: Optional[bool] = False #ignore this page when adding crosslinks to other pages
    allow_crossworld: Optional[bool] = True #Allow adding crosslink for other worlds to this page / allow this page to be added to crosslink for other worlds

    # Lists are returned via related tables
        

class PageCreate(PageBase):
    values: Optional[List["PageCharacteristicValueCreate"]] = []

class PageUpdate(SQLModel):
    name: Optional[str] = None
    content: Optional[str] = None
    autogenerated_content: Optional[str] = None
    updated_by_agent_id: Optional[int] = None
    logo: Optional[str] = None
    values: Optional[List["PageCharacteristicValueUpdate"]] = None
    allow_crosslinks: Optional[bool] = True #allow crosslinks in this page
    ignore_crosslink: Optional[bool] = False #ignore this page when adding crosslinks to other pages
    allow_crossworld: Optional[bool] = True #Allow adding crosslink for other worlds to this page / allow this page to be added to crosslink for other worlds

class PageRead(PageBase):
    id: int
    created_by_user_id: Optional[int]
    created_at: datetime
    updated_at: Optional[datetime]
    values: List["PageCharacteristicValueRead"] = []
    key_events: List["PageKeyEventRead"] = []
    relationship_map: List["PageRelationshipRead"] = []
    changelog: List["PageChangeRead"] = []

# New lightweight schema for search results
class PageSummary(SQLModel):
    id: int
    gameworld_id: int
    concept_id: int
    name: str
    logo: Optional[str] = None

# resolve forward references on import
from .schema_page_characteristic_value import (
    PageCharacteristicValueCreate,
    PageCharacteristicValueUpdate,
    PageCharacteristicValueRead,
)
from .schema_page_key_event import PageKeyEventRead
from .schema_page_relationship import PageRelationshipRead
from .schema_page_change import PageChangeRead

PageCreate.model_rebuild()
PageUpdate.model_rebuild()
PageRead.model_rebuild()
PageSummary.model_rebuild()


