from sqlmodel import SQLModel
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker
from app.config import settings

DATABASE_URL = settings.database_url

engine = create_async_engine(DATABASE_URL, echo=True, future=True)
async_session_maker = sessionmaker(
    bind=engine, class_=AsyncSession, expire_on_commit=False
)


async def init_db():
    async with engine.begin() as conn:
        await conn.run_sync(SQLModel.metadata.create_all)
        await conn.run_sync(_migrate)


def _migrate(conn):
    """Simple migration to add new columns without dropping data."""
    from sqlalchemy import inspect, text

    inspector = inspect(conn)
    columns = [c["name"] for c in inspector.get_columns("agent")]
    if "task" not in columns:
        conn.execute(text("ALTER TABLE agent ADD COLUMN task TEXT"))
    if "logo" not in columns:
        conn.execute(text("ALTER TABLE agent ADD COLUMN logo TEXT"))
    if "personality" not in columns:
        conn.execute(text("ALTER TABLE agent ADD COLUMN personality TEXT"))
    if "vector_db_update_date" not in columns:
        conn.execute(
            text("ALTER TABLE agent ADD COLUMN vector_db_update_date DATETIME")
        )
    if "specialist_update_date" not in columns:
        conn.execute(
            text("ALTER TABLE agent ADD COLUMN specialist_update_date DATETIME")
        )

    # -- User table migrations --
    columns = [c["name"] for c in inspector.get_columns("user")]
    if "timezone" not in columns:
        conn.execute(text("ALTER TABLE user ADD COLUMN timezone TEXT"))

    # -- Session table migrations --
    session_cols = inspector.get_columns("session")
    column_names = [c["name"] for c in session_cols]
    if "name" not in column_names:
        # Existing rows may exist, so add with a default value
        conn.execute(text("ALTER TABLE session ADD COLUMN name TEXT DEFAULT ''"))
    if "timezone" not in column_names:
        conn.execute(text("ALTER TABLE session ADD COLUMN timezone TEXT DEFAULT 'UTC'"))
    if "scheduled_time" in column_names:
        sched_col = next(c for c in session_cols if c["name"] == "scheduled_time")
        if not sched_col["nullable"]:
            conn.execute(text("ALTER TABLE session RENAME TO session_old"))
            conn.execute(
                text(
                    "CREATE TABLE session ("
                    "id INTEGER PRIMARY KEY AUTOINCREMENT, "
                    "table_id INTEGER NOT NULL REFERENCES table(id), "
                    "name TEXT NOT NULL, "
                    "scheduled_time DATETIME, "
                    "summary TEXT, "
                    "location TEXT, "
                    "timezone TEXT NOT NULL DEFAULT 'UTC', "
                    "created_by INTEGER NOT NULL REFERENCES user(id), "
                    "created_at DATETIME NOT NULL)"
                )
            )
            conn.execute(
                text(
                    "INSERT INTO session (id, table_id, name, scheduled_time, summary, location, timezone, created_by, created_at) "
                    "SELECT id, table_id, name, scheduled_time, summary, location, timezone, created_by, created_at FROM session_old"
                )
            )
            conn.execute(text("DROP TABLE session_old"))

    # -- Page table migrations --
    columns = [c["name"] for c in inspector.get_columns("page")]
    if "autogenerated_content" not in columns:
        conn.execute(text("ALTER TABLE page ADD COLUMN autogenerated_content TEXT"))
    if "updated_by_agent_id" not in columns:
        conn.execute(
            text(
                "ALTER TABLE page ADD COLUMN updated_by_agent_id INTEGER REFERENCES agent(id)"
            )
        )

    # -- PageKeyEvent table --
    if "pagekeyevent" not in inspector.get_table_names():
        conn.execute(
            text(
                "CREATE TABLE pagekeyevent (id INTEGER PRIMARY KEY AUTOINCREMENT, page_id INTEGER NOT NULL REFERENCES page(id), event_type TEXT NOT NULL, event_date DATETIME, summary TEXT, source_page_id INTEGER REFERENCES page(id), related_page_ids JSON, author_type TEXT NOT NULL, author_id INTEGER NOT NULL, added_at DATETIME NOT NULL)"
            )
        )

    # -- PageRelationship table --
    if "pagerelationship" not in inspector.get_table_names():
        conn.execute(
            text(
                "CREATE TABLE pagerelationship (id INTEGER PRIMARY KEY AUTOINCREMENT, page_id INTEGER NOT NULL REFERENCES page(id), target_page_id INTEGER NOT NULL REFERENCES page(id), relationship_type TEXT NOT NULL, direction TEXT NOT NULL, source_page_id INTEGER REFERENCES page(id), description TEXT, author_type TEXT NOT NULL, author_id INTEGER NOT NULL, added_at DATETIME NOT NULL)"
            )
        )
    else:
        columns = [c["name"] for c in inspector.get_columns("pagerelationship")]
        if "direction" not in columns:
            conn.execute(
                text(
                    "ALTER TABLE pagerelationship ADD COLUMN direction TEXT DEFAULT 'outgoing'"
                )
            )

    # -- PageChange table --
    if "pagechange" not in inspector.get_table_names():
        conn.execute(
            text(
                "CREATE TABLE pagechange (id INTEGER PRIMARY KEY AUTOINCREMENT, page_id INTEGER NOT NULL REFERENCES page(id), date DATETIME NOT NULL, change_type TEXT NOT NULL, author_type TEXT NOT NULL, author_id INTEGER NOT NULL, values JSON)"
            )
        )

    # -- SpecialistSource table --
    if "specialistsource" not in inspector.get_table_names():
        conn.execute(
            text(
                "CREATE TABLE specialistsource (id INTEGER PRIMARY KEY AUTOINCREMENT, agent_id INTEGER NOT NULL REFERENCES agent(id), name TEXT, type TEXT NOT NULL, path TEXT, url TEXT, added_at DATETIME NOT NULL)"
            )
        )
    else:
        columns = [c["name"] for c in inspector.get_columns("specialistsource")]
        if "name" not in columns:
            conn.execute(text("ALTER TABLE specialistsource ADD COLUMN name TEXT"))

    # -- LibraryItem table --
    if "libraryitem" not in inspector.get_table_names():
        conn.execute(
            text(
                "CREATE TABLE libraryitem (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, system TEXT, description TEXT, path TEXT, added_at DATETIME NOT NULL, vector_db_update_date DATETIME)"
            )
        )
    else:
        columns = [c["name"] for c in inspector.get_columns("libraryitem")]
        if "vector_db_update_date" not in columns:
            conn.execute(
                text(
                    "ALTER TABLE libraryitem ADD COLUMN vector_db_update_date DATETIME"
                )
            )
        if "cover_url" not in columns:
            conn.execute(text("ALTER TABLE libraryitem ADD COLUMN cover_url TEXT"))

    # -- AgentLibraryItem table --
    if "agentlibraryitem" not in inspector.get_table_names():
        conn.execute(
            text(
                "CREATE TABLE agentlibraryitem (agent_id INTEGER NOT NULL REFERENCES agent(id), item_id INTEGER NOT NULL REFERENCES libraryitem(id), added_at DATETIME NOT NULL, PRIMARY KEY (agent_id, item_id))"
            )
        )

    # -- WorldEmbedding table --
    if "worldembedding" not in inspector.get_table_names():
        conn.execute(
            text(
                "CREATE TABLE worldembedding (id INTEGER PRIMARY KEY AUTOINCREMENT, world_id INTEGER NOT NULL REFERENCES gameworld(id), name TEXT NOT NULL, created_at DATETIME NOT NULL, last_index_time DATETIME, page_count INTEGER, build_seconds REAL)"
            )
        )
    else:
        columns = [c["name"] for c in inspector.get_columns("worldembedding")]
        if "last_index_time" not in columns:
            conn.execute(
                text("ALTER TABLE worldembedding ADD COLUMN last_index_time DATETIME")
            )
        if "page_count" not in columns:
            conn.execute(
                text("ALTER TABLE worldembedding ADD COLUMN page_count INTEGER")
            )
        if "build_seconds" not in columns:
            conn.execute(
                text("ALTER TABLE worldembedding ADD COLUMN build_seconds REAL")
            )

    # -- AgentEmbedding table --
    if "agentembedding" not in inspector.get_table_names():
        conn.execute(
            text(
                "CREATE TABLE agentembedding (agent_id INTEGER NOT NULL REFERENCES agent(id), embedding_id INTEGER NOT NULL REFERENCES worldembedding(id), added_at DATETIME NOT NULL, PRIMARY KEY (agent_id, embedding_id))"
            )
        )

    # -- UserNote table --
    if "usernote" not in inspector.get_table_names():
        conn.execute(
            text(
                "CREATE TABLE usernote (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL REFERENCES user(id), title TEXT NOT NULL, content TEXT, note_date DATETIME, tags JSON, gameworld_id INTEGER REFERENCES gameworld(id), shared_with_user_ids JSON, contributors JSON, locked_by_user_id INTEGER REFERENCES user(id), locked_at DATETIME, created_at DATETIME NOT NULL, updated_at DATETIME)"
            )
        )
    else:
        columns = [c["name"] for c in inspector.get_columns("usernote")]
        if "contributors" not in columns:
            conn.execute(text("ALTER TABLE usernote ADD COLUMN contributors JSON"))
        if "locked_by_user_id" not in columns:
            conn.execute(
                text(
                    "ALTER TABLE usernote ADD COLUMN locked_by_user_id INTEGER REFERENCES user(id)"
                )
            )
        if "locked_at" not in columns:
            conn.execute(text("ALTER TABLE usernote ADD COLUMN locked_at DATETIME"))


async def get_session() -> AsyncSession:
    async with async_session_maker() as session:
        yield session
