"""Prompt contracts in CharacterAgent embodiment execution order.

IDENTITY_DESCRIPTION_PROMPT resolves narrative grounding when absent and
refreshes it after embodiment; it never supplies numerical trait evidence.
For each source scene chunk, PERSPECTIVE_PROMPT runs first:
    objective scenes -> psychologically distinctive subjective perspectives.
    A truncated response retries with PERSPECTIVE_TRUNCATION_RECOVERY_PROMPT.
After perspective validation, two calls run in parallel for that chunk:
    PSYCHOLOGICAL_ANALYSIS_PROMPT (built from ENRICHMENT_PROMPT):
        canonical scenes + source_type/perspectives + identity_description -> emotions, beliefs, impacts, signals.
    TRAIT_INTERPRETATION_PROMPT:
        canonical scenes + perspectives + identity_description -> candidates.
The backend combines both branches and deterministically updates the draft
profile in source order. No prompt receives a cumulative raw-evidence ledger or produces
public output; the reviewable draft is assembled by the backend.
"""
import json
from app.jobs.character_agent.trait_evidence_contract import TRAIT_EVIDENCE_CONTRACT
from app.schemas.character_traits import DIRECTIONAL_TRAITS, TRAIT_BY_KEY, trait_metadata

# Purpose: Supply the complete trait definitions and scoring contract.
# Used by: TRAIT_INTERPRETATION_PROMPT only.
# Expected: Scene trait extraction uses the authoritative definitions and constraints.
TRAIT_CONTRACT = "\nAuthoritative trait definitions and scale:\n" + json.dumps(trait_metadata(), ensure_ascii=False)
# Purpose: Supply only the eight narrative trait meanings and pole descriptions.
# Used by: IDENTITY_DESCRIPTION_PROMPT.
# Expected: Psychological synthesis can describe traits without scoring machinery.
IDENTITY_TRAIT_DESCRIPTION_CONTRACT = (
    "\nEstablished personality dimensions and meanings:\n"
    + json.dumps([
        {
            "name": key,
            "definition": TRAIT_BY_KEY[key].definition,
            "low_pole": TRAIT_BY_KEY[key].left_pole,
            "high_pole": TRAIT_BY_KEY[key].right_pole,
        }
        for key in DIRECTIONAL_TRAITS
    ], ensure_ascii=False)
)
PROMPT_VERSION = "character-embodiment-v28-psychological-perspective"

# Execution order: Stage 0, once when description is absent and once after
# scene processing to refresh it from the resulting current state.
# Purpose: Synthesize narrative grounding without calculating traits.
# Used by: EmbodyAgent.generate_identity_description.
# Expected: identity_summary, psychological_summary, personality_traits.
IDENTITY_DESCRIPTION_PROMPT = r"""You are constructing the psychological identity of a fictional character.
Create a concise, distinctive portrait that can guide how the character interprets
events, thinks, and behaves. Ground it in the supplied canonical identity and
psychological state. Do not invent history, motivations, relationships, or
experiences. If a current trait value is unknown, do not infer that trait from
the missing value. Numerical values describe tendencies, not absolute rules.

INPUT JSON:
{
  "name": "character name",
  "entity_type": "ontology entity type",
  "entity_descriptor": "entity type descriptor, or null",
  "autogenerated_text": "autogenerated character description, or null",
  "text": "authored character text, or null",
  "properties": [{"name": "property name", "value": "property value"}],
  "goals": [{"name": "goal name", "description": "goal description or null"}],
  "aspects": [{"name": "aspect name", "type": "aspect type", "descriptor": "aspect description or null"}],
  "traits": [{"name": "forbearance", "value": 3}, {"name": "presence", "value": null}]
}

Interpret each input field as follows:
- name, entity_type, entity_descriptor, autogenerated_text, and text describe
  the canonical character and their authored background.
- properties contains named entity properties as name/value pairs.
- goals and aspects describe current psychological state and characterization.
- traits contains one of the eight established trait keys and its current
  integer point value from 1 through 9; null means unknown. The appended trait
  contract explains each dimension and its low/high meanings.

OUTPUT JSON SCHEMA (return exactly this object shape):
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "required": ["identity_summary", "psychological_summary", "personality_traits"],
  "properties": {
    "identity_summary": {"type": "string", "minLength": 1},
    "psychological_summary": {"type": "string", "minLength": 1},
    "personality_traits": {
      "type": "array",
      "items": {"type": "object", "additionalProperties": false,
        "required": ["trait", "description"],
        "properties": {
          "trait": {"enum": ["integrity", "caution", "presence", "forbearance", "diligence", "curiosity", "sharing", "restlessness"]},
          "description": {"type": "string", "minLength": 1}
        }
      }
    }
  }
}

Produce three components:
1. identity_summary: one concise paragraph describing the character's
   background, role, defining characteristics, and what makes them recognizable.
2. psychological_summary: one concise paragraph describing motivations, desires,
   fears, values, internal conflicts, ambitions, and their distinctive outlook.
3. personality_traits: only the character's meaningfully supported dispositions.
   Each description should be brief, specific to this character, and explain how
   that disposition appears in their attitudes or choices.

Write psychologically insightful, natural prose. Prefer distinctive details over
exhaustive coverage. Reflect supported development in the supplied current
state. Do not confuse temporary emotions with enduring dispositions. Avoid
repetition between components. Omit unsupported traits; an empty array is valid.
Return JSON only.""" + IDENTITY_TRAIT_DESCRIPTION_CONTRACT

# Execution order: Stage 1, after Stage 0; run for each chunk before Stage 2/3.
# Stage 1: objective scenes to subjective perspectives.
# Purpose: Extract one grounded subjective perspective per objective scene.
# Used by: EmbodyAgent._incorporate_perspectives, the first chunk call.
# Expected: Ordered JSON perspectives with psychologically grounded subjective text.
PERSPECTIVE_PROMPT = r"""You are incorporating a character's identity into canonical objective scenes.

Scenes are immutable objective evidence and are listed earliest to latest. The
identity object includes identity_description; use it as personality grounding,
not as evidence of behavior in any scene. For
each scene, produce exactly one compact grounded subjective perspective. Never
rewrite a misunderstanding, suspicion, or uncertainty as an objective scene fact.

Use only facts available to the character at each scene. The whole source bundle is
visible to you, but later revelations must never become earlier knowledge.
The backend assigns every canonical scene and evidence_ids reference. Do not return IDs or
evidence references; return one result for each numbered input position. Use
identity_description to understand the character's established outlook while
respecting only facts available at each scene.
Return every perspective in the same order as the input positions. The backend binds
position 1 to the first scene, position 2 to the second, and so on.

This is compact structured character-state extraction, not narration, roleplay,
a memoir, dialogue, or stream of consciousness. Do not retell the scene.

For every perspective:
- perspective: at most 120 words; explain what the experience means to this
  character specifically. Let established personality, values, fears, motivations,
  and beliefs shape what they notice, conclude, and feel. Distinguish what they
  know from what they suspect, and do not present mistaken beliefs as objective
  facts. Describe meaningful internal change when supported by this scene and
  what the character knows; do not reduce the account to an immediate emotion.
  Keep the interpretation grounded and concise without retelling the scene.

INPUT:
{
  "identity": {
    "alias": "name or alias",
    "subtitle": "subtitle or null",
    "entity_type": "ontology type",
    "entity_type_description": "type description or null",
    "properties": {"property": "value"},
    "identity_description": {"identity_summary":"...", "psychological_summary":"...", "personality_traits":[{"trait":"trait key","description":"..."}]}
  },
  "scenes": [
    {"position": 1, "name": "scene name", "description": "scene description", "created_at": "ISO timestamp or null"}
  ],
  "required_output": "one position-bound perspective object as defined below"
}

OUTPUT — return an object with exactly one key "perspectives":
{
  "perspectives": [
    {
      "source_type": "participated | witnessed | heard_about | read_about | inferred | unknown",
      "perspective": "psychologically distinctive subjective account, including supported internal change"
    }
  ]
}

Return JSON only."""


# Execution order: Stage 1 recovery; substitute only when PERSPECTIVE_PROMPT is truncated.
# Purpose: Retry perspective extraction after the first output is truncated.
# Used by: EmbodyAgent._incorporate_perspectives on a truncated response.
# Expected: The same ordered JSON perspectives, within the output budget.
PERSPECTIVE_TRUNCATION_RECOVERY_PROMPT = PERSPECTIVE_PROMPT + r"""

RECOVERY INSTRUCTION: Your previous response exceeded the output budget. Produce
the same required perspectives much more compactly. The exact one-perspective-per-
scene count and every field limit are mandatory. Return JSON only."""


# Execution order: Stage 2 branch, parallel with TRAIT_INTERPRETATION_PROMPT after Stage 1.
# Stages 2 and 3 receive canonical scene context and the Stage 1 interpretation.
# Purpose: Define psychological enrichment from canonical scenes and grounded character interpretations.
# Used by: PSYCHOLOGICAL_ANALYSIS_PROMPT for the second scene-chunk call.
# Expected: Ordered JSON enrichments with emotions, beliefs, impacts, and signals.
ENRICHMENT_PROMPT = r"""Stage 2 — enrich grounded character perspectives. For every ordered
scene item, use its canonical scene name and description together with the
agent_scene_interpretation source_type and perspective from Stage 1. Use
identity_description as established psychological grounding. Interpret each
scene through what this character knows and how their distinctive personality,
values, fears, motivations, and beliefs shape its meaning. Capture supported
internal changes, not just immediate emotions. Do not contradict the canonical
scene facts, treat the character's uncertainty as fact, or let later positions
affect earlier ones. Return exactly one enrichment per input scene, in order.

INPUT JSON:
{"identity_description":{"identity_summary":"...","psychological_summary":"...","personality_traits":[{"trait":"...","description":"..."}]},"scenes":[{"position":1,"scene":{"name":"canonical scene name","description":"canonical scene description"},"agent_scene_interpretation":{"source_type":"participated|witnessed|heard_about|read_about|inferred|unknown","perspective":"the character's subjective interpretation"}}],"current_profile":{"aspects":[{"position":1,"name":"..."}],"goals":[{"position":1,"title":"..."}]}}

Input meanings: identity_description is the established narrative portrait;
scenes is the ordered list of canonical records, where position binds the item
to its output, scene.name and scene.description are objective source facts, and
agent_scene_interpretation.source_type describes how the character knows the
scene while perspective describes its subjective meaning to them. Current
profile lists are active aspects and goals available as impact targets, indexed
by position. Do not treat interpretation as an objective fact or identity
description as proof that a particular reaction occurred.

Every enrichment MUST contain all five arrays: emotions, beliefs, impacts,
aspect_signals, goal_signals. Use [] when unsupported. Never
return scene_id, evidence_ids, episode_id, available_after_scene_id, or target_id:
the backend supplies those.

Limits per scene: emotions 2, beliefs 2, impacts 2, aspect
signals 1, goal_signals 1. Descriptions/condition justifications <=240 chars;
beliefs, impacts, and behavior <=300; other justifications <=360.

OUTPUT: {"scene_enrichments":[{"emotions":[{"arousal":0..100,"valence":"0..100 (0 negative, 50 neutral, 100 positive)","description":"..."}],"beliefs":[{"statement":"...","confidence":0..100,"status":"suspected|believed|confirmed|doubted|disproven|superseded"}],"impacts":[{"impact_type":"goal_change|aspect_change","target_index":1,"direction":"allowed direction","magnitude":0..100,"description":"..."}],"aspect_signals":[{"name":"I ...","category":"identity|role|status|physical|capability|knowledge|preference|attitude|history","description":"...","importance":1..5,"justification":"...","confidence":0.0}],"goal_signals":[{"operation":"add|complete","title":"...","description":"...","goal_type":"desire|objective|ambition|obligation|avoidance|survival","priority":0..100,"commitment":0..100,"basis":"explicit|inferred","justification":"...","confidence":0.0}]}]}.

Impacts use target_index from the matching current_profile list. goal_change is
advanced|threatened; aspect_change is created|reinforced|invalidated. With no
targets, impacts must be []. Current-profile aspects are impact targets only:
never repeat or rephrase the same underlying fact in aspect_signals. Current-profile goals are impact
targets and completion candidates: do not repeat a title for operation `add`,
but operation `complete` must use the exact title of an active current-profile goal.

An aspect signal needs a grounded durable character fact; its name must be a
concise present-tense first-person self-statement beginning with `I `, such as
`I belong to the Order of Saint Paul`, `I can return through a synthetic transfer`,
or `I am a vessel of Belshazar`. Never use an abstract label such as "affiliation"
or "synthetic consciousness transfer". A goal signal with operation `add` needs a
grounded ongoing personal commitment. For every active current-profile goal,
assess whether this scene establishes that it was achieved, resolved, made
impossible, or superseded. Emit operation `complete` only on that conclusive
evidence; never complete a goal merely because it is absent, delayed, uncertain,
or still in progress. They are evidence, not mutations. A
confirmed, character-specific revelation about origin, nature, body, identity,
or constructed status is a mandatory distinct `identity` aspect signal when it
is important to the character. Name the revelation itself (for example,
"I am a <creator>-crafted vessel"), not an existing relationship, role, or goal. Return
JSON only."""


# Execution order: Stage 2 call, after perspective validation, parallel with Stage 3.
# Purpose: Apply the enrichment contract to a whole perspective chunk.
# Used by: EmbodyAgent._analyze_psychological_batch after perspectives are bound.
# Expected: One ordered JSON scene_enrichments item per input perspective.
PSYCHOLOGICAL_ANALYSIS_PROMPT = ENRICHMENT_PROMPT + r"""
This is the complete psychological-analysis stage. Return emotions, beliefs,
impacts, aspect_signals, and goal_signals for every
perspective. Each item must cite exactly the current scene conceptually; the
backend assigns evidence_ids by position, so omit them from model output.
"""

# Backend-owned references remain part of the public contract, but are never model supplied.
PERSPECTIVE_PROMPT += "\nThe backend binds every perspective to exactly its own supplied scene and assigns evidence_ids by position; omit them from model output."
ENRICHMENT_PROMPT += "\nEach item must cite exactly the current scene conceptually; the backend assigns evidence_ids by position, so omit them from model output."

# Execution order: Stage 3 branch, parallel with PSYCHOLOGICAL_ANALYSIS_PROMPT after Stage 1.
# Stage 3 receives canonical scene context and the Stage 1 interpretation.
# Purpose: Classify grounded character-specific trait signals against the directional trait registry.
# Used by: EmbodyAgent._interpret_traits_batch after perspective validation.
# Expected: Ordered JSON scene_trait_interpretations with supported candidates.
TRAIT_INTERPRETATION_PROMPT = r"""Stage 3 — interpret canonical scenes through this character's grounded perspective to identify supported trait observations.
INPUT JSON:
{"target":{"alias":"character alias","entity_type":"canonical ontology type","entity_type_description":"type meaning or null","identity_description":{"identity_summary":"...","psychological_summary":"...","personality_traits":[{"trait":"trait key","description":"..."}]}},"scenes":[{"position":1,"scene":{"name":"canonical scene name","description":"canonical scene description"},"agent_scene_interpretation":{"source_type":"participated|witnessed|heard_about|read_about|inferred|unknown","perspective":"the character's subjective interpretation"}}]}

Input meanings: target identifies the character being interpreted; identity_description
provides established psychological context, not proof that a trait was expressed
in a particular scene. scenes is ordered and position binds each result to one
scene. scene.name and scene.description are canonical objective facts.
agent_scene_interpretation.source_type says how the character knows the scene;
perspective says what the character understood and what the experience means
to them. The scene is canonical objective context; the interpretation is what
this character understood and experienced. Use identity_description to understand distinctive psychology, but do not assume its claims prove a trait. Consider choices, expressed values, and meaningful psychological responses in context. A strong feeling alone does not establish a trait. Do not infer from names, occupation, species, role, other characters, or unsupported assumptions. Interpret only this character, respecting the source_type and what the character could know.
Return one scene_trait_interpretations item for each input scene, in order.
Observations must be justified by the supplied canonical scene and character
interpretation, including evidence that contradicts the identity description.
Each scene has at
most one observation per trait.
Only emit a trait when the scene and interpretation support a meaningful,
character-specific disposition or choice. Missing or ambiguous evidence is
unknown, never midpoint. Return empty trait_candidates arrays normally.
OUTPUT: {"scene_trait_interpretations":[{"trait_candidates":[{"trait":"one of eight keys","polarity":"low|high","situation_type":"diagnostic:relationship:stakes|unspecified","justification":"brief grounded reason"}]}]}.
Return JSON only.""" + TRAIT_EVIDENCE_CONTRACT + TRAIT_CONTRACT
