"""Prompt contracts in CharacterAgent embodiment execution order.

IDENTITY_DESCRIPTION_PROMPT resolves narrative grounding when absent and
refreshes it after embodiment; it never supplies numerical trait evidence.
For each source scene chunk, PERSPECTIVE_PROMPT runs first:
    objective scenes -> psychologically distinctive subjective perspectives.
    A truncated response retries with PERSPECTIVE_TRUNCATION_RECOVERY_PROMPT.
After perspective validation, two calls run in parallel for that chunk:
    PSYCHOLOGICAL_ANALYSIS_PROMPT (built from ENRICHMENT_PROMPT):
        canonical scenes + source_type/perspectives + identity_description -> selective emotions/beliefs, at most one character-defining aspect and one independently meaningful goal event per scene.
    TRAIT_INTERPRETATION_PROMPT:
        canonical scenes + authoritative trait meanings -> up to three complete six-field candidates per scene; backend validates trait-specific context.
After all chunks for one source, one optional consolidation call reconciles its
profile events with current character state using typed ordered operations and local
references, checking admission before preserving distinct qualifying properties
and independently meaningful goals. Stage 2 and Stage 4 share
PROFILE_ADMISSION_CONTRACT; rejected candidates are omitted without reclassifying
or rewriting scene perspectives, emotions, or beliefs.
Malformed/duplicate scene candidates are dropped individually;
invalid output envelopes use the bounded validation retry budget. Validated chunk
outputs are checkpointed and reused only when input fingerprints match; truncated
psychological batches split until single scenes. Backend reducers validate and
apply lifecycle/focus rules before acceptance. Trait aggregation remains
deterministic. Prompts do not receive full scene history or produce public output.
"""
import json
from app.jobs.character_agent.trait_evidence_contract import TRAIT_EVIDENCE_CONTRACT
from app.schemas.character_traits import DIRECTIONAL_TRAITS, TRAIT_BY_KEY

# Purpose: Supply only the eight narrative trait meanings and pole descriptions.
# Used by: IDENTITY_DESCRIPTION_PROMPT.
# Expected: Psychological synthesis can describe traits without scoring machinery.
IDENTITY_TRAIT_DESCRIPTION_CONTRACT = (
    "\nEstablished personality dimensions and meanings:\n"
    + json.dumps([
        {
            "name": key,
            "definition": TRAIT_BY_KEY[key].definition,
            "low_pole": TRAIT_BY_KEY[key].left_pole,
            "high_pole": TRAIT_BY_KEY[key].right_pole,
        }
        for key in DIRECTIONAL_TRAITS
    ], ensure_ascii=False)
)
PROMPT_VERSION = "character-embodiment-v37-profile-admission"

# Execution order: Stage 0, once when description is absent and once after
# scene processing to refresh it from the resulting current state.
# Purpose: Synthesize narrative grounding without calculating traits.
# Used by: EmbodyAgent.generate_identity_description.
# Expected: identity_summary, psychological_summary, personality_traits.
IDENTITY_DESCRIPTION_PROMPT = r"""You are constructing the psychological identity of a fictional character.
Create a concise, distinctive portrait that can guide how the character interprets
events, thinks, and behaves. Ground it in the supplied canonical identity and
psychological state. Do not invent history, motivations, relationships, or
experiences. If a current trait value is unknown, do not infer that trait from
the missing value. Numerical values describe tendencies, not absolute rules.

INPUT JSON:
{
  "name": "character name",
  "entity_type": "ontology entity type",
  "entity_descriptor": "entity type descriptor, or null",
  "autogenerated_text": "autogenerated character description, or null",
  "text": "authored character text, or null",
  "properties": [{"name": "property name", "value": "property value"}],
  "goals": [{"name": "goal name", "description": "goal description or null"}],
  "aspects": [{"name": "aspect name", "type": "aspect type", "descriptor": "aspect description or null"}],
  "traits": [{"name": "forbearance", "value": 3}, {"name": "presence", "value": null}]
}

Interpret each input field as follows:
- name, entity_type, entity_descriptor, autogenerated_text, and text describe
  the canonical character and their authored background.
- properties contains named entity properties as name/value pairs.
- goals and aspects describe current psychological state and characterization.
- traits contains one of the eight established trait keys and its current
  integer point value from 1 through 9; null means unknown. The appended trait
  contract explains each dimension and its low/high meanings.

OUTPUT JSON SCHEMA (return exactly this object shape):
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "required": ["identity_summary", "psychological_summary", "personality_traits"],
  "properties": {
    "identity_summary": {"type": "string", "minLength": 1},
    "psychological_summary": {"type": "string", "minLength": 1},
    "personality_traits": {
      "type": "array",
      "items": {"type": "object", "additionalProperties": false,
        "required": ["trait", "description"],
        "properties": {
          "trait": {"enum": ["integrity", "caution", "presence", "forbearance", "diligence", "curiosity", "sharing", "restlessness"]},
          "description": {"type": "string", "minLength": 1}
        }
      }
    }
  }
}

Produce three components:
1. identity_summary: one concise paragraph describing the character's
   background, role, defining characteristics, and what makes them recognizable.
2. psychological_summary: one concise paragraph describing motivations, desires,
   fears, values, internal conflicts, ambitions, and their distinctive outlook.
3. personality_traits: only the character's meaningfully supported dispositions.
   Each description should be brief, specific to this character, and explain how
   that disposition appears in their attitudes or choices.

Write psychologically insightful, natural prose. Prefer distinctive details over
exhaustive coverage. Reflect supported development in the supplied current
state. Do not confuse temporary emotions with enduring dispositions. Avoid
repetition between components. Omit unsupported traits; an empty array is valid.
Return JSON only.""" + IDENTITY_TRAIT_DESCRIPTION_CONTRACT

# Execution order: Stage 1, after Stage 0; run for each chunk before Stage 2/3.
# Stage 1: objective scenes to subjective perspectives.
# Purpose: Extract one grounded subjective perspective per objective scene.
# Used by: EmbodyAgent._incorporate_perspectives, the first chunk call.
# Expected: Ordered JSON perspectives with psychologically grounded subjective text.
PERSPECTIVE_PROMPT = r"""You are incorporating a character's identity into canonical objective scenes.

Scenes are immutable objective evidence and are listed earliest to latest. The
identity object includes identity_description; use it as personality grounding,
not as evidence of behavior in any scene. For
each scene, produce exactly one compact grounded subjective perspective. Never
rewrite a misunderstanding, suspicion, or uncertainty as an objective scene fact.

If the character did not participate in or witness the event, describe only what they
could plausibly know from the available information. If their awareness is not established,
 do not invent memories, emotional reactions, or conclusions.

Use only facts available to the character at each scene. The whole source bundle is
visible to you, but later revelations must never become earlier knowledge.
The backend assigns every canonical scene and evidence_ids reference. Do not return IDs or
evidence references; return one result for each numbered input position. Use
identity_description to understand the character's established outlook while
respecting only facts available at each scene.
Return every perspective in the same order as the input positions. The backend binds
position 1 to the first scene, position 2 to the second, and so on
.

This is compact structured character-state extraction, not narration, roleplay,
a memoir, dialogue, or stream of consciousness. Do not retell the scene.

For every perspective:
- perspective: nonblank, at most 120 words and 900 characters; explain what the experience means to this
  character specifically. Let established personality, values, fears, motivations,
  and beliefs shape what they notice, conclude, and feel. Distinguish what they
  know from what they suspect, and do not present mistaken beliefs as objective
  facts. Describe meaningful internal change when supported by this scene and
  what the character knows; do not reduce the account to an immediate emotion.
  Keep the interpretation grounded and concise without retelling the scene.

INPUT:
{
  "identity": {
    "alias": "name or alias",
    "subtitle": "subtitle or null",
    "entity_type": "ontology type",
    "entity_type_description": "type description or null",
    "properties": {"property": "value"},
    "identity_description": {"identity_summary":"...", "psychological_summary":"...", "personality_traits":[{"trait":"trait key","description":"..."}]}
  },
  "scenes": [
    {"position": 1, "name": "scene name", "description": "scene description", "created_at": "ISO timestamp or null"}
  ],
  "required_output": "one position-bound perspective object as defined below"
}

OUTPUT — return an object with exactly one key "perspectives":
{
  "perspectives": [
    {
      "source_type": "participated | witnessed | heard_about | read_about | inferred | unknown",
      "perspective": "psychologically distinctive subjective account, including supported internal change"
    }
  ]
}

Return JSON only."""


# Execution order: Stage 1 recovery; substitute only when PERSPECTIVE_PROMPT is truncated.
# Purpose: Retry perspective extraction after the first output is truncated.
# Used by: EmbodyAgent._incorporate_perspectives on a truncated response.
# Expected: The same ordered JSON perspectives, within the output budget.
PERSPECTIVE_TRUNCATION_RECOVERY_PROMPT = PERSPECTIVE_PROMPT + r"""

RECOVERY INSTRUCTION: Your previous response exceeded the output budget. Produce
the same required perspectives much more compactly. The exact one-perspective-per-
scene count and every field limit are mandatory. Return JSON only."""


# Purpose: Define one admission boundary for persistent aspect and goal candidates.
# Used by: ENRICHMENT_PROMPT/PSYCHOLOGICAL_ANALYSIS_PROMPT (Stage 2) and
# PSYCHOLOGICAL_CONSOLIDATION_PROMPT (Stage 4), before comparing qualified items.
# Expected: Only character-defining properties and independently meaningful outcomes qualify.
PROFILE_ADMISSION_CONTRACT = r"""
Aspects answer: Who or what is this character?
An aspect is a supported, relatively persistent, character-defining property:
appearance, identity, enduring fear, commitment, relationship, significant
personal circumstance, or established capability. Persistence does not mean
permanence. One explicit revelation can establish a defining fact; repeated
scenes are not required. "I have golden hair", "I fear deep water", and "I am a
manufactured vessel" qualify when established by the source. A temporary
reaction, accepting a confession, or learning a plot clue does not qualify.
One deception does not establish an enduring willingness to lie; one successful
negotiation does not establish a lasting capability. Require evidence of the
defining property itself. "I refuse to be controlled" can express an enduring
conviction. Enduring expertise can qualify as knowledge; knowing the latest
ritual clue alone cannot. A generic "I am very curious" must not duplicate the
existing curiosity trait; a distinctive enduring fixation can qualify.

Goals answer: What does this character want to achieve?
A goal is a supported, personally meaningful outcome with a recognizable
completion condition, whether short-term or enduring. Require independent
significance: would accomplishing it matter to the character beyond merely
advancing another objective? Ordinary actions, tactics, errands, and instrumental
steps do not qualify by themselves. Examining photographs or following a clue
usually advances an investigation rather than establishing another goal.
Different completion conditions alone do not establish independent significance.
Entering the Shadow City can qualify as a separate goal when the source makes
it a significant undertaking in its own right; when it is merely the next route
to a clue, it does not. Do not invent an overarching goal to absorb scene actions.

Apply these admission rules only to profile events and aspect/goal decisions.
Omit rejected candidates; do not reclassify them or rewrite scene perspectives,
emotions, or beliefs. There are no minimum profile counts.
"""

# Execution order: Stage 2 branch, parallel with TRAIT_INTERPRETATION_PROMPT after Stage 1.
# Stage 2 receives canonical scene context and the Stage 1 interpretation.
# Purpose: Define psychological enrichment from canonical scenes and grounded character interpretations.
# Used by: PSYCHOLOGICAL_ANALYSIS_PROMPT for the second scene-chunk call.
# Expected: Ordered JSON enrichments with selective emotions/beliefs and grounded aspect/goal events.
ENRICHMENT_PROMPT = r"""Stage 2 — enrich grounded character perspectives. For every ordered
scene item, use its canonical scene name and description together with the
agent_scene_interpretation source_type and perspective from Stage 1. Use
identity_description as established psychological grounding. Interpret each
scene through what this character knows and how their distinctive personality,
values, fears, motivations, and beliefs shape its meaning. Capture supported
internal changes, not just immediate emotions. Do not contradict canonical
scene facts, treat uncertainty as fact, or let later positions affect earlier
ones. Return exactly one enrichment per input scene, in order.

INPUT JSON:
{"identity_description":{"identity_summary":"...","psychological_summary":"...","personality_traits":[{"trait":"...","description":"..."}]},"scenes":[{"position":1,"scene":{"name":"canonical scene name","description":"canonical scene description"},"agent_scene_interpretation":{"source_type":"participated|witnessed|heard_about|read_about|inferred|unknown","perspective":"the character's subjective interpretation"}}]}

Input meanings: identity_description is the established narrative portrait;
scenes is the ordered list of canonical records, where position binds each item
to its output. scene.name and scene.description are objective source facts;
source_type describes how the character knows the scene and perspective its
subjective meaning. Do not treat interpretation as objective fact or identity
description as proof that a reaction occurred.

Every enrichment MUST contain all three arrays: emotions, beliefs, profile_events.
Use [] when unsupported. Never return scene or evidence IDs; the backend binds
each result to its input scene.

Select one primary emotion and one primary belief when supported. Include a
second emotion or belief only when it is distinct and significant: a separate
reaction or conclusion, not a paraphrase or minor variation of the first.
Do not fill available slots. Unsupported emotions or beliefs must remain [].

Limits per scene: emotions 2, beliefs 2, and at most one profile event of each
kind (one aspect and one goal). Text fields are at
most 240 characters for emotion descriptions and 300 for belief statements or
profile-event descriptions. All text fields must be nonempty.

OUTPUT: {"scene_enrichments":[{"emotions":[{"arousal":0..100,"valence":0..100 (0 negative, 50 neutral, 100 positive),"description":"..."}],"beliefs":[{"statement":"...","confidence":0..100}],"profile_events":[{"kind":"aspect|goal","description":"brief significant evidence-grounded development"}]}]}.

""" + PROFILE_ADMISSION_CONTRACT + r"""
Check aspects independently from goals and emotions for every scene. Emit an
aspect event when canonical scene evidence establishes, reveals, or meaningfully
reinforces a defining fact, including an enduring fact already mentioned in the
identity description. A fact need not first become true in this scene to be
supported by it. Identity description alone is not evidence. Preserve the
concrete fact in the event description, rather than replacing it with a generic
reaction, resolve, or theme. For example, evidence that Ernst is a manufactured
doll with implanted memories supports an identity aspect even if he already
suspects his origin or also resolves to find his maker. A goal or belief about
the revelation does not replace the aspect event. Do not turn every scene detail
into an aspect; require defining, enduring personal significance.
Emit a goal event for a qualifying new objective or supported significant
development/resolution of an existing objective. A step can supply evidence of
progress toward an existing goal without becoming another goal. Preserve explicit
completion, failure, or abandonment in the event description when supported;
do not infer resolution from silence or age.
Emit profile_events only for supported significant developments; use [] when
none exist. There is no minimum number of aspects or goals. Events are
candidates, not final aspects/goals or status changes.
Do not duplicate the subjective perspective or add numerical ratings. Return JSON only."""

# Execution order: Stage 2 call, after perspective validation, parallel with Stage 3.
# Purpose: Apply the enrichment contract to a whole perspective chunk.
# Used by: EmbodyAgent._analyze_psychological_batch after perspectives are bound.
# Expected: One ordered JSON scene_enrichments item per input perspective.
PSYCHOLOGICAL_ANALYSIS_PROMPT = ENRICHMENT_PROMPT + r"""
This is the complete psychological-enrichment stage. Return emotions, beliefs,
and profile_events for every perspective. Each item must cite exactly the current scene conceptually; the
backend assigns evidence_ids by position, so omit them from model output.
"""

# Execution order: Stage 3 branch, parallel with PSYCHOLOGICAL_ANALYSIS_PROMPT after Stage 1.
# Stage 3 receives canonical scene context and authoritative trait definitions;
# prior personality_traits and generated perspectives are excluded.
# Purpose: Classify grounded character-specific trait signals against the directional trait registry.
# Used by: EmbodyAgent._interpret_traits_batch after perspective validation.
# Expected: Ordered JSON scene_trait_interpretations with supported candidates.
TRAIT_INTERPRETATION_PROMPT = r"""Stage 3 — interpret canonical scenes to identify supported trait observations.
INPUT JSON:
{"target":{"alias":"character alias","identity_summary":"narrative background summary","psychological_summary":"motivations, values, fears and outlook summary"},"scenes":[{"position":1,"scene":{"name":"canonical scene name","description":"canonical objective scene description"}}]}

`identity_summary` and `psychological_summary` provide concise context for
interpreting the character's choices. They are not evidence that a disposition
was demonstrated. The target never includes prior `personality_traits`.

Identify personality trait observations for this character
across the supplied chronological scenes.

Traits answer: How does this character tend to behave?
Admit evidence of a behavioral tendency interpreted through the existing trait
definitions. A temporary reaction or isolated outcome is insufficient by itself;
one diagnostic voluntary choice may supply evidence without establishing a
settled trait. Identity facts and established capabilities are not trait signals
by themselves. Use the authoritative meanings below; do not introduce new traits.

Use identity_summary and psychological_summary only as background
for understanding the character. Use canonical scene facts to
identify choices, actions, and explicitly expressed values. The
summaries are not evidence that a trait was demonstrated. Do not
use generated perspectives or prior personality_traits.

For each scene, identify supported observations using
the eight established personality dimensions.

Rules:
- Focus on meaningful voluntary choices, expressed values,
  and clearly demonstrated dispositional responses.
- Interpret behavior within circumstances, knowledge, and
  available alternatives explicitly established by the scene.
- Do not mistake temporary emotions, intentions, or
  experiences for enduring personality dispositions.
- Do not infer traits from identity, role, species, or
  previous personality descriptions.
- Preserve evidence that differs from patterns visible across the supplied scenes.
- Ground every observation and justification in the canonical
  scene. Do not infer unstated motivations or alternatives.
- Consider only this character's own behavior and values.
- Omit compelled, ambiguous, or non-diagnostic evidence.
- Return at most one observation per trait per scene, and no more than three
  trait candidates total per scene. Select only the strongest supported signals.
- Return empty arrays when no meaningful evidence exists.
- Never generate numerical trait values or STEADINESS.
- Preserve scene ordering.


OUTPUT (return exactly one result per input scene in the same order):
{"scene_trait_interpretations":[{"trait_candidates":[{"trait":"one of the eight directional trait keys","diagnostic_situation":"a diagnostic value allowed for that trait, or null","relationship":"friend|enemy|other, or null","stakes":"ordinary|high_stakes, or null","polarity":"low|high","justification":"..."}]}]}

All candidate keys are required and additional keys are forbidden. Each scene may
contain at most three candidates, with at most one candidate for each trait.
`justification` is a nonempty string of at most 360 characters. For a specified
context, diagnostic_situation, relationship, and stakes must all be non-null. For
unspecified context, all three must be null. Allowed diagnostic_situation values
are trait-specific:
""" + json.dumps({key: list(TRAIT_BY_KEY[key].diagnostic_situations) for key in DIRECTIONAL_TRAITS}, ensure_ascii=False) + r"""
The backend constructs the persisted situation_type as
`diagnostic_situation:relationship:stakes`, or `unspecified` when all three
fields are null. Never return a compound situation string. Return JSON only.""" + IDENTITY_TRAIT_DESCRIPTION_CONTRACT + TRAIT_EVIDENCE_CONTRACT


# Execution order: Stage 4, after all Stage 2/3 chunks for one source; skipped without events.
# Purpose: Reconcile evidence, preserving independent aspect facts and goal outcomes.
# Used by: EmbodyAgent._consolidate_profile; backend reducers validate and apply output.
# Expected: Existing-item operations plus self-contained additions with nested chronological changes.
PSYCHOLOGICAL_CONSOLIDATION_PROMPT = r"""Stage 4 — reason about and consolidate one chronological source bundle.
This stage produces internal decisions, not public prose. Use only supplied
identity context, source events in scene order, and current/historical profile
items. Do not infer full scene history. Ignore trivial, temporary, redundant,
ambiguous or unsupported events. Merge equivalent developments rather than
creating duplicate aspects/goals. Each operation needs a short, nonblank
justification and one or more supplied event IDs of the same kind as its list.
The backend validates these decisions and binds all persistence identifiers.

""" + PROFILE_ADMISSION_CONTRACT + r"""
First qualify each event using the admission rules, then compare qualified
properties/outcomes with existing items, and only then add, update, reinforce,
or change status. Stage 2 events are proposals, not proof of qualification.
Reject weak candidates even if Stage 2 proposed them. An event may be omitted
without an operation. Preserve supported significant progress or resolution of
an existing goal without promoting the instrumental step into a separate goal.
Consolidate aspects by the specific proposition they assert, not a shared theme,
category, motivation, or emotional reaction. For every supported aspect event,
compare its concrete fact with the existing aspect's name AND description.
Reinforce only when that same fact is already represented. Use update for a
refinement of the same proposition, preserving its established meaning. Add a
new aspect for an independently meaningful fact not represented by existing
text; do not replace or broaden one aspect into a catch-all character summary.
An update must refine the SAME proposition, not append an independent fact to
the old description. If the existing statement can remain true while the new
fact is false (or vice versa), they are independent and need separate aspects
when both are supported. Do not combine them using "and" merely to avoid an
addition. For example, established expertise in ritual magic and an enduring
refusal to be a pawn are distinct qualifying properties; retain the conviction
and add the expertise with category="knowledge" when supported. Merely learning
a ritual's consequences is not enough to establish that expertise. There is no
one-aspect-per-character, per-source, or per-category limit.
Different aspects can share category="identity" and still be independent.
For example, "I am a manufactured doll with implanted memories" states an
origin fact; "I refuse to be a pawn in someone else's design" states a conviction.
One does not imply the other. If both are evidenced, preserve both. Repeated
revelations that Ernst is a doll or a manufactured vessel with implanted memories
can consolidate into ONE origin aspect whose text retains those concrete facts.
Similarly, belonging to a circle and established ritual expertise are different
properties even if both inform the same investigation.
An existing aspect "I refuse to be a mere wake in someone else's ledger", with
a description about being more than traces in another's design, does not already
state either "I am a manufactured doll" or "I am an expert in ritual magic".
Do not attribute these facts to that existing text.
Before reinforce, check whether a reader could recover the event's defining
fact from the target name/description WITHOUT the new event, identity_description,
justification, or assumed subtext. If not, a null-content reinforcement loses
information: add the independent fact instead. A related revelation does not by
itself prove an existing conviction was reaffirmed; require direct evidence for
any parallel reinforcement. Apply this check to each proposed aspect operation
before returning the final JSON.
Do not consume a new fact through a reinforce operation with null content unless
the target already states it. Justification and evidence links do not substitute
for preserving the fact in the aspect's name or description. Do not omit a
supported defining fact solely because identity_description already mentions it
or because the event also supports a goal or belief. Ignore unsupported or
temporary material and merge true paraphrases; do not aim for any aspect count.

Shared motivation is not an equivalent objective. Compare intended outcomes
and completion conditions before merging qualifying goals. Preserve an
independently meaningful new objective even when it contributes to an existing
motivation.
For example, "Enter the Shadow City" and "Discover who made Ernst" may share a
motivation and remain separate goals when the source establishes independent
significance for both, rather than only different completion conditions.
"Identify my maker" and "Discover who made me" describe
the same outcome and should reinforce or update one goal rather than duplicate
it. Do not split mere paraphrases into separate goals. Evidence determines the
number of aspects/goals; there are no minimum counts, and empty arrays are valid.

INPUT JSON:
{"identity_description":{"identity_summary":"...","psychological_summary":"...","personality_traits":[{"trait":"trait key","description":"..."}]},"events":[{"id":"event-001","kind":"aspect|goal","description":"source evidence"}],"aspects":[{"index":1,"name":"I ...","description":"text or null","category":"category","status":"active|inactive","in_focus":true}],"goals":[{"index":1,"title":"...","description":"text or null","goal_type":"type","status":"active|completed|abandoned|superseded","in_focus":true}]}
identity_description may be null. Its summaries describe established narrative
context, never evidence of a new event. Each input array may be empty. Events
have backend-assigned source-local IDs; copy only supplied IDs. Profile index is
a one-based integer identifying the exact item in its own input array. Historical
inactive/resolved/out-of-focus items are included for comparison and reactivation.

OUTPUT JSON — all six arrays are required and may be empty:
{"consolidation":{"aspect_operations":[],"goal_operations":[],"new_aspects":[],"new_goals":[],"focused_aspects":[],"focused_goals":[]}}

Existing items use ordered aspect_operations and goal_operations. Every target
has exactly {"scope":"existing","index":1}, a one-based index into the matching
input array. Existing operations are update, reinforce, or status. Update and
reinforce carry target, content fields (null preserves current content),
justification, and nonempty event_references. Update must change at least one
content field. Status carries target, status, justification, and event_references.
Aspect content keys are name, description, category; statuses are active/inactive.
Goal content keys are title, description, goal_type; statuses are
active/completed/abandoned/superseded. Status cannot be combined with content.

New items are self-contained objects in new_aspects/new_goals and have no target
reference. An item added in this response has no existing-item index: "existing"
always refers to the original input array, never the first new addition. Combine
repeated evidence for a new aspect in that addition's event_references rather
than reinforcing an unrelated existing item. Example new aspect retaining a defining fact:
{"name":"I am a manufactured doll","description":"My memories were implanted during molding.","category":"identity","in_focus":true,"justification":"The supplied aspect events reveal this origin.","event_references":["event-001"],"changes":[]}
Example new goal with chronological history:
{"title":"Discover the conspiracy","description":"text or null","goal_type":"objective","in_focus":false,"justification":"...","event_references":["event-001"],"changes":[{"operation":"status","status":"completed","justification":"...","event_references":["event-005"]}]}
New aspect base fields are name (must start with "I "), description, category,
in_focus, justification, event_references, and changes. New goal base fields are
title, description, goal_type, in_focus, justification, event_references, and
changes. Each change is an ordered update/reinforce with content fields, or a
status transition, each with justification and nonempty event_references. Changes
apply only to their enclosing new item. Additions start active; the backend
materializes one add followed by each listed change in order. The item's in_focus
is its final focus preference and applies only if its final status is active.

Focus arrays select only pre-existing items and each element has exactly
{"scope":"existing","index":1}. Update changes material content; reinforce
records evidence without duplication and may preserve content with null. Explicit
reactivation is allowed. Every field shown in these shapes is required, nullable
fields may be null as described, and no extra keys are allowed. Never return
canonical IDs, candidate_id, target_id, scene IDs, evidence IDs, or numeric event
references. Never invent events or existing targets. Event references must be
supplied IDs of the matching kind. Operations execute in list order. The backend
validates transitions and final focus after materializing the complete sequence.

Never resolve a goal because it is absent or old. Never deactivate an enduring
fact solely because it is old. Focus is independent of lifecycle and must contain
unique references to at most ten final active aspects and ten final active goals.
Unresolved active items may leave focus without status change. Focus does not
delete history. Only goal events support goal operations; only aspect events
support aspect operations. Valid references alone do not prove completion: require
clear supporting evidence before selecting a lifecycle change.

Limits: names/titles 1–255 characters, descriptions at most 1000, nonblank
justifications 1–500. Aspect names must begin with "I ". All reference indexes
are positive JSON integers (never strings, booleans or fractions). Event reference
arrays are nonempty arrays of supplied ID strings. No member of any required
array may be null. Return one complete JSON document only."""
