"""Prompt contracts in CharacterAgent embodiment execution order.

IDENTITY_DESCRIPTION_PROMPT resolves narrative grounding when absent and
refreshes it after embodiment; it never supplies numerical trait evidence.
For each source scene chunk, PERSPECTIVE_PROMPT runs first:
    objective scenes -> psychologically distinctive subjective perspectives.
    A truncated response retries with PERSPECTIVE_TRUNCATION_RECOVERY_PROMPT.
After perspective validation, two calls run in parallel for that chunk:
    PSYCHOLOGICAL_ANALYSIS_PROMPT (built from ENRICHMENT_PROMPT):
        canonical scenes + source_type/perspectives + identity_description -> emotions, beliefs, profile_events.
    TRAIT_INTERPRETATION_PROMPT:
        canonical scenes + authoritative trait meanings -> candidates.
After all chunks for one source, one optional consolidation call reconciles its
profile events with current character state using typed ordered operations and local
references. Every stage shares a bounded validation retry budget; truncated
psychological batches split until single scenes. Backend reducers validate and
apply lifecycle/focus rules before acceptance. Trait aggregation remains
deterministic. Prompts do not receive full scene history or produce public output.
"""
import json
from app.jobs.character_agent.trait_evidence_contract import TRAIT_EVIDENCE_CONTRACT
from app.schemas.character_traits import DIRECTIONAL_TRAITS, TRAIT_BY_KEY

# Purpose: Supply only the eight narrative trait meanings and pole descriptions.
# Used by: IDENTITY_DESCRIPTION_PROMPT.
# Expected: Psychological synthesis can describe traits without scoring machinery.
IDENTITY_TRAIT_DESCRIPTION_CONTRACT = (
    "\nEstablished personality dimensions and meanings:\n"
    + json.dumps([
        {
            "name": key,
            "definition": TRAIT_BY_KEY[key].definition,
            "low_pole": TRAIT_BY_KEY[key].left_pole,
            "high_pole": TRAIT_BY_KEY[key].right_pole,
        }
        for key in DIRECTIONAL_TRAITS
    ], ensure_ascii=False)
)
PROMPT_VERSION = "character-embodiment-v31-validated-consolidation"

# Execution order: Stage 0, once when description is absent and once after
# scene processing to refresh it from the resulting current state.
# Purpose: Synthesize narrative grounding without calculating traits.
# Used by: EmbodyAgent.generate_identity_description.
# Expected: identity_summary, psychological_summary, personality_traits.
IDENTITY_DESCRIPTION_PROMPT = r"""You are constructing the psychological identity of a fictional character.
Create a concise, distinctive portrait that can guide how the character interprets
events, thinks, and behaves. Ground it in the supplied canonical identity and
psychological state. Do not invent history, motivations, relationships, or
experiences. If a current trait value is unknown, do not infer that trait from
the missing value. Numerical values describe tendencies, not absolute rules.

INPUT JSON:
{
  "name": "character name",
  "entity_type": "ontology entity type",
  "entity_descriptor": "entity type descriptor, or null",
  "autogenerated_text": "autogenerated character description, or null",
  "text": "authored character text, or null",
  "properties": [{"name": "property name", "value": "property value"}],
  "goals": [{"name": "goal name", "description": "goal description or null"}],
  "aspects": [{"name": "aspect name", "type": "aspect type", "descriptor": "aspect description or null"}],
  "traits": [{"name": "forbearance", "value": 3}, {"name": "presence", "value": null}]
}

Interpret each input field as follows:
- name, entity_type, entity_descriptor, autogenerated_text, and text describe
  the canonical character and their authored background.
- properties contains named entity properties as name/value pairs.
- goals and aspects describe current psychological state and characterization.
- traits contains one of the eight established trait keys and its current
  integer point value from 1 through 9; null means unknown. The appended trait
  contract explains each dimension and its low/high meanings.

OUTPUT JSON SCHEMA (return exactly this object shape):
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "required": ["identity_summary", "psychological_summary", "personality_traits"],
  "properties": {
    "identity_summary": {"type": "string", "minLength": 1},
    "psychological_summary": {"type": "string", "minLength": 1},
    "personality_traits": {
      "type": "array",
      "items": {"type": "object", "additionalProperties": false,
        "required": ["trait", "description"],
        "properties": {
          "trait": {"enum": ["integrity", "caution", "presence", "forbearance", "diligence", "curiosity", "sharing", "restlessness"]},
          "description": {"type": "string", "minLength": 1}
        }
      }
    }
  }
}

Produce three components:
1. identity_summary: one concise paragraph describing the character's
   background, role, defining characteristics, and what makes them recognizable.
2. psychological_summary: one concise paragraph describing motivations, desires,
   fears, values, internal conflicts, ambitions, and their distinctive outlook.
3. personality_traits: only the character's meaningfully supported dispositions.
   Each description should be brief, specific to this character, and explain how
   that disposition appears in their attitudes or choices.

Write psychologically insightful, natural prose. Prefer distinctive details over
exhaustive coverage. Reflect supported development in the supplied current
state. Do not confuse temporary emotions with enduring dispositions. Avoid
repetition between components. Omit unsupported traits; an empty array is valid.
Return JSON only.""" + IDENTITY_TRAIT_DESCRIPTION_CONTRACT

# Execution order: Stage 1, after Stage 0; run for each chunk before Stage 2/3.
# Stage 1: objective scenes to subjective perspectives.
# Purpose: Extract one grounded subjective perspective per objective scene.
# Used by: EmbodyAgent._incorporate_perspectives, the first chunk call.
# Expected: Ordered JSON perspectives with psychologically grounded subjective text.
PERSPECTIVE_PROMPT = r"""You are incorporating a character's identity into canonical objective scenes.

Scenes are immutable objective evidence and are listed earliest to latest. The
identity object includes identity_description; use it as personality grounding,
not as evidence of behavior in any scene. For
each scene, produce exactly one compact grounded subjective perspective. Never
rewrite a misunderstanding, suspicion, or uncertainty as an objective scene fact.

If the character did not participate in or witness the event, describe only what they
could plausibly know from the available information. If their awareness is not established,
 do not invent memories, emotional reactions, or conclusions.

Use only facts available to the character at each scene. The whole source bundle is
visible to you, but later revelations must never become earlier knowledge.
The backend assigns every canonical scene and evidence_ids reference. Do not return IDs or
evidence references; return one result for each numbered input position. Use
identity_description to understand the character's established outlook while
respecting only facts available at each scene.
Return every perspective in the same order as the input positions. The backend binds
position 1 to the first scene, position 2 to the second, and so on
.

This is compact structured character-state extraction, not narration, roleplay,
a memoir, dialogue, or stream of consciousness. Do not retell the scene.

For every perspective:
- perspective: nonblank, at most 120 words and 900 characters; explain what the experience means to this
  character specifically. Let established personality, values, fears, motivations,
  and beliefs shape what they notice, conclude, and feel. Distinguish what they
  know from what they suspect, and do not present mistaken beliefs as objective
  facts. Describe meaningful internal change when supported by this scene and
  what the character knows; do not reduce the account to an immediate emotion.
  Keep the interpretation grounded and concise without retelling the scene.

INPUT:
{
  "identity": {
    "alias": "name or alias",
    "subtitle": "subtitle or null",
    "entity_type": "ontology type",
    "entity_type_description": "type description or null",
    "properties": {"property": "value"},
    "identity_description": {"identity_summary":"...", "psychological_summary":"...", "personality_traits":[{"trait":"trait key","description":"..."}]}
  },
  "scenes": [
    {"position": 1, "name": "scene name", "description": "scene description", "created_at": "ISO timestamp or null"}
  ],
  "required_output": "one position-bound perspective object as defined below"
}

OUTPUT — return an object with exactly one key "perspectives":
{
  "perspectives": [
    {
      "source_type": "participated | witnessed | heard_about | read_about | inferred | unknown",
      "perspective": "psychologically distinctive subjective account, including supported internal change"
    }
  ]
}

Return JSON only."""


# Execution order: Stage 1 recovery; substitute only when PERSPECTIVE_PROMPT is truncated.
# Purpose: Retry perspective extraction after the first output is truncated.
# Used by: EmbodyAgent._incorporate_perspectives on a truncated response.
# Expected: The same ordered JSON perspectives, within the output budget.
PERSPECTIVE_TRUNCATION_RECOVERY_PROMPT = PERSPECTIVE_PROMPT + r"""

RECOVERY INSTRUCTION: Your previous response exceeded the output budget. Produce
the same required perspectives much more compactly. The exact one-perspective-per-
scene count and every field limit are mandatory. Return JSON only."""


# Execution order: Stage 2 branch, parallel with TRAIT_INTERPRETATION_PROMPT after Stage 1.
# Stage 2 receives canonical scene context and the Stage 1 interpretation.
# Purpose: Define psychological enrichment from canonical scenes and grounded character interpretations.
# Used by: PSYCHOLOGICAL_ANALYSIS_PROMPT for the second scene-chunk call.
# Expected: Ordered JSON enrichments with emotions, beliefs, and profile events.
ENRICHMENT_PROMPT = r"""Stage 2 — enrich grounded character perspectives. For every ordered
scene item, use its canonical scene name and description together with the
agent_scene_interpretation source_type and perspective from Stage 1. Use
identity_description as established psychological grounding. Interpret each
scene through what this character knows and how their distinctive personality,
values, fears, motivations, and beliefs shape its meaning. Capture supported
internal changes, not just immediate emotions. Do not contradict canonical
scene facts, treat uncertainty as fact, or let later positions affect earlier
ones. Return exactly one enrichment per input scene, in order.

INPUT JSON:
{"identity_description":{"identity_summary":"...","psychological_summary":"...","personality_traits":[{"trait":"...","description":"..."}]},"scenes":[{"position":1,"scene":{"name":"canonical scene name","description":"canonical scene description"},"agent_scene_interpretation":{"source_type":"participated|witnessed|heard_about|read_about|inferred|unknown","perspective":"the character's subjective interpretation"}}]}

Input meanings: identity_description is the established narrative portrait;
scenes is the ordered list of canonical records, where position binds each item
to its output. scene.name and scene.description are objective source facts;
source_type describes how the character knows the scene and perspective its
subjective meaning. Do not treat interpretation as objective fact or identity
description as proof that a reaction occurred.

Every enrichment MUST contain all three arrays: emotions, beliefs, profile_events.
Use [] when unsupported. Never return scene or evidence IDs; the backend binds
each result to its input scene.

Limits per scene: emotions 2, beliefs 2, profile_events 2. Text fields are at
most 240 characters for emotion descriptions and 300 for belief statements or
profile-event descriptions. All text fields must be nonempty.

OUTPUT: {"scene_enrichments":[{"emotions":[{"arousal":0..100,"valence":0..100 (0 negative, 50 neutral, 100 positive),"description":"..."}],"beliefs":[{"statement":"...","confidence":0..100}],"profile_events":[{"kind":"aspect|goal","description":"brief significant evidence-grounded development"}]}]}.

Most scenes should produce no profile_events. Include only significant identity
revelations, lasting circumstances, genuine personal commitments, or meaningful
resolutions. Events are candidates, not final aspects/goals or status changes.
Do not duplicate the subjective perspective or add numerical ratings. Return JSON only."""

# Execution order: Stage 2 call, after perspective validation, parallel with Stage 3.
# Purpose: Apply the enrichment contract to a whole perspective chunk.
# Used by: EmbodyAgent._analyze_psychological_batch after perspectives are bound.
# Expected: One ordered JSON scene_enrichments item per input perspective.
PSYCHOLOGICAL_ANALYSIS_PROMPT = ENRICHMENT_PROMPT + r"""
This is the complete psychological-enrichment stage. Return emotions, beliefs,
and profile_events for every perspective. Each item must cite exactly the current scene conceptually; the
backend assigns evidence_ids by position, so omit them from model output.
"""

# Execution order: Stage 3 branch, parallel with PSYCHOLOGICAL_ANALYSIS_PROMPT after Stage 1.
# Stage 3 receives canonical scene context and authoritative trait definitions;
# prior personality_traits and generated perspectives are excluded.
# Purpose: Classify grounded character-specific trait signals against the directional trait registry.
# Used by: EmbodyAgent._interpret_traits_batch after perspective validation.
# Expected: Ordered JSON scene_trait_interpretations with supported candidates.
TRAIT_INTERPRETATION_PROMPT = r"""Stage 3 — interpret canonical scenes to identify supported trait observations.
INPUT JSON:
{"target":{"alias":"character alias","identity_summary":"narrative background summary","psychological_summary":"motivations, values, fears and outlook summary"},"scenes":[{"position":1,"scene":{"name":"canonical scene name","description":"canonical objective scene description"}}]}

`identity_summary` and `psychological_summary` provide concise context for
interpreting the character's choices. They are not evidence that a disposition
was demonstrated. The target never includes prior `personality_traits`.

Identify personality trait observations for this character
across the supplied chronological scenes.

Use identity_summary and psychological_summary only as background
for understanding the character. Use canonical scene facts to
identify choices, actions, and explicitly expressed values. The
summaries are not evidence that a trait was demonstrated. Do not
use generated perspectives or prior personality_traits.

For each scene, identify supported observations using
the eight established personality dimensions.

Rules:
- Focus on meaningful voluntary choices, expressed values,
  and clearly demonstrated dispositional responses.
- Interpret behavior within circumstances, knowledge, and
  available alternatives explicitly established by the scene.
- Do not mistake temporary emotions, intentions, or
  experiences for enduring personality dispositions.
- Do not infer traits from identity, role, species, or
  previous personality descriptions.
- Preserve evidence that differs from patterns visible across the supplied scenes.
- Ground every observation and justification in the canonical
  scene. Do not infer unstated motivations or alternatives.
- Consider only this character's own behavior and values.
- Omit compelled, ambiguous, or non-diagnostic evidence.
- Return at most one observation per trait per scene.
- Return empty arrays when no meaningful evidence exists.
- Never generate numerical trait values or STEADINESS.
- Preserve scene ordering.


OUTPUT JSON SCHEMA (return exactly this object shape, with one result per input scene in the same order):
{
  "type": "object",
  "additionalProperties": false,
  "required": ["scene_trait_interpretations"],
  "properties": {
    "scene_trait_interpretations": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["trait_candidates"],
        "properties": {
          "trait_candidates": {
            "type": "array",
            "maxItems": 8,
            "items": {
              "type": "object",
              "additionalProperties": false,
              "required": ["trait", "polarity", "situation_type", "justification"],
              "properties": {
                "trait": {"enum": ["integrity", "caution", "presence", "forbearance", "diligence", "curiosity", "sharing", "restlessness"]},
                "polarity": {"enum": ["low", "high"]},
                "situation_type": {"type": "string", "minLength": 1, "maxLength": 80, "description": "diagnostic:relationship:stakes or unspecified; use the diagnostic values and rules below"},
                "justification": {"type": "string", "minLength": 1, "maxLength": 360}
              }
            }
          }
        }
      }
    }
  }
}
Return JSON only.""" + IDENTITY_TRAIT_DESCRIPTION_CONTRACT + TRAIT_EVIDENCE_CONTRACT


# Execution order: Stage 4, after all Stage 2/3 chunks for one source; skipped without events.
# Purpose: Reconcile source-local evidence with existing and historical profile items.
# Used by: EmbodyAgent._consolidate_profile; backend reducers validate and apply output.
# Expected: Typed ordered aspect/goal operations and local focus references; no backend IDs.
PSYCHOLOGICAL_CONSOLIDATION_PROMPT = r"""Stage 4 — reason about and consolidate one chronological source bundle.
This stage produces internal decisions, not public prose. Use only supplied
identity context, source events in scene order, and current/historical profile
items. Do not infer full scene history. Ignore trivial, temporary, redundant,
ambiguous or unsupported events. Merge equivalent developments rather than
creating duplicate aspects/goals. Each operation needs a short, nonblank
justification and one or more supplied event IDs of the same kind as its list.
The backend validates these decisions and binds all persistence identifiers.

INPUT JSON:
{"identity_description":{"identity_summary":"...","psychological_summary":"...","personality_traits":[{"trait":"trait key","description":"..."}]},"events":[{"id":"event-001","kind":"aspect|goal","description":"source evidence"}],"aspects":[{"index":1,"name":"I ...","description":"text or null","category":"category","status":"active|inactive","in_focus":true}],"goals":[{"index":1,"title":"...","description":"text or null","goal_type":"type","status":"active|completed|abandoned|superseded","in_focus":true}]}
identity_description may be null. Its summaries describe established narrative
context, never evidence of a new event. Each input array may be empty. Events
have backend-assigned source-local IDs; copy only supplied IDs. Profile index is
a one-based integer identifying the exact item in its own input array. Historical
inactive/resolved/out-of-focus items are included for comparison and reactivation.

OUTPUT JSON — all four arrays are required and may be empty:
{"consolidation":{"aspect_operations":[],"goal_operations":[],"focused_aspects":[],"focused_goals":[]}}

Each operation must be exactly one of the following shapes. All listed keys are
required, no extra keys are allowed. A nullable content field explicitly set to
null on update/reinforce means preserve its current value.
Aspect add:
{"operation":"add","name":"I am a defining first-person statement","description":"text or null","category":"identity|role|status|physical|capability|knowledge|preference|attitude|history","justification":"...","event_references":["event-001"]}
Aspect update:
{"operation":"update","target":{"scope":"existing|new","index":1},"name":"I ... or null","description":"text or null","category":"identity|role|status|physical|capability|knowledge|preference|attitude|history|null","justification":"...","event_references":["event-001"]}
Aspect reinforce:
{"operation":"reinforce","target":{"scope":"existing|new","index":1},"name":"I ... or null","description":"text or null","category":"identity|role|status|physical|capability|knowledge|preference|attitude|history|null","justification":"...","event_references":["event-001"]}
Aspect status:
{"operation":"status","target":{"scope":"existing|new","index":1},"status":"active|inactive","justification":"...","event_references":["event-001"]}
Goal add:
{"operation":"add","title":"...","description":"text or null","goal_type":"desire|objective|ambition|obligation|avoidance|survival","justification":"...","event_references":["event-001"]}
Goal update:
{"operation":"update","target":{"scope":"existing|new","index":1},"title":"text or null","description":"text or null","goal_type":"desire|objective|ambition|obligation|avoidance|survival|null","justification":"...","event_references":["event-001"]}
Goal reinforce:
{"operation":"reinforce","target":{"scope":"existing|new","index":1},"title":"text or null","description":"text or null","goal_type":"desire|objective|ambition|obligation|avoidance|survival|null","justification":"...","event_references":["event-001"]}
Goal status:
{"operation":"status","target":{"scope":"existing|new","index":1},"status":"active|completed|abandoned|superseded","justification":"...","event_references":["event-001"]}

Each focus element has exactly {"scope":"existing|new","index":1}.
Scope existing addresses the input array of the matching kind. Scope new
addresses the one-based occurrence of an add in that kind's operation list.
For operations, a new target must have been added earlier in the same list.
Focus may reference any addition after all operations are applied. Never return
canonical IDs, candidate_id, target_id, scene IDs, evidence IDs, or numeric event
references. Never invent an event or target; no forward operation references.

Operations execute in list order. Additions start active without a status field.
An item introduced and resolved in this source needs add then status operations,
using scope new and the same new index. Update changes material content and must
supply at least one non-null content field. Reinforce records further evidence
without duplication; preserve content with null unless a supported refinement
exists. Neither update nor reinforce can contain status. Status operations
contain no content fields. An existing item's name/title is not required on
status; the backend supplies it. Explicit reactivation to active is permitted.

Never resolve a goal because it is absent or old. Never deactivate an enduring
fact solely because it is old. Focus is independent of lifecycle and must contain
unique references to at most ten final active aspects and ten final active goals.
Unresolved active items may leave focus without status change. Focus does not
delete history. Only goal events support goal operations; only aspect events
support aspect operations. Valid references alone do not prove completion: require
clear supporting evidence before selecting a lifecycle change.

Limits: names/titles 1–255 characters, descriptions at most 1000, nonblank
justifications 1–500. Aspect names must begin with "I ". All reference indexes
are positive JSON integers (never strings, booleans or fractions). Event reference
arrays are nonempty arrays of supplied ID strings. No member of any required
array may be null. Return one complete JSON document only."""
