"""Evidence collection and SQL review lifecycle for CharacterAgent embodiment."""

from __future__ import annotations

import json
from datetime import date, datetime, time, timezone
from typing import Any
from uuid import uuid4

from fastapi import HTTPException
from neo4j.time import Date, DateTime, Duration, Time
from sqlalchemy import select

from app.models.character_embodiment import CharacterEmbodimentDraft, CharacterEmbodimentDraftStatus
from app.models.ontology import (
    OntologyEntity, OntologyProperty, PropertyDataType,
)
from app.schemas.character_agent import (
    BEHAVIOURAL_AXES,
    EmbodimentDraftRead,
    EmbodimentEvidence,
    EmbodimentProposal,
    CharacterSourceGroup,
    SourceSceneInput,
)


def _json(value: str | None, default: Any) -> Any:
    if not value:
        return default
    try:
        return json.loads(value)
    except (TypeError, ValueError):
        return default


def _dump(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"), default=str)


def _json_safe(value: Any) -> Any:
    """Normalize graph values before they enter evidence or LLM payloads."""
    if isinstance(value, (DateTime, datetime, Date, date, Time, time)):
        return value.isoformat()
    if isinstance(value, Duration):
        return str(value)
    if isinstance(value, dict):
        return {str(key): _json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(item) for item in value]
    return value


class CharacterEmbodimentService:
    def __init__(self, sql_session, graph_session):
        self.sql = sql_session
        self.graph = graph_session

    @staticmethod
    def pack_evidence(
        evidence: list[EmbodimentEvidence], token_budget: int
    ) -> list[EmbodimentEvidence]:
        """Pack evidence with the provider-neutral ten-characters-per-token budget."""
        char_budget = max(10_000, token_budget * 10)
        packed: list[EmbodimentEvidence] = []
        used = 0
        for item in evidence:
            size = len(item.text)
            if packed and used + size > char_budget:
                continue
            if not packed and size > char_budget:
                item = item.model_copy(update={"text": item.text[:char_budget]})
                size = len(item.text)
            packed.append(item)
            used += size
        return packed

    async def collect_evidence(
        self, ontology_id: int, entity_id: str, *, token_budget: int
    ) -> tuple[dict[str, Any], list[EmbodimentEvidence], str]:
        entity_row = await (await self.graph.run(
            """
            MATCH (entity:EntityInstance {entity_instance_id:$entity_id})
            OPTIONAL MATCH (instance:OntologyInstance)-[:HAS_ENTITY]->(entity)
            RETURN entity, instance.instance_id AS instance_id
            """, entity_id=entity_id,
        )).single()
        if not entity_row:
            raise HTTPException(status_code=404, detail="EntityInstance not found")
        entity = _json_safe(dict(entity_row["entity"]))
        if int(entity.get("ontology_id") or 0) != ontology_id:
            raise HTTPException(status_code=400, detail="EntityInstance does not belong to ontology")

        definition_id = int(entity.get("entity_definition_id") or 0)
        definition = await self.sql.scalar(select(OntologyEntity).where(
            OntologyEntity.id == definition_id, OntologyEntity.ontology_id == ontology_id
        ))
        if not definition:
            raise HTTPException(status_code=409, detail="EntityInstance definition is unavailable")
        property_rows = await self.sql.execute(
            select(OntologyProperty).where(OntologyProperty.entity_id == definition_id)
        )
        properties = list(property_rows.scalars().all())
        property_names = {str(item.id): item.name for item in properties}
        raw_properties = _json(entity.get("properties"), {})
        property_image = next((
            raw_properties.get(str(item.id))
            for item in properties
            if item.data_type == PropertyDataType.IMAGE
            and isinstance(raw_properties.get(str(item.id)), str)
            and raw_properties.get(str(item.id)).strip()
        ), None)
        canonical = {
            "entity_instance_id": entity_id,
            "alias": str(entity.get("alias") or entity_id),
            "avatar_url": entity.get("node_avatar_url") or property_image,
            "authored_text": entity.get("text"),
            "generated_text": entity.get("autogenerated_text"),
            "entity_type": definition.name,
            "entity_type_description": definition.description,
            "properties": {
                property_names.get(str(key), str(key)): value
                for key, value in raw_properties.items()
            },
        }
        evidence: list[EmbodimentEvidence] = [
            EmbodimentEvidence(
                evidence_id=f"identity:{entity_id}:alias", kind="identity",
                source_id=entity_id, text=f"Canonical alias: {canonical['alias']}",
                provenance={"field": "alias"},
            ),
            EmbodimentEvidence(
                evidence_id=f"identity:{entity_id}:ontology-type", kind="identity",
                source_id=entity_id,
                text=_dump({
                    "name": definition.name,
                    "description": definition.description,
                }),
                provenance={
                    "field": "entity_type",
                    "entity_definition_id": definition_id,
                },
            )
        ]
        for key, value in canonical["properties"].items():
            if value not in (None, "", [], {}):
                evidence.append(EmbodimentEvidence(
                    evidence_id=f"property:{entity_id}:{key}", kind="property",
                    source_id=entity_id, text=f"{key}: {value}",
                    provenance={"property_name": key},
                ))
        if canonical["authored_text"]:
            evidence.append(EmbodimentEvidence(
                evidence_id=f"text:{entity_id}:authored", kind="identity",
                source_id=entity_id, text=str(canonical["authored_text"]),
                provenance={"field": "text", "generated": False},
            ))
        if canonical["generated_text"]:
            evidence.append(EmbodimentEvidence(
                evidence_id=f"text:{entity_id}:autogenerated", kind="identity",
                source_id=entity_id, text=str(canonical["generated_text"]),
                provenance={"field": "autogenerated_text", "generated": True},
            ))

        scenes = await self.graph.run(
            """
            MATCH (scene:Scene)-[entity_rel:RELATES_TO]->
                  (entity:EntityInstance {entity_instance_id:$entity_id})
            RETURN scene.id AS id, scene.name AS name,
                   scene.description AS description,
                   properties(entity_rel) AS entity_relation,
                   scene.created_at AS created_at, properties(scene) AS props
            ORDER BY coalesce(toString(created_at), ''), id
            """, entity_id=entity_id,
        )
        cutoff = datetime.now(timezone.utc).isoformat()
        async for row in scenes:
            created = str(row["created_at"] or "")
            evidence.append(EmbodimentEvidence(
                evidence_id=f"scene:{row['id']}", kind="scene", source_id=str(row["id"]),
                text=f"{row['name']}: {row['description']}",
                occurred_at=created or None,
                provenance={
                    "entity_relation": _json_safe(dict(row.get("entity_relation") or {})),
                    "properties": _json_safe(dict(row["props"] or {})),
                },
            ))

        return canonical, self.pack_evidence(evidence, token_budget), cutoff

    async def collect_projection_evidence(
        self, ontology_id: int, entity_id: str, *, token_budget: int
    ) -> tuple[dict[str, Any], list[EmbodimentEvidence], list[CharacterSourceGroup], str]:
        """Separate entity seed evidence from chronologically grouped Scene inputs."""
        canonical, all_evidence, cutoff = await self.collect_evidence(
            ontology_id, entity_id, token_budget=token_budget
        )
        entity_evidence = [item for item in all_evidence if item.kind != "scene"]
        rows = await self.graph.run(
            """
            MATCH (scene:Scene)-[:DERIVED_FROM]->(source:EntityInstance)
            WHERE EXISTS {
              MATCH (scene)-[:RELATES_TO]->
                    (:EntityInstance {entity_instance_id:$entity_id})
            } OR EXISTS {
              MATCH (scene)-[:CONTAINS]->(:Milestone)-[:RELATES_TO]->
                    (:EntityInstance {entity_instance_id:$entity_id})
            }
            OPTIONAL MATCH (scene)-[entity_rel:RELATES_TO]->
                           (:EntityInstance {entity_instance_id:$entity_id})
            RETURN source.entity_instance_id AS source_id,
                   coalesce(source.alias, source.entity_instance_id) AS source_name,
                   source.created_at AS source_created_at,
                   scene.id AS scene_id, scene.name AS scene_name,
                   scene.description AS scene_description,
                   scene.created_at AS scene_created_at,
                   properties(entity_rel) AS entity_relation
            ORDER BY coalesce(toString(source_created_at), toString(scene_created_at), ''),
                     source_id, coalesce(toString(scene_created_at), ''), scene_id
            """,
            entity_id=entity_id,
        )
        grouped: dict[str, dict[str, Any]] = {}
        async for row in rows:
            source_id = str(row["source_id"])
            group = grouped.setdefault(source_id, {
                "source_group_id": source_id,
                "source_name": str(row["source_name"] or source_id),
                "source_created_at": (
                    str(row["source_created_at"]) if row["source_created_at"] else None
                ),
                "scenes": [],
            })
            group["scenes"].append(SourceSceneInput(
                scene_id=str(row["scene_id"]),
                title=str(row["scene_name"] or row["scene_id"]),
                description=str(row["scene_description"] or ""),
                created_at=str(row["scene_created_at"]) if row["scene_created_at"] else None,
                entity_relation=_json_safe(dict(row["entity_relation"] or {})),
            ))
        groups = [CharacterSourceGroup.model_validate(item) for item in grouped.values()]
        groups.sort(key=lambda group: (
            group.source_created_at
            or next((scene.created_at for scene in group.scenes if scene.created_at), ""),
            group.source_group_id,
        ))
        return canonical, self.pack_evidence(entity_evidence, token_budget), groups, cutoff

    async def load_embodiment_input(
        self, source_entity_id: str, ontology_id: int,
    ) -> dict[str, Any]:
        """Load all data needed by EmbodyAgent for one source group.

        Loads the source entity's canonical identity, finds any existing
        CharacterAgent EMBODYING this entity for current axes/aspects/goals,
        and collects scenes DERIVED_FROM the source entity that involve the
        embodied entity.

        Returns:
          canonical_identity: dict with alias, entity_type, entity_type_description,
                              properties, authored_text, generated_text, avatar_url
          current_axes: dict of 8 axis name -> int value (defaults 50 if no agent)
          current_aspects: list of {name, category, description, importance, intensity}
          current_goals: list of {title, description, goal_type, priority, commitment}
          source_entity_alias: str
          scenes: list of {scene_id, name, description, created_at}
          agent_id: str | None
        """
        # 1. Load the source entity
        entity_row = await (
            await self.graph.run(
                """
                MATCH (entity:EntityInstance {entity_instance_id:$source_id})
                RETURN entity
                """,
                source_id=source_entity_id,
            )
        ).single()
        if not entity_row:
            raise HTTPException(status_code=404, detail="EntityInstance not found")
        entity = _json_safe(dict(entity_row["entity"]))
        if int(entity.get("ontology_id") or 0) != ontology_id:
            raise HTTPException(
                status_code=400, detail="EntityInstance does not belong to ontology"
            )

        # 2. Canonical identity (entity type + property definitions from SQL)
        definition_id = int(entity.get("entity_definition_id") or 0)
        definition = await self.sql.scalar(
            select(OntologyEntity).where(
                OntologyEntity.id == definition_id,
                OntologyEntity.ontology_id == ontology_id,
            )
        )
        if not definition:
            raise HTTPException(
                status_code=409, detail="EntityInstance definition is unavailable"
            )
        property_rows = await self.sql.execute(
            select(OntologyProperty).where(
                OntologyProperty.entity_id == definition_id
            )
        )
        properties_list = list(property_rows.scalars().all())
        property_names = {str(item.id): item.name for item in properties_list}
        raw_properties = _json(entity.get("properties"), {})
        property_image = next(
            (
                raw_properties.get(str(item.id))
                for item in properties_list
                if item.data_type == PropertyDataType.IMAGE
                and isinstance(raw_properties.get(str(item.id)), str)
                and raw_properties.get(str(item.id)).strip()
            ),
            None,
        )
        entity_instance_id = str(
            entity.get("entity_instance_id") or source_entity_id
        )
        canonical_identity = {
            "entity_instance_id": entity_instance_id,
            "alias": str(
                entity.get("alias") or entity.get("entity_instance_id") or source_entity_id
            ),
            "avatar_url": entity.get("node_avatar_url") or property_image,
            "authored_text": entity.get("text"),
            "generated_text": entity.get("autogenerated_text"),
            "entity_type": definition.name,
            "entity_type_description": definition.description,
            "properties": {
                property_names.get(str(key), str(key)): value
                for key, value in raw_properties.items()
            },
        }

        # 3. Check for existing agent, load current axes/aspects/goals
        agent_row = await (
            await self.graph.run(
                """
                OPTIONAL MATCH (agent:CharacterAgent)-[:EMBODIES]->
                              (:EntityInstance {entity_instance_id:$source_id})
                RETURN agent
                """,
                source_id=source_entity_id,
            )
        ).single()
        agent = _json_safe(dict(agent_row["agent"])) if agent_row and agent_row["agent"] else None

        current_axes: dict[str, int] = {}
        if agent:
            for axis in BEHAVIOURAL_AXES:
                current_axes[axis] = int(agent.get(axis, 50))
            if agent.get("subtitle"):
                canonical_identity["subtitle"] = str(agent["subtitle"])
        else:
            for axis in BEHAVIOURAL_AXES:
                current_axes[axis] = 50

        current_aspects: list[dict[str, Any]] = []
        current_goals: list[dict[str, Any]] = []
        agent_id: str | None = None
        if agent:
            agent_id = str(agent.get("id", ""))
            aux = await (
                await self.graph.run(
                    """
                    MATCH (agent:CharacterAgent {id:$agent_id})
                    CALL {
                      WITH agent
                      OPTIONAL MATCH (agent)-[:HAS_ASPECT]->(aspect:CharacterAspect)
                      RETURN collect({
                        id: aspect.id,
                        name: aspect.name,
                        category: aspect.category,
                        description: aspect.description,
                        importance: aspect.importance,
                        intensity: aspect.intensity
                      }) AS aspects
                    }
                    CALL {
                      WITH agent
                      OPTIONAL MATCH (agent)-[:PURSUES]->(goal:CharacterGoal)
                      RETURN collect({
                        id: goal.id,
                        title: goal.title,
                        description: goal.description,
                        goal_type: goal.goal_type,
                        priority: goal.priority,
                        commitment: goal.commitment
                      }) AS goals
                    }
                    RETURN aspects, goals
                    """,
                    agent_id=agent_id,
                )
            ).single()
            if aux:
                current_aspects = [a for a in (aux["aspects"] or []) if a]
                current_goals = [g for g in (aux["goals"] or []) if g]

        # 4. Source entity alias
        source_alias = str(
            entity.get("alias") or entity.get("entity_instance_id") or source_entity_id
        )

        # 5. Scenes RELATED_TO this entity, grouped by DERIVED_FROM source
        scene_rows = await self.graph.run(
            """
            MATCH (scene:Scene)-[:RELATES_TO]->
                  (:EntityInstance {entity_instance_id:$entity_id})
            OPTIONAL MATCH (scene)-[:DERIVED_FROM]->(source:EntityInstance)
            RETURN scene.id AS scene_id,
                   coalesce(scene.name, scene.id) AS name,
                   coalesce(scene.description, '') AS description,
                   toString(scene.created_at) AS created_at,
                   source.entity_instance_id AS source_id,
                   coalesce(source.alias, source.entity_instance_id) AS source_alias
            ORDER BY coalesce(toString(scene.created_at), ''), scene.id
            """,
            entity_id=entity_instance_id,
        )
        scenes: list[dict[str, Any]] = []
        groups: dict[str, dict[str, Any]] = {}
        async for row in scene_rows:
            s = {
                "scene_id": str(row["scene_id"]),
                "name": str(row["name"]),
                "description": str(row["description"]),
                "created_at": str(row["created_at"]) if row["created_at"] else None,
            }
            scenes.append(s)
            gid = str(row["source_id"]) if row["source_id"] else "__orphan__"
            group = groups.get(gid)
            if not group:
                group = {
                    "source_id": str(row["source_id"]) if row["source_id"] else None,
                    "source_alias": str(row["source_alias"]) if row["source_alias"] else "Unknown source",
                    "scenes": [],
                }
                groups[gid] = group
            group["scenes"].append(s)

        source_groups = sorted(
            groups.values(),
            key=lambda g: (
                g["scenes"][0]["created_at"] or "" if g["scenes"] else "",
                g["source_id"] or "",
            ),
        )

        return {
            "canonical_identity": canonical_identity,
            "current_axes": current_axes,
            "current_aspects": current_aspects,
            "current_goals": current_goals,
            "source_entity_alias": source_alias,
            "scenes": scenes,
            "source_groups": source_groups,
            "agent_id": agent_id,
        }

    @staticmethod
    def read(draft: CharacterEmbodimentDraft) -> EmbodimentDraftRead:
        observations = _json(draft.observations, None)
        # A short-lived worker version persisted the optional orchestration
        # field in this public, strict observations payload.  Ignore it when
        # reading those completed drafts so they remain reviewable after the
        # deploy that corrects future writes.
        if isinstance(observations, dict):
            observations.pop("subtitle_change", None)
        return EmbodimentDraftRead(
            id=draft.id, ontology_id=draft.ontology_id, source_entity_id=draft.source_entity_id,
            target_character_agent_id=draft.target_character_agent_id, status=draft.status,
            background_job_id=draft.background_job_id, generation_revision=draft.generation_revision,
            evidence=_json(draft.evidence_snapshot, []),
            source_evidence_ids=_json(draft.source_evidence_ids, []),
            evidence_cutoff=draft.evidence_cutoff,
            observations=observations,
            proposal=_json(draft.generated_proposal, None),
            timeline=_json(draft.timeline_projection, None),
            provider=draft.provider, model=draft.model, prompt_version=draft.prompt_version,
            error_message=draft.error_message, generated_at=draft.generated_at,
            created_at=draft.created_at, updated_at=draft.updated_at,
        )
