"""Evidence collection and SQL review lifecycle for CharacterAgent embodiment."""

from __future__ import annotations

import json
from datetime import date, datetime, time, timezone
from typing import Any
from uuid import uuid4

from fastapi import HTTPException
from neo4j.time import Date, DateTime, Duration, Time
from sqlalchemy import select

from app.models.character_embodiment import CharacterEmbodimentDraft, CharacterEmbodimentDraftStatus
from app.models.ontology import (
    OntologyEntity, OntologyProperty, PropertyDataType,
)
from app.schemas.character_agent import (
    EmbodimentDraftRead,
    EmbodimentEvidence,
    EmbodimentProposal,
    CharacterSourceGroup,
    SourceSceneInput,
)


from app.schemas.character_traits import TraitProfile, TraitEvidence


def _json(value: str | None, default: Any) -> Any:
    if not value:
        return default
    try:
        return json.loads(value)
    except (TypeError, ValueError):
        return default


def _dump(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"), default=str)


def _json_safe(value: Any) -> Any:
    """Normalize graph values before they enter evidence or LLM payloads."""
    if isinstance(value, (DateTime, datetime, Date, date, Time, time)):
        return value.isoformat()
    if isinstance(value, Duration):
        return str(value)
    if isinstance(value, dict):
        return {str(key): _json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(item) for item in value]
    return value


class CharacterEmbodimentService:
    def __init__(self, sql_session, graph_session):
        self.sql = sql_session
        self.graph = graph_session

    @staticmethod
    def pack_evidence(
        evidence: list[EmbodimentEvidence], token_budget: int
    ) -> list[EmbodimentEvidence]:
        """Pack evidence with the provider-neutral ten-characters-per-token budget."""
        char_budget = max(10_000, token_budget * 10)
        packed: list[EmbodimentEvidence] = []
        used = 0
        for item in evidence:
            size = len(item.text)
            if packed and used + size > char_budget:
                continue
            if not packed and size > char_budget:
                item = item.model_copy(update={"text": item.text[:char_budget]})
                size = len(item.text)
            packed.append(item)
            used += size
        return packed

    async def collect_evidence(
        self, ontology_id: int, entity_id: str, *, token_budget: int
    ) -> tuple[dict[str, Any], list[EmbodimentEvidence], str]:
        entity_row = await (await self.graph.run(
            """
            MATCH (entity:EntityInstance {entity_instance_id:$entity_id})
            OPTIONAL MATCH (instance:OntologyInstance)-[:HAS_ENTITY]->(entity)
            RETURN entity, instance.instance_id AS instance_id
            """, entity_id=entity_id,
        )).single()
        if not entity_row:
            raise HTTPException(status_code=404, detail="EntityInstance not found")
        entity = _json_safe(dict(entity_row["entity"]))
        if int(entity.get("ontology_id") or 0) != ontology_id:
            raise HTTPException(status_code=400, detail="EntityInstance does not belong to ontology")

        definition_id = int(entity.get("entity_definition_id") or 0)
        definition = await self.sql.scalar(select(OntologyEntity).where(
            OntologyEntity.id == definition_id, OntologyEntity.ontology_id == ontology_id
        ))
        if not definition:
            raise HTTPException(status_code=409, detail="EntityInstance definition is unavailable")
        property_rows = await self.sql.execute(
            select(OntologyProperty).where(OntologyProperty.entity_id == definition_id)
        )
        properties = list(property_rows.scalars().all())
        property_names = {str(item.id): item.name for item in properties}
        raw_properties = _json(entity.get("properties"), {})
        property_image = next((
            raw_properties.get(str(item.id))
            for item in properties
            if item.data_type == PropertyDataType.IMAGE
            and isinstance(raw_properties.get(str(item.id)), str)
            and raw_properties.get(str(item.id)).strip()
        ), None)
        canonical = {
            "entity_instance_id": entity_id,
            "alias": str(entity.get("alias") or entity_id),
            "avatar_url": entity.get("node_avatar_url") or property_image,
            "authored_text": entity.get("text"),
            "generated_text": entity.get("autogenerated_text"),
            "entity_type": definition.name,
            "entity_type_description": definition.description,
            "properties": {
                property_names.get(str(key), str(key)): value
                for key, value in raw_properties.items()
            },
        }
        evidence: list[EmbodimentEvidence] = [
            EmbodimentEvidence(
                evidence_id=f"identity:{entity_id}:alias", kind="identity",
                source_id=entity_id, text=f"Canonical alias: {canonical['alias']}",
                provenance={"field": "alias"},
            ),
            EmbodimentEvidence(
                evidence_id=f"identity:{entity_id}:ontology-type", kind="identity",
                source_id=entity_id,
                text=_dump({
                    "name": definition.name,
                    "description": definition.description,
                }),
                provenance={
                    "field": "entity_type",
                    "entity_definition_id": definition_id,
                },
            )
        ]
        for key, value in canonical["properties"].items():
            if value not in (None, "", [], {}):
                evidence.append(EmbodimentEvidence(
                    evidence_id=f"property:{entity_id}:{key}", kind="property",
                    source_id=entity_id, text=f"{key}: {value}",
                    provenance={"property_name": key},
                ))
        if canonical["authored_text"]:
            evidence.append(EmbodimentEvidence(
                evidence_id=f"text:{entity_id}:authored", kind="identity",
                source_id=entity_id, text=str(canonical["authored_text"]),
                provenance={"field": "text", "generated": False},
            ))
        if canonical["generated_text"]:
            evidence.append(EmbodimentEvidence(
                evidence_id=f"text:{entity_id}:autogenerated", kind="identity",
                source_id=entity_id, text=str(canonical["generated_text"]),
                provenance={"field": "autogenerated_text", "generated": True},
            ))

        scenes = await self.graph.run(
            """
            MATCH (scene:Scene)-[entity_rel:RELATES_TO]->
                  (entity:EntityInstance {entity_instance_id:$entity_id})
            RETURN scene.id AS id, scene.name AS name,
                   scene.description AS description,
                   properties(entity_rel) AS entity_relation,
                   scene.created_at AS created_at, properties(scene) AS props
            ORDER BY coalesce(toString(created_at), ''), id
            """, entity_id=entity_id,
        )
        cutoff = datetime.now(timezone.utc).isoformat()
        async for row in scenes:
            created = str(row["created_at"] or "")
            evidence.append(EmbodimentEvidence(
                evidence_id=f"scene:{row['id']}", kind="scene", source_id=str(row["id"]),
                text=f"{row['name']}: {row['description']}",
                occurred_at=created or None,
                provenance={
                    "entity_relation": _json_safe(dict(row.get("entity_relation") or {})),
                    "properties": _json_safe(dict(row["props"] or {})),
                },
            ))

        return canonical, self.pack_evidence(evidence, token_budget), cutoff

    async def collect_projection_evidence(
        self, ontology_id: int, entity_id: str, *, token_budget: int
    ) -> tuple[dict[str, Any], list[EmbodimentEvidence], list[CharacterSourceGroup], str]:
        """Separate entity seed evidence from chronologically grouped Scene inputs."""
        canonical, all_evidence, cutoff = await self.collect_evidence(
            ontology_id, entity_id, token_budget=token_budget
        )
        entity_evidence = [item for item in all_evidence if item.kind != "scene"]
        rows = await self.graph.run(
            """
            MATCH (scene:Scene)-[:DERIVED_FROM]->(source:EntityInstance)
            WHERE (EXISTS {
              MATCH (scene)-[:RELATES_TO]->
                    (:EntityInstance {entity_instance_id:$entity_id})
            } OR EXISTS {
              MATCH (scene)-[:CONTAINS]->(:Milestone)-[:RELATES_TO]->
                    (:EntityInstance {entity_instance_id:$entity_id})
            })
            OPTIONAL MATCH (scene)-[entity_rel:RELATES_TO]->
                           (:EntityInstance {entity_instance_id:$entity_id})
            RETURN source.entity_instance_id AS source_id,
                   coalesce(source.alias, source.entity_instance_id) AS source_name,
                   source.created_at AS source_created_at,
                   scene.id AS scene_id, scene.name AS scene_name,
                   scene.description AS scene_description,
                   scene.created_at AS scene_created_at,
                   properties(entity_rel) AS entity_relation
            ORDER BY coalesce(toString(source_created_at), toString(scene_created_at), ''),
                     source_id, coalesce(toString(scene_created_at), ''), scene_id
            """,
            entity_id=entity_id,
        )
        grouped: dict[str, dict[str, Any]] = {}
        async for row in rows:
            source_id = str(row["source_id"])
            group = grouped.setdefault(source_id, {
                "source_group_id": source_id,
                "source_name": str(row["source_name"] or source_id),
                "source_created_at": (
                    str(row["source_created_at"]) if row["source_created_at"] else None
                ),
                "scenes": [],
            })
            group["scenes"].append(SourceSceneInput(
                scene_id=str(row["scene_id"]),
                title=str(row["scene_name"] or row["scene_id"]),
                description=str(row["scene_description"] or ""),
                created_at=str(row["scene_created_at"]) if row["scene_created_at"] else None,
                entity_relation=_json_safe(dict(row["entity_relation"] or {})),
            ))
        groups = [CharacterSourceGroup.model_validate(item) for item in grouped.values()]
        groups.sort(key=lambda group: (
            group.source_created_at
            or next((scene.created_at for scene in group.scenes if scene.created_at), ""),
            group.source_group_id,
        ))
        return canonical, self.pack_evidence(entity_evidence, token_budget), groups, cutoff

    async def load_embodiment_input(
        self, source_entity_id: str, ontology_id: int,
    ) -> dict[str, Any]:
        """Load authored identity, scoped scenes, current profile, and its evidence ledger."""
        # 1. Load the source entity
        entity_row = await (
            await self.graph.run(
                """
                MATCH (entity:EntityInstance {entity_instance_id:$source_id})
                RETURN entity
                """,
                source_id=source_entity_id,
            )
        ).single()
        if not entity_row:
            raise HTTPException(status_code=404, detail="EntityInstance not found")
        entity = _json_safe(dict(entity_row["entity"]))
        if int(entity.get("ontology_id") or 0) != ontology_id:
            raise HTTPException(
                status_code=400, detail="EntityInstance does not belong to ontology"
            )

        # 2. Canonical identity (entity type + property definitions from SQL)
        definition_id = int(entity.get("entity_definition_id") or 0)
        definition = await self.sql.scalar(
            select(OntologyEntity).where(
                OntologyEntity.id == definition_id,
                OntologyEntity.ontology_id == ontology_id,
            )
        )
        if not definition:
            raise HTTPException(
                status_code=409, detail="EntityInstance definition is unavailable"
            )
        property_rows = await self.sql.execute(
            select(OntologyProperty).where(
                OntologyProperty.entity_id == definition_id
            )
        )
        properties_list = list(property_rows.scalars().all())
        property_names = {str(item.id): item.name for item in properties_list}
        raw_properties = _json(entity.get("properties"), {})
        property_image = next(
            (
                raw_properties.get(str(item.id))
                for item in properties_list
                if item.data_type == PropertyDataType.IMAGE
                and isinstance(raw_properties.get(str(item.id)), str)
                and raw_properties.get(str(item.id)).strip()
            ),
            None,
        )
        entity_instance_id = str(
            entity.get("entity_instance_id") or source_entity_id
        )
        canonical_identity = {
            "entity_instance_id": entity_instance_id,
            "alias": str(
                entity.get("alias") or entity.get("entity_instance_id") or source_entity_id
            ),
            "avatar_url": entity.get("node_avatar_url") or property_image,
            "authored_text": entity.get("text"),
            "generated_text": entity.get("autogenerated_text"),
            "entity_type": definition.name,
            "entity_type_description": definition.description,
            "properties": {
                property_names.get(str(key), str(key)): value
                for key, value in raw_properties.items()
            },
        }

        # 3. Check for existing agent, load current traits/aspects/goals
        agent_row = await (
            await self.graph.run(
                """
                OPTIONAL MATCH (agent:CharacterAgent)-[:EMBODIES]->
                              (:EntityInstance {entity_instance_id:$source_id})
                RETURN agent
                """,
                source_id=source_entity_id,
            )
        ).single()
        agent = _json_safe(dict(agent_row["agent"])) if agent_row and agent_row["agent"] else None

        trait_profile = TraitProfile.model_validate_json(agent["trait_profile"]) if agent else TraitProfile()
        trait_evidence = []
        latest_revision = -1
        processed_scene_ids = set()
        if agent:
            if agent.get("subtitle"):
                canonical_identity["subtitle"] = str(agent["subtitle"])
            history = await self.graph.run(
                "MATCH (:CharacterAgent {id:$id})-[:HAS_REVISION]->(r:CharacterIdentityRevision) "
                "RETURN r ORDER BY r.revision_number", id=agent["id"])
            async for record in history:
                revision = dict(record["r"])
                latest_revision = revision["revision_number"]
                processed_scene_ids.update(json.loads(revision.get("scene_ids") or "[]"))
                trait_evidence.extend(TraitEvidence.model_validate(item) for item in json.loads(revision.get("trait_evidence") or "[]"))

        current_aspects: list[dict[str, Any]] = []
        current_goals: list[dict[str, Any]] = []
        agent_id: str | None = None
        if agent:
            agent_id = str(agent.get("id", ""))
            aux = await (
                await self.graph.run(
                    """
                    MATCH (agent:CharacterAgent {id:$agent_id})
                    CALL {
                      WITH agent
                      OPTIONAL MATCH (agent)-[assignment:HAS_ASPECT]->
                                     (aspect:CharacterAspect)
                      WHERE coalesce(assignment.status, 'active') = 'active'
                      RETURN collect({
                        id: aspect.id,
                        name: aspect.name,
                        category: aspect.category,
                        description: aspect.description,
                        importance: assignment.importance,
                        intensity: assignment.intensity,
                        created_at: assignment.created_at
                      }) AS aspects
                    }
                    CALL {
                      WITH agent
                      OPTIONAL MATCH (agent)-[pursuit:PURSUES]->
                                     (goal:CharacterGoal)
                      WHERE coalesce(pursuit.status, goal.status, 'active') = 'active'
                      RETURN collect({
                        id: goal.id,
                        title: goal.title,
                        description: goal.description,
                        goal_type: goal.goal_type,
                        priority: coalesce(pursuit.priority, goal.priority),
                        commitment: coalesce(pursuit.commitment, goal.commitment),
                        created_at: pursuit.created_at
                      }) AS goals
                    }
                    RETURN aspects, goals
                    """,
                    agent_id=agent_id,
                )
            ).single()
            if aux:
                current_aspects = [
                    a for a in (aux["aspects"] or []) if a and a.get("name")
                ]
                current_goals = [
                    g for g in (aux["goals"] or []) if g and g.get("title")
                ]

        # 4. Source entity alias
        source_alias = str(
            entity.get("alias") or entity.get("entity_instance_id") or source_entity_id
        )

        # 5. Scenes involving this entity, grouped by DERIVED_FROM source.
        # A character can be linked directly or through a milestone.  Legacy
        # scenes may not carry denormalized scope fields, but when those fields
        # are present they must match the already validated entity scope.
        scene_rows = await self.graph.run(
            """
            MATCH (scene:Scene)
            WHERE EXISTS {
              MATCH (scene)-[:RELATES_TO]->
                    (:EntityInstance {entity_instance_id:$entity_id})
            } OR EXISTS {
              MATCH (scene)-[:CONTAINS]->(:Milestone)-[:RELATES_TO]->
                    (:EntityInstance {entity_instance_id:$entity_id})
            }
            AND coalesce(scene.ontology_id, $ontology_id) = $ontology_id
            AND coalesce(scene.instance_id, $instance_id) = $instance_id
            OPTIONAL MATCH (scene)-[:DERIVED_FROM]->(source:EntityInstance)
            RETURN DISTINCT scene.id AS scene_id,
                   coalesce(scene.name, scene.id) AS name,
                   coalesce(scene.description, '') AS description,
                   toString(scene.created_at) AS created_at,
                   source.entity_instance_id AS source_id,
                   coalesce(source.alias, source.entity_instance_id) AS source_alias
            ORDER BY coalesce(toString(scene.created_at), ''), scene.id
            """,
            entity_id=entity_instance_id, ontology_id=ontology_id,
            instance_id=entity.get("instance_id"),
        )
        scenes: list[dict[str, Any]] = []
        groups: dict[str, dict[str, Any]] = {}
        async for row in scene_rows:
            s = {
                "scene_id": str(row["scene_id"]),
                "name": str(row["name"]),
                "description": str(row["description"]),
                "created_at": str(row["created_at"]) if row["created_at"] else None,
            }
            scenes.append(s)
            gid = str(row["source_id"]) if row["source_id"] else "__orphan__"
            group = groups.get(gid)
            if not group:
                group = {
                    "source_id": str(row["source_id"]) if row["source_id"] else None,
                    "source_alias": str(row["source_alias"]) if row["source_alias"] else "Unknown source",
                    "scenes": [],
                }
                groups[gid] = group
            group["scenes"].append(s)

        source_groups = sorted(
            groups.values(),
            key=lambda g: (
                g["scenes"][0]["created_at"] or "" if g["scenes"] else "",
                g["source_id"] or "",
            ),
        )

        return {
            "canonical_identity": canonical_identity,
            "trait_profile": trait_profile,
            "trait_evidence": trait_evidence,
            "latest_revision": latest_revision,
            "processed_scene_ids": processed_scene_ids,
            "current_aspects": current_aspects,
            "current_goals": current_goals,
            "source_entity_alias": source_alias,
            "scenes": scenes,
            "source_groups": source_groups,
            "agent_id": agent_id,
        }

    async def append_created_scenes(self, *, agent_id, entity_id, ontology_id,
                                    created_scene_ids, llm_client, settings):
        """Append newly authored scenes with the same chunk and profile rules as drafts."""
        from app.jobs.character_agent.embody_agent import EmbodyAgent
        from app.jobs.character_agent.embody_agent_prompts import PROMPT_VERSION
        from app.jobs.character_agent.profile import _build_timeline, _apply_aspect_ops, _apply_goal_ops
        from app.schemas.character_agent import CharacterTimelineProjection, SceneInput
        from app.services.character_trait_service import chunk_source_scenes, merge_evidence, scene_digest
        from app.services.character_agent_service import CharacterAgentService, _now

        inputs = await self.load_embodiment_input(entity_id, ontology_id)
        if inputs["agent_id"] != agent_id:
            raise ValueError("embodied identity changed")
        processed = await self.graph.run(
            "MATCH (:CharacterAgent {id:$id})-[:HAS_PERSPECTIVE]->(p:ScenePerspective)-[:PROJECTS_ON]->(s:Scene) "
            "RETURN p.scene_id AS id, coalesce(toString(s.created_at), '') AS time, p.source_digest AS digest", id=agent_id)
        seen = {row["id"]: (row["time"], row["digest"]) async for row in processed}
        if not inputs["processed_scene_ids"] <= set(seen):
            raise ValueError("removed processed scenes require CharacterAgent regeneration")
        current_scene_ids = {scene["scene_id"] for scene in inputs["scenes"]}
        if not set(seen) <= current_scene_ids:
            raise ValueError("removed or detached processed scenes require CharacterAgent regeneration")
        last_key = max(((value[0], scene) for scene, value in seen.items()), default=None)
        for group in inputs["source_groups"]:
            for scene in group["scenes"]:
                if scene["scene_id"] in seen and seen[scene["scene_id"]][1] != scene_digest(scene):
                    raise ValueError("edited processed scenes require CharacterAgent regeneration")
        groups = []
        for group in inputs["source_groups"]:
            scenes = [scene for scene in group["scenes"] if scene["scene_id"] in created_scene_ids and scene["scene_id"] not in seen]
            if any(last_key and (scene.get("created_at") or '', scene['scene_id']) <= last_key for scene in scenes):
                raise ValueError("backdated scenes require CharacterAgent regeneration")
            if scenes:
                groups.append({**group, "scenes": scenes})
        profile, evidence = inputs["trait_profile"], inputs["trait_evidence"]
        aspects, goals = inputs["current_aspects"], inputs["current_goals"]
        number = inputs["latest_revision"]
        subtitle = inputs["canonical_identity"].get("subtitle")
        service = CharacterAgentService(self.sql, self.graph)
        for chunk in chunk_source_scenes(groups):
            job = EmbodyAgent(llm_client=llm_client,
                character_incorporation_model=settings.model_character_agent_character_incorporation,
                scene_interpretation_model=settings.model_character_agent_scene_interpretation,
                character_update_model=settings.model_character_agent_update,
                max_aspects=settings.character_agent_embodiment_max_aspects,
                max_goals=settings.character_agent_embodiment_max_goals,
                semantic_correction_attempts=settings.character_agent_embodiment_semantic_correction_attempts)
            result = await job.run(source_entity_id=chunk["source_id"], source_entity_alias=chunk["source_alias"],
                canonical_identity=inputs["canonical_identity"], current_trait_profile=profile,
                current_trait_evidence=evidence, current_aspects=aspects, current_goals=goals,
                scenes=[SceneInput(**scene) for scene in chunk["scenes"]], batch_id=chunk["batch_id"])
            timeline = CharacterTimelineProjection.model_validate_json(_build_timeline(
                source_entity_id=entity_id, source_entity_alias=inputs["source_entity_alias"],
                canonical_identity=inputs["canonical_identity"], current_trait_profile=profile,
                current_aspects=aspects, current_goals=goals, current_subtitle=subtitle,
                per_bundle_results=[result], starting_revision=number,
                max_aspects=settings.character_agent_embodiment_max_aspects,
                max_goals=settings.character_agent_embodiment_max_goals))
            agent = (await service.get_agent(agent_id)).model_dump(mode="json")
            async def persist(tx):
                await service._persist_timeline_tx(tx, agent, timeline, _now(), append=True,
                    provider=settings.model_character_agent_update.provider,
                    model=settings.model_character_agent_update.name, prompt_version=PROMPT_VERSION)
            await self.graph.execute_write(persist)
            profile = result.trait_profile
            evidence = merge_evidence(evidence, result.trait_evidence)
            _apply_aspect_ops(aspects, result.aspect_updates, max_active=settings.character_agent_embodiment_max_aspects)
            _apply_goal_ops(goals, result.goal_updates, max_active=settings.character_agent_embodiment_max_goals)
            subtitle = timeline.revisions[-1].subtitle
            number += 1

    @staticmethod
    def read(draft: CharacterEmbodimentDraft) -> EmbodimentDraftRead:
        observations = _json(draft.observations, None)
        # A short-lived worker version persisted the optional orchestration
        # field in this public, strict observations payload.  Ignore it when
        # reading those completed drafts so they remain reviewable after the
        # deploy that corrects future writes.
        if isinstance(observations, dict):
            observations.pop("subtitle_change", None)
        return EmbodimentDraftRead(
            id=draft.id, ontology_id=draft.ontology_id, source_entity_id=draft.source_entity_id,
            target_character_agent_id=draft.target_character_agent_id, status=draft.status,
            background_job_id=draft.background_job_id, generation_revision=draft.generation_revision,
            evidence=_json(draft.evidence_snapshot, []),
            source_evidence_ids=_json(draft.source_evidence_ids, []),
            evidence_cutoff=draft.evidence_cutoff,
            observations=observations,
            proposal=_json(draft.generated_proposal, None),
            timeline=_json(draft.timeline_projection, None),
            provider=draft.provider, model=draft.model, prompt_version=draft.prompt_version,
            error_message=draft.error_message, generated_at=draft.generated_at,
            created_at=draft.created_at, updated_at=draft.updated_at,
        )
