"""Neo4j business rules for ontology-scoped character administration."""

from __future__ import annotations

import re
import json
from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from fastapi import HTTPException
from neo4j import AsyncSession
from neo4j.exceptions import ConstraintError
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession as SqlAsyncSession

from app.models.ontology import Ontology, OntologyEntity, OntologyProperty, PropertyDataType

from app.schemas.character_agent import (
    CharacterAgentCreate, CharacterAgentRead, CharacterAgentUpdate,
    CharacterAspectAssignmentCreate, CharacterAspectAssignmentRead,
    CharacterAspectAssignmentUpdate, CharacterAspectCreate, CharacterAspectRead,
    CharacterAspectUpdate, CharacterGoalCreate, CharacterGoalRead,
    CharacterGoalUpdate, CharacterEmbodimentCandidate,
    CharacterEmbodimentCandidatePage,
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _normalize_name(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip()).casefold()


def _props(record: Any, key: str = "node") -> dict[str, Any]:
    return dict(record[key])


def _agent_data(data: dict[str, Any]) -> dict[str, Any]:
    data["entity_instance_id"] = data["embodied_entity_instance_id"]
    data.setdefault("trait_adherence", 80)
    return data


class CharacterAgentService:
    def __init__(self, sql_session: SqlAsyncSession, graph_session: AsyncSession) -> None:
        self.sql = sql_session
        self.graph = graph_session

    async def _require_ontology(self, ontology_id: int) -> None:
        result = await self.sql.execute(select(Ontology.id).where(Ontology.id == ontology_id))
        if result.scalar_one_or_none() is None:
            raise HTTPException(status_code=404, detail="Ontology not found")

    async def _entity_type(self, ontology_id: int, entity_definition_id: int) -> OntologyEntity:
        result = await self.sql.execute(
            select(OntologyEntity).where(
                OntologyEntity.id == entity_definition_id,
                OntologyEntity.ontology_id == ontology_id,
            )
        )
        entity_type = result.scalar_one_or_none()
        if entity_type is None:
            raise HTTPException(status_code=404, detail="Entity type not found in ontology")
        return entity_type

    async def _image_property_ids(self, entity_definition_id: int) -> list[str]:
        result = await self.sql.execute(
            select(OntologyProperty.id).where(
                OntologyProperty.entity_id == entity_definition_id,
                OntologyProperty.data_type == PropertyDataType.IMAGE,
            )
        )
        return [str(value) for value in result.scalars().all()]

    @staticmethod
    def _property_image(properties: Any, image_property_ids: list[str]) -> str | None:
        if not properties:
            return None
        try:
            values = json.loads(properties) if isinstance(properties, str) else dict(properties)
        except (TypeError, ValueError, json.JSONDecodeError):
            return None
        for property_id in image_property_ids:
            value = values.get(property_id)
            if isinstance(value, str) and value.strip():
                return value.strip()
        return None

    async def list_embodiment_candidates(
        self, ontology_id: int, entity_definition_id: int, search: str | None,
        skip: int, limit: int,
    ) -> CharacterEmbodimentCandidatePage:
        await self._require_ontology(ontology_id)
        entity_type = await self._entity_type(ontology_id, entity_definition_id)
        image_property_ids = await self._image_property_ids(entity_definition_id)
        search_text = (search or "").strip().casefold()
        params = {
            "ontology_id": ontology_id, "entity_definition_id": entity_definition_id,
            "search": search_text, "skip": skip, "limit": limit,
        }
        where = """
            entity.ontology_id = $ontology_id
            AND toInteger(entity.entity_definition_id) = $entity_definition_id
            AND NOT (:CharacterAgent)-[:EMBODIES]->(entity)
            AND ($search = '' OR toLower(coalesce(entity.alias, '')) CONTAINS $search
                 OR toLower(coalesce(entity.text, '')) CONTAINS $search
                 OR toLower(coalesce(entity.autogenerated_text, '')) CONTAINS $search)
        """
        count_row = await self._one(
            f"MATCH (entity:EntityInstance) WHERE {where} RETURN count(entity) AS total",
            **params,
        )
        result = await self.graph.run(
            f"MATCH (entity:EntityInstance) WHERE {where} RETURN entity "
            "ORDER BY toLower(coalesce(entity.alias, '')), entity.entity_instance_id "
            "SKIP $skip LIMIT $limit",
            **params,
        )
        candidates = []
        async for row in result:
            entity = dict(row["entity"])
            name = str(entity.get("alias") or entity["entity_instance_id"])
            background = str(entity.get("text") or entity.get("autogenerated_text") or name)
            avatar = entity.get("node_avatar_url")
            candidates.append(CharacterEmbodimentCandidate(
                entity_instance_id=str(entity["entity_instance_id"]), ontology_id=ontology_id,
                entity_definition_id=entity_definition_id, entity_type_name=entity_type.name,
                entity_type_image_url=entity_type.image_url, name=name,
                background_story=background, avatar_url=avatar,
                image_url=self._property_image(entity.get("properties"), image_property_ids),
            ))
        return CharacterEmbodimentCandidatePage(
            total=int(count_row["total"] if count_row else 0), skip=skip,
            limit=limit, results=candidates,
        )

    async def _one(self, query: str, **params) -> Any | None:
        result = await self.graph.run(query, **params)
        return await result.single()

    async def _node(self, label: str, node_id: str) -> dict[str, Any]:
        row = await self._one(
            f"MATCH (node:{label} {{id: $node_id}}) "
            "OPTIONAL MATCH (node)-[:OBTAINED_FROM]->(scene:Scene) "
            "RETURN node, scene.id AS obtained_from_scene_id",
            node_id=node_id,
        )
        if not row:
            raise HTTPException(status_code=404, detail=f"{label} not found")
        data = _props(row)
        if label != "CharacterAgent":
            data["obtained_from_scene_id"] = row["obtained_from_scene_id"]
        return data

    async def create_agent(self, payload: CharacterAgentCreate, user_id: int) -> CharacterAgentRead:
        data = payload.model_dump(mode="json")
        entity_id = data.pop("entity_instance_id")
        ontology_id = data["ontology_id"]
        await self._require_ontology(ontology_id)
        image_property_ids_result = await self.sql.execute(
            select(OntologyProperty.id).join(
                OntologyEntity, OntologyEntity.id == OntologyProperty.entity_id
            ).where(
                OntologyEntity.ontology_id == ontology_id,
                OntologyProperty.data_type == PropertyDataType.IMAGE,
            )
        )
        image_property_ids = [str(value) for value in image_property_ids_result.scalars().all()]
        node_id, timestamp = str(uuid4()), _now()

        async def work(tx):
            result = await tx.run(
                """
                OPTIONAL MATCH (entity:EntityInstance {entity_instance_id: $entity_id})
                RETURN entity.ontology_id AS entity_ontology_id, entity IS NOT NULL AS entity_exists,
                       entity.alias AS entity_name, entity.text AS entity_text,
                       entity.autogenerated_text AS entity_autogenerated_text,
                       entity.node_avatar_url AS entity_avatar_url,
                       entity.properties AS entity_properties,
                       EXISTS { MATCH (:CharacterAgent {embodied_entity_instance_id: $entity_id}) } AS existing
                """, entity_id=entity_id,
            )
            scope = await result.single()
            if not scope["entity_exists"]:
                raise HTTPException(status_code=404, detail="EntityInstance not found")
            if scope["entity_ontology_id"] is None or int(scope["entity_ontology_id"]) != ontology_id:
                raise HTTPException(status_code=400, detail="EntityInstance does not belong to ontology")
            if bool(scope["existing"]):
                raise HTTPException(status_code=409, detail="EntityInstance already has a CharacterAgent")
            data["name"] = data.get("name") or scope["entity_name"] or entity_id
            data["background_story"] = (
                data.get("background_story") or scope["entity_text"]
                or scope["entity_autogenerated_text"] or data["name"]
            )
            data["image_url"] = (
                data.get("image_url") or scope["entity_avatar_url"]
                or self._property_image(scope["entity_properties"], image_property_ids)
            )
            props = {
                **data, "id": node_id,
                "embodied_entity_instance_id": entity_id, "created_by_user_id": user_id,
                "created_at": timestamp, "updated_at": timestamp,
            }
            created = await tx.run(
                """
                MATCH (entity:EntityInstance {entity_instance_id: $entity_id, ontology_id: $ontology_id})
                CREATE (agent:CharacterAgent)
                SET agent = $props
                CREATE (agent)-[:EMBODIES]->(entity)
                RETURN agent
                """, ontology_id=ontology_id, entity_id=entity_id, props=props,
            )
            return _props(await created.single(), "agent")

        try:
            created = await self.graph.execute_write(work)
        except ConstraintError as exc:
            raise HTTPException(status_code=409, detail="EntityInstance already has a CharacterAgent") from exc
        return CharacterAgentRead.model_validate(_agent_data(created))

    async def list_agents(self, ontology_id: int | None, agent_status: str | None,
                          entity_id: str | None, skip: int, limit: int) -> list[CharacterAgentRead]:
        clauses, params = [], {"skip": skip, "limit": limit}
        if ontology_id is not None:
            clauses.append("agent.ontology_id = $ontology_id"); params["ontology_id"] = ontology_id
        if agent_status:
            clauses.append("agent.status = $status"); params["status"] = agent_status
        if entity_id:
            clauses.append("agent.embodied_entity_instance_id = $entity_id"); params["entity_id"] = entity_id
        where = " WHERE " + " AND ".join(clauses) if clauses else ""
        result = await self.graph.run(
            f"MATCH (agent:CharacterAgent){where} RETURN agent "
            "ORDER BY agent.created_at DESC, agent.id ASC SKIP $skip LIMIT $limit", **params,
        )
        return [CharacterAgentRead.model_validate(_agent_data(_props(row, "agent"))) async for row in result]

    async def get_agent(self, node_id: str) -> CharacterAgentRead:
        return CharacterAgentRead.model_validate(_agent_data(await self._node("CharacterAgent", node_id)))

    async def load_query_snapshot(self, node_id: str) -> dict[str, Any]:
        """Load the complete active character identity in one graph operation."""
        row = await self._one(
            """
            MATCH (agent:CharacterAgent {id: $node_id})-[:EMBODIES]->(entity:EntityInstance)
            CALL {
              WITH agent
              OPTIONAL MATCH (agent)-[assignment:HAS_ASPECT]->(aspect:CharacterAspect)
              WHERE aspect.status = 'active' AND coalesce(assignment.status, 'active') = 'active'
              WITH aspect, assignment
              ORDER BY assignment.importance DESC, assignment.intensity DESC, aspect.id ASC
              RETURN collect(CASE WHEN aspect IS NULL THEN null ELSE {
                id: aspect.id, name: aspect.name, category: aspect.category,
                description: aspect.description, importance: assignment.importance,
                intensity: assignment.intensity, notes: assignment.notes
              } END) AS aspects
            }
            CALL {
              WITH agent
              OPTIONAL MATCH (agent)-[:PURSUES]->(goal:CharacterGoal)
              WHERE goal.status = 'active'
              WITH goal ORDER BY goal.priority DESC, goal.commitment DESC, goal.status ASC, goal.id ASC
              RETURN collect(CASE WHEN goal IS NULL THEN null ELSE {
                id: goal.id, title: goal.title, description: goal.description,
                goal_type: goal.goal_type, status: goal.status,
                priority: goal.priority, commitment: goal.commitment
              } END) AS goals
            }
            RETURN agent, entity, [item IN aspects WHERE item IS NOT NULL] AS aspects,
                   [item IN goals WHERE item IS NOT NULL] AS goals
            """,
            node_id=node_id,
        )
        if not row:
            raise HTTPException(status_code=404, detail="CharacterAgent not found")
        agent = dict(row["agent"])
        if agent.get("status") != "active":
            raise HTTPException(status_code=409, detail="CharacterAgent is not active")
        agent.setdefault("trait_adherence", 80)
        traits = {
            key: int(agent.get(key, 50))
            for key in (
                "calm_aggressive", "cautious_reckless", "compassionate_ruthless",
                "trusting_suspicious", "honest_deceptive", "patient_impulsive",
                "humble_proud", "cooperative_dominating",
            )
        }
        return {
            "character_agent": {
                "name": str(agent.get("name") or row["entity"].get("alias") or "Character"),
                "background_story": str(agent.get("background_story") or ""),
                "behavioural_traits": traits,
                "trait_adherence": int(agent["trait_adherence"]),
            },
            "aspects": [dict(item) for item in row["aspects"]],
            "goals": [dict(item) for item in row["goals"]],
        }

    async def update_agent(self, node_id: str, payload: CharacterAgentUpdate) -> CharacterAgentRead:
        changes = payload.model_dump(exclude_unset=True, mode="json")
        changes["updated_at"] = _now()
        row = await self._one(
            "MATCH (agent:CharacterAgent {id: $node_id}) SET agent += $changes RETURN agent AS node",
            node_id=node_id, changes=changes,
        )
        if not row:
            raise HTTPException(status_code=404, detail="CharacterAgent not found")
        return CharacterAgentRead.model_validate(_agent_data(_props(row)))

    async def delete_agent(self, node_id: str) -> None:
        async def work(tx):
            found = await tx.run(
                "MATCH (agent:CharacterAgent {id: $node_id}) "
                "OPTIONAL MATCH (agent)-[:HAS_ASPECT]->(aspect:CharacterAspect) "
                "OPTIONAL MATCH (agent)-[:PURSUES]->(goal:CharacterGoal) "
                "RETURN agent, collect(DISTINCT aspect.id) AS aspects, collect(DISTINCT goal.id) AS goals",
                node_id=node_id,
            )
            row = await found.single()
            if not row:
                raise HTTPException(status_code=404, detail="CharacterAgent not found")
            aspect_ids, goal_ids = row["aspects"], row["goals"]
            await tx.run("MATCH (agent:CharacterAgent {id: $node_id}) DETACH DELETE agent", node_id=node_id)
            await tx.run(
                "UNWIND $ids AS id MATCH (node:CharacterAspect {id:id}) "
                "WHERE NOT (:CharacterAgent)-[:HAS_ASPECT]->(node) DETACH DELETE node",
                ids=aspect_ids,
            )
            await tx.run(
                "UNWIND $ids AS id MATCH (node:CharacterGoal {id:id}) "
                "WHERE NOT (:CharacterAgent)-[:PURSUES]->(node) DETACH DELETE node",
                ids=goal_ids,
            )
        await self.graph.execute_write(work)

    async def _validate_scene(self, tx, ontology_id: int, scene_id: str | None) -> None:
        if scene_id is None:
            return
        result = await tx.run(
            "MATCH (scene:Scene {id:$scene_id, ontology_id:$ontology_id}) RETURN scene",
            ontology_id=ontology_id, scene_id=scene_id,
        )
        if not await result.single():
            raise HTTPException(status_code=400, detail="Scene does not belong to OntologyInstance")

    async def _create_definition(self, label: str, payload, user_id: int) -> dict[str, Any]:
        data = payload.model_dump(mode="json")
        scene_id = data.pop("obtained_from_scene_id", None)
        node_id, timestamp = str(uuid4()), _now()
        await self._require_ontology(data["ontology_id"])
        if label == "CharacterAspect":
            data["normalized_name"] = _normalize_name(data["name"])

        async def work(tx):
            await self._validate_scene(tx, data["ontology_id"], scene_id)
            if label == "CharacterAspect":
                duplicate = await tx.run(
                    "MATCH (n:CharacterAspect {ontology_id:$ontology_id, normalized_name:$normalized}) RETURN n.id AS id",
                    ontology_id=data["ontology_id"], normalized=data["normalized_name"],
                )
                if await duplicate.single():
                    raise HTTPException(status_code=409, detail="CharacterAspect normalized name already exists")
            props = {**data, "id": node_id, "created_at": timestamp, "updated_at": timestamp}
            created = await tx.run(f"CREATE (node:{label}) SET node = $props RETURN node", props=props)
            node = _props(await created.single())
            if scene_id:
                await tx.run(
                    f"MATCH (node:{label} {{id:$node_id}}), (scene:Scene {{id:$scene_id}}) CREATE (node)-[:OBTAINED_FROM]->(scene)",
                    node_id=node_id, scene_id=scene_id,
                )
            node["obtained_from_scene_id"] = scene_id
            return node
        try:
            return await self.graph.execute_write(work)
        except ConstraintError as exc:
            if label == "CharacterAspect":
                raise HTTPException(status_code=409, detail="CharacterAspect normalized name already exists") from exc
            raise

    async def create_aspect(self, payload: CharacterAspectCreate, user_id: int) -> CharacterAspectRead:
        return CharacterAspectRead.model_validate(await self._create_definition("CharacterAspect", payload, user_id))

    async def create_goal(self, payload: CharacterGoalCreate, user_id: int) -> CharacterGoalRead:
        return CharacterGoalRead.model_validate(await self._create_definition("CharacterGoal", payload, user_id))

    async def _list_definitions(self, label: str, ontology_id: int, skip: int, limit: int):
        result = await self.graph.run(
            f"MATCH (node:{label} {{ontology_id:$ontology_id}}) "
            "OPTIONAL MATCH (node)-[:OBTAINED_FROM]->(scene:Scene) "
            "RETURN node, scene.id AS obtained_from_scene_id "
            "ORDER BY node.created_at DESC, node.id ASC SKIP $skip LIMIT $limit",
            ontology_id=ontology_id, skip=skip, limit=limit,
        )
        rows = []
        async for row in result:
            item = _props(row); item["obtained_from_scene_id"] = row["obtained_from_scene_id"]; rows.append(item)
        return rows

    async def list_aspects(self, ontology_id: int, skip: int, limit: int) -> list[CharacterAspectRead]:
        return [CharacterAspectRead.model_validate(x) for x in await self._list_definitions("CharacterAspect", ontology_id, skip, limit)]

    async def list_goals(self, ontology_id: int, skip: int, limit: int) -> list[CharacterGoalRead]:
        return [CharacterGoalRead.model_validate(x) for x in await self._list_definitions("CharacterGoal", ontology_id, skip, limit)]

    async def get_aspect(self, node_id: str) -> CharacterAspectRead:
        return CharacterAspectRead.model_validate(await self._node("CharacterAspect", node_id))

    async def get_goal(self, node_id: str) -> CharacterGoalRead:
        return CharacterGoalRead.model_validate(await self._node("CharacterGoal", node_id))

    async def _update_definition(self, label: str, node_id: str, payload) -> dict[str, Any]:
        changes = payload.model_dump(exclude_unset=True, mode="json")
        scene_was_set = "obtained_from_scene_id" in changes
        scene_id = changes.pop("obtained_from_scene_id", None)
        if label == "CharacterAspect" and "name" in changes:
            changes["normalized_name"] = _normalize_name(changes["name"])
        changes["updated_at"] = _now()

        async def work(tx):
            current = await tx.run(f"MATCH (node:{label} {{id:$node_id}}) RETURN node", node_id=node_id)
            row = await current.single()
            if not row:
                raise HTTPException(status_code=404, detail=f"{label} not found")
            old = _props(row)
            await self._validate_scene(tx, old["ontology_id"], scene_id if scene_was_set else None)
            if label == "CharacterAspect" and "normalized_name" in changes:
                duplicate = await tx.run(
                    "MATCH (n:CharacterAspect {ontology_id:$ontology_id, normalized_name:$normalized}) WHERE n.id <> $node_id RETURN n.id",
                    ontology_id=old["ontology_id"], normalized=changes["normalized_name"], node_id=node_id,
                )
                if await duplicate.single():
                    raise HTTPException(status_code=409, detail="CharacterAspect normalized name already exists")
            updated = await tx.run(f"MATCH (node:{label} {{id:$node_id}}) SET node += $changes RETURN node", node_id=node_id, changes=changes)
            node = _props(await updated.single())
            if scene_was_set:
                await tx.run(f"MATCH (node:{label} {{id:$node_id}})-[r:OBTAINED_FROM]->() DELETE r", node_id=node_id)
                if scene_id:
                    await tx.run(f"MATCH (node:{label} {{id:$node_id}}), (scene:Scene {{id:$scene_id}}) CREATE (node)-[:OBTAINED_FROM]->(scene)", node_id=node_id, scene_id=scene_id)
            provenance = await tx.run(f"MATCH (node:{label} {{id:$node_id}}) OPTIONAL MATCH (node)-[:OBTAINED_FROM]->(scene:Scene) RETURN scene.id AS id", node_id=node_id)
            node["obtained_from_scene_id"] = (await provenance.single())["id"]
            return node
        try:
            return await self.graph.execute_write(work)
        except ConstraintError as exc:
            raise HTTPException(status_code=409, detail="CharacterAspect normalized name already exists") from exc

    async def update_aspect(self, node_id: str, payload: CharacterAspectUpdate) -> CharacterAspectRead:
        return CharacterAspectRead.model_validate(await self._update_definition("CharacterAspect", node_id, payload))

    async def update_goal(self, node_id: str, payload: CharacterGoalUpdate) -> CharacterGoalRead:
        return CharacterGoalRead.model_validate(await self._update_definition("CharacterGoal", node_id, payload))

    async def delete_definition(self, label: str, node_id: str) -> None:
        rel = "HAS_ASPECT" if label == "CharacterAspect" else "PURSUES"
        row = await self._one(
            f"MATCH (node:{label} {{id:$node_id}}) RETURN count {{ MATCH (:CharacterAgent)-[:{rel}]->(node) }} AS uses",
            node_id=node_id,
        )
        if not row:
            raise HTTPException(status_code=404, detail=f"{label} not found")
        if int(row["uses"] or 0):
            raise HTTPException(status_code=409, detail=f"{label} is still assigned")
        await self.graph.run(f"MATCH (node:{label} {{id:$node_id}}) DETACH DELETE node", node_id=node_id)

    async def assign_aspect(self, agent_id: str, payload: CharacterAspectAssignmentCreate) -> CharacterAspectAssignmentRead:
        values = payload.model_dump(mode="json"); aspect_id = values.pop("character_aspect_id"); timestamp = _now()
        values.update(created_at=timestamp, updated_at=timestamp)
        row = await self._one(
            """
            MATCH (agent:CharacterAgent {id:$agent_id}), (aspect:CharacterAspect {id:$aspect_id})
            WHERE agent.ontology_id = aspect.ontology_id
              AND NOT (agent)-[:HAS_ASPECT]->(aspect)
            CREATE (agent)-[rel:HAS_ASPECT]->(aspect) SET rel = $values
            WITH aspect, rel
            OPTIONAL MATCH (aspect)-[:OBTAINED_FROM]->(scene:Scene)
            RETURN aspect, rel, scene.id AS obtained_from_scene_id
            """, agent_id=agent_id, aspect_id=aspect_id, values=values,
        )
        if not row:
            await self._assignment_error(agent_id, aspect_id, "CharacterAspect", "HAS_ASPECT")
        return self._aspect_assignment(row)

    async def _assignment_error(self, agent_id: str, target_id: str, label: str, rel: str) -> None:
        agent = await self._one("MATCH (n:CharacterAgent {id:$id}) RETURN n", id=agent_id)
        target = await self._one(f"MATCH (n:{label} {{id:$id}}) RETURN n", id=target_id)
        if not agent or not target:
            raise HTTPException(status_code=404, detail="CharacterAgent or target not found")
        duplicate = await self._one(f"MATCH (:CharacterAgent {{id:$agent}})-[r:{rel}]->(:{label} {{id:$target}}) RETURN r", agent=agent_id, target=target_id)
        if duplicate:
            raise HTTPException(status_code=409, detail="Relationship already exists")
        raise HTTPException(status_code=400, detail="Cross-ontology connection rejected")

    def _aspect_assignment(self, row) -> CharacterAspectAssignmentRead:
        aspect = _props(row, "aspect"); aspect["obtained_from_scene_id"] = row["obtained_from_scene_id"]
        rel = dict(row["rel"])
        return CharacterAspectAssignmentRead(aspect=CharacterAspectRead.model_validate(aspect), **rel)

    async def list_agent_aspects(self, agent_id: str) -> list[CharacterAspectAssignmentRead]:
        if not await self._one("MATCH (n:CharacterAgent {id:$id}) RETURN n", id=agent_id):
            raise HTTPException(status_code=404, detail="CharacterAgent not found")
        result = await self.graph.run(
            "MATCH (:CharacterAgent {id:$id})-[rel:HAS_ASPECT]->(aspect:CharacterAspect) "
            "OPTIONAL MATCH (aspect)-[:OBTAINED_FROM]->(scene:Scene) "
            "RETURN aspect, rel, scene.id AS obtained_from_scene_id ORDER BY rel.created_at DESC, aspect.id ASC", id=agent_id,
        )
        return [self._aspect_assignment(row) async for row in result]

    async def update_assignment(self, agent_id: str, aspect_id: str, payload: CharacterAspectAssignmentUpdate) -> CharacterAspectAssignmentRead:
        changes = payload.model_dump(exclude_unset=True, mode="json"); changes["updated_at"] = _now()
        row = await self._one(
            "MATCH (:CharacterAgent {id:$agent})-[rel:HAS_ASPECT]->(aspect:CharacterAspect {id:$aspect}) "
            "SET rel += $changes WITH aspect, rel "
            "OPTIONAL MATCH (aspect)-[:OBTAINED_FROM]->(scene:Scene) "
            "RETURN aspect, rel, scene.id AS obtained_from_scene_id",
            agent=agent_id, aspect=aspect_id, changes=changes,
        )
        if not row:
            raise HTTPException(status_code=404, detail="Aspect assignment not found")
        return self._aspect_assignment(row)

    async def pursue_goal(self, agent_id: str, goal_id: str) -> CharacterGoalRead:
        row = await self._one(
            "MATCH (agent:CharacterAgent {id:$agent}), (goal:CharacterGoal {id:$goal}) "
            "WHERE agent.ontology_id=goal.ontology_id AND NOT (agent)-[:PURSUES]->(goal) "
            "CREATE (agent)-[:PURSUES {created_at:$now}]->(goal) "
            "WITH goal "
            "OPTIONAL MATCH (goal)-[:OBTAINED_FROM]->(scene:Scene) RETURN goal AS node, scene.id AS obtained_from_scene_id",
            agent=agent_id, goal=goal_id, now=_now(),
        )
        if not row:
            await self._assignment_error(agent_id, goal_id, "CharacterGoal", "PURSUES")
        data = _props(row); data["obtained_from_scene_id"] = row["obtained_from_scene_id"]
        return CharacterGoalRead.model_validate(data)

    async def list_agent_goals(self, agent_id: str) -> list[CharacterGoalRead]:
        if not await self._one("MATCH (n:CharacterAgent {id:$id}) RETURN n", id=agent_id):
            raise HTTPException(status_code=404, detail="CharacterAgent not found")
        return [CharacterGoalRead.model_validate(x) for x in await self._list_related_goals(agent_id)]

    async def _list_related_goals(self, agent_id: str):
        result = await self.graph.run(
            "MATCH (:CharacterAgent {id:$id})-[:PURSUES]->(node:CharacterGoal) "
            "OPTIONAL MATCH (node)-[:OBTAINED_FROM]->(scene:Scene) RETURN node, scene.id AS obtained_from_scene_id "
            "ORDER BY node.created_at DESC, node.id ASC", id=agent_id,
        )
        rows=[]
        async for row in result:
            data=_props(row); data["obtained_from_scene_id"]=row["obtained_from_scene_id"]; rows.append(data)
        return rows

    async def unassign(self, agent_id: str, target_id: str, label: str, rel: str) -> None:
        async def work(tx):
            result = await tx.run(
                f"MATCH (:CharacterAgent {{id:$agent}})-[r:{rel}]->(node:{label} {{id:$target}}) DELETE r RETURN node.id AS id",
                agent=agent_id, target=target_id,
            )
            if not await result.single():
                raise HTTPException(status_code=404, detail="Relationship not found")
            remaining = await tx.run(f"MATCH (:CharacterAgent)-[r:{rel}]->(:{label} {{id:$target}}) RETURN count(r) AS count", target=target_id)
            if int((await remaining.single())["count"] or 0) == 0:
                await tx.run(f"MATCH (node:{label} {{id:$target}}) DETACH DELETE node", target=target_id)
        await self.graph.execute_write(work)
