"""Endpoints to export legacy artifacts from backend/data/prod.db into media files."""

from __future__ import annotations

import os
import sqlite3
from datetime import datetime
from pathlib import Path
from urllib.parse import urlparse

from fastapi import APIRouter, Depends, HTTPException, status

from app.api.deps import get_current_active_admin_or_world_builder
from app.core.config import get_settings
from app.models.user import User

router = APIRouter(prefix="/legacy", tags=["legacy-export"])


def _slugify(name: str) -> str:
    cleaned = "".join(ch if ch.isalnum() or ch in (" ", "-", "_") else "_" for ch in (name or ""))
    return "_".join(cleaned.strip().split())[:200] or "page"


def _resolve_legacy_db() -> Path:
    old_url = os.getenv("OLD_DATABASE_URL", "sqlite+aiosqlite:///../backend/data/prod.db")
    db_path: Path | None = None
    try:
        parsed = urlparse(old_url.replace("+aiosqlite", ""))
        if parsed.scheme.startswith("sqlite"):
            raw_path = parsed.path.lstrip("/")
            candidate = Path(raw_path)
            if candidate.exists():
                db_path = candidate
    except Exception:
        db_path = None
    if db_path is None or not db_path.exists():
        for candidate in (
            Path("../backend/data/prod.db"),
            Path("backend/data/prod.db"),
            Path("./backend/data/prod.db"),
        ):
            if candidate.exists():
                db_path = candidate
                break
    if db_path is None or not db_path.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Legacy DB not found. Set OLD_DATABASE_URL or place prod.db under ../backend/data/",
        )
    return db_path


def _sanitize_email(email: str | None) -> str:
    if not email:
        return "unknown_user"
    cleaned = email.strip().lower().replace("@", "_at_").replace(".", "_")
    safe = "".join(ch if ch.isalnum() or ch in {"_", "-"} else "_" for ch in cleaned)
    return safe[:200] or "unknown_user"


def _format_note_date(raw_date: str | None, fallback: str | None = None) -> tuple[str, str]:
    candidate = raw_date or fallback or ""
    candidate = candidate.strip()
    if not candidate:
        return "", "unknown_date"

    iso_value = candidate
    try:
        # Support microseconds without timezone and with Z suffix
        normalized = candidate.replace("Z", "+00:00")
        dt = datetime.fromisoformat(normalized)
        iso_value = dt.isoformat()
        safe_value = dt.strftime("%Y%m%dT%H%M%S")
    except ValueError:
        safe_value = "".join(ch if ch.isalnum() or ch in {"_", "-"} else "_" for ch in candidate)[:200]
        if not safe_value:
            safe_value = "unknown_date"
    return iso_value, safe_value


@router.post(
    "/export-pages",
    status_code=status.HTTP_200_OK,
)
def export_legacy_pages(
    _current_user: User = Depends(get_current_active_admin_or_world_builder),
) -> dict:
    """Export legacy Page records from backend/data/prod.db to media/old_format files.

    Writes two files per page when data exists:
    - media/old_format/{gameworld_id}/{concept_id}/{page_name}_context.html
    - media/old_format/{gameworld_id}/{concept_id}/{page_name}_autogenerated_context.html
    """
    settings = get_settings()
    db_path = _resolve_legacy_db()

    base_out = Path(settings.media_root) / "old_format"
    base_out.mkdir(parents=True, exist_ok=True)

    written: list[str] = []
    pages_total = 0
    try:
        conn = sqlite3.connect(str(db_path))
        conn.row_factory = sqlite3.Row
        cur = conn.cursor()
        cur.execute(
            """
            SELECT id, gameworld_id, concept_id, name, content, autogenerated_content
            FROM page
            """
        )
        rows = cur.fetchall()
        pages_total = len(rows)
        for r in rows:
            gw = r["gameworld_id"]
            cid = r["concept_id"]
            name = r["name"] or "page"
            safe = _slugify(name)
            out_dir = base_out / str(gw) / str(cid)
            out_dir.mkdir(parents=True, exist_ok=True)

            if r["content"]:
                p = out_dir / f"{safe}_context.html"
                # Write as HTML-safe content; assume stored content may be HTML already
                p.write_text(r["content"], encoding="utf-8")
                written.append(str(p))
            if r["autogenerated_content"]:
                p2 = out_dir / f"{safe}_autogenerated_context.html"
                p2.write_text(r["autogenerated_content"], encoding="utf-8")
                written.append(str(p2))
        conn.close()
    except sqlite3.Error as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"SQLite error: {e}",
        )

    return {"pages_scanned": pages_total, "files_written": len(written), "paths": written[:1000]}


@router.post(
    "/export-notes",
    status_code=status.HTTP_200_OK,
)
def export_legacy_notes(
    _current_user: User = Depends(get_current_active_admin_or_world_builder),
) -> dict:
    """Export legacy UserNote records into text files grouped by user email."""

    settings = get_settings()
    db_path = _resolve_legacy_db()

    base_out = Path(settings.media_root) / "old_notes"
    base_out.mkdir(parents=True, exist_ok=True)

    written: list[str] = []
    processed = 0

    try:
        conn = sqlite3.connect(str(db_path))
        conn.row_factory = sqlite3.Row
        cur = conn.cursor()
        cur.execute(
            """
            SELECT n.id,
                   n.content,
                   n.note_date,
                   n.created_at,
                   u.email AS user_email
            FROM usernote AS n
            LEFT JOIN user AS u ON u.id = n.user_id
            """
        )
        rows = cur.fetchall()
        processed = len(rows)
        for row in rows:
            email = row["user_email"] or "unknown@example.com"
            safe_email = _sanitize_email(email)
            iso_date, safe_date = _format_note_date(row["note_date"], row["created_at"])
            content = row["content"] or ""

            out_dir = base_out / safe_email
            out_dir.mkdir(parents=True, exist_ok=True)

            filename = f"{safe_date}.txt"
            path = out_dir / filename
            suffix = 1
            while path.exists():
                suffix += 1
                path = out_dir / f"{safe_date}_{suffix}.txt"

            body_lines = [
                f"User Email: {email}",
                f"Note Date: {iso_date or 'Unknown'}",
                "",
                content,
            ]
            path.write_text("\n".join(body_lines), encoding="utf-8")
            written.append(str(path))
        conn.close()
    except sqlite3.Error as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"SQLite error: {exc}",
        )

    return {
        "notes_scanned": processed,
        "files_written": len(written),
        "paths": written[:1000],
    }
